var annotated_dup =
[
    [ "Bio", "namespace_bio.html", [
      [ "ImageUtil", "class_bio_1_1_image_util.html", null ],
      [ "ISliceProvider", "interface_bio_1_1_i_slice_provider.html", "interface_bio_1_1_i_slice_provider" ],
      [ "ISlideExternInfo", "interface_bio_1_1_i_slide_extern_info.html", "interface_bio_1_1_i_slide_extern_info" ],
      [ "ISlideSource", "interface_bio_1_1_i_slide_source.html", null ],
      [ "LruCache", "class_bio_1_1_lru_cache.html", "class_bio_1_1_lru_cache" ],
      [ "MagicSelect", "class_bio_1_1_magic_select.html", "class_bio_1_1_magic_select" ],
      [ "ROIManager", "class_bio_1_1_r_o_i_manager.html", "class_bio_1_1_r_o_i_manager" ],
      [ "SliceInfo", "class_bio_1_1_slice_info.html", "class_bio_1_1_slice_info" ],
      [ "SliceParame", "class_bio_1_1_slice_parame.html", "class_bio_1_1_slice_parame" ],
      [ "SlideBase", "class_bio_1_1_slide_base.html", "class_bio_1_1_slide_base" ],
      [ "SlideImage", "class_bio_1_1_slide_image.html", "class_bio_1_1_slide_image" ],
      [ "SlideSliceLayer", "class_bio_1_1_slide_slice_layer.html", "class_bio_1_1_slide_slice_layer" ],
      [ "SlideSourceBase", "class_bio_1_1_slide_source_base.html", "class_bio_1_1_slide_source_base" ],
      [ "SlideTileLayer", "class_bio_1_1_slide_tile_layer.html", "class_bio_1_1_slide_tile_layer" ],
      [ "TileCache", "class_bio_1_1_tile_cache.html", "class_bio_1_1_tile_cache" ],
      [ "TileInformation", "class_bio_1_1_tile_information.html", "class_bio_1_1_tile_information" ]
    ] ],
    [ "BioGTK", "namespace_bio_g_t_k.html", [
      [ "About", "class_bio_g_t_k_1_1_about.html", "class_bio_g_t_k_1_1_about" ],
      [ "ApplyFilter", "class_bio_g_t_k_1_1_apply_filter.html", "class_bio_g_t_k_1_1_apply_filter" ],
      [ "BioConsole", "class_bio_g_t_k_1_1_bio_console.html", "class_bio_g_t_k_1_1_bio_console" ],
      [ "BioImage", "class_bio_g_t_k_1_1_bio_image.html", "class_bio_g_t_k_1_1_bio_image" ],
      [ "ChannelsTool", "class_bio_g_t_k_1_1_channels_tool.html", "class_bio_g_t_k_1_1_channels_tool" ],
      [ "ColorTool", "class_bio_g_t_k_1_1_color_tool.html", "class_bio_g_t_k_1_1_color_tool" ],
      [ "ComboPicker", "class_bio_g_t_k_1_1_combo_picker.html", "class_bio_g_t_k_1_1_combo_picker" ],
      [ "Filt", "class_bio_g_t_k_1_1_filt.html", "class_bio_g_t_k_1_1_filt" ],
      [ "FiltersView", "class_bio_g_t_k_1_1_filters_view.html", "class_bio_g_t_k_1_1_filters_view" ],
      [ "Focus", "class_bio_g_t_k_1_1_focus.html", "class_bio_g_t_k_1_1_focus" ],
      [ "Function", "class_bio_g_t_k_1_1_function.html", "class_bio_g_t_k_1_1_function" ],
      [ "Functions", "class_bio_g_t_k_1_1_functions.html", "class_bio_g_t_k_1_1_functions" ],
      [ "HistogramControl", "class_bio_g_t_k_1_1_histogram_control.html", "class_bio_g_t_k_1_1_histogram_control" ],
      [ "ImageInfo", "class_bio_g_t_k_1_1_image_info.html", "class_bio_g_t_k_1_1_image_info" ],
      [ "ImageView", "class_bio_g_t_k_1_1_image_view.html", "class_bio_g_t_k_1_1_image_view" ],
      [ "NodeView", "class_bio_g_t_k_1_1_node_view.html", "class_bio_g_t_k_1_1_node_view" ],
      [ "NumberPicker", "class_bio_g_t_k_1_1_number_picker.html", "class_bio_g_t_k_1_1_number_picker" ],
      [ "Objectives", "class_bio_g_t_k_1_1_objectives.html", "class_bio_g_t_k_1_1_objectives" ],
      [ "PlateTool", "class_bio_g_t_k_1_1_plate_tool.html", "class_bio_g_t_k_1_1_plate_tool" ],
      [ "Play", "class_bio_g_t_k_1_1_play.html", "class_bio_g_t_k_1_1_play" ],
      [ "Plot", "class_bio_g_t_k_1_1_plot.html", "class_bio_g_t_k_1_1_plot" ],
      [ "Plugin", "class_bio_g_t_k_1_1_plugin.html", "class_bio_g_t_k_1_1_plugin" ],
      [ "Progress", "class_bio_g_t_k_1_1_progress.html", "class_bio_g_t_k_1_1_progress" ],
      [ "QuPath", "class_bio_g_t_k_1_1_qu_path.html", "class_bio_g_t_k_1_1_qu_path" ],
      [ "Recorder", "class_bio_g_t_k_1_1_recorder.html", "class_bio_g_t_k_1_1_recorder" ],
      [ "RectangleD", "struct_bio_g_t_k_1_1_rectangle_d.html", "struct_bio_g_t_k_1_1_rectangle_d" ],
      [ "Resolution", "struct_bio_g_t_k_1_1_resolution.html", "struct_bio_g_t_k_1_1_resolution" ],
      [ "Resolutions", "class_bio_g_t_k_1_1_resolutions.html", "class_bio_g_t_k_1_1_resolutions" ],
      [ "RLShutter", "class_bio_g_t_k_1_1_r_l_shutter.html", "class_bio_g_t_k_1_1_r_l_shutter" ],
      [ "ROI", "class_bio_g_t_k_1_1_r_o_i.html", "class_bio_g_t_k_1_1_r_o_i" ],
      [ "Scripting", "class_bio_g_t_k_1_1_scripting.html", "class_bio_g_t_k_1_1_scripting" ],
      [ "Search", "class_bio_g_t_k_1_1_search.html", "class_bio_g_t_k_1_1_search" ],
      [ "SetTool", "class_bio_g_t_k_1_1_set_tool.html", "class_bio_g_t_k_1_1_set_tool" ],
      [ "StackTools", "class_bio_g_t_k_1_1_stack_tools.html", "class_bio_g_t_k_1_1_stack_tools" ],
      [ "Stage", "class_bio_g_t_k_1_1_stage.html", "class_bio_g_t_k_1_1_stage" ],
      [ "TabsView", "class_bio_g_t_k_1_1_tabs_view.html", "class_bio_g_t_k_1_1_tabs_view" ],
      [ "TextInput", "class_bio_g_t_k_1_1_text_input.html", "class_bio_g_t_k_1_1_text_input" ],
      [ "TLShutter", "class_bio_g_t_k_1_1_t_l_shutter.html", "class_bio_g_t_k_1_1_t_l_shutter" ],
      [ "Tolerance", "class_bio_g_t_k_1_1_tolerance.html", "class_bio_g_t_k_1_1_tolerance" ],
      [ "Tools", "class_bio_g_t_k_1_1_tools.html", "class_bio_g_t_k_1_1_tools" ],
      [ "Updater", "class_bio_g_t_k_1_1_updater.html", "class_bio_g_t_k_1_1_updater" ]
    ] ]
];