BioImager: BioImager.ImageView Class Reference
BioImager.ImageView Class Reference
ImageView control for image stacks, pyramidal and whole-slide-images.
Classes
struct Layer
Public Types
enum ViewMode
Public Member Functions
ImageView (BioImage im, bool OpenWithOpenSlide=true)
Initializing the image viewer. *‍/.
ImageView ()
Initializing the ImageView class. *‍/.
void SetCoordinate (int z, int c, int t)
ZCT GetCoordinate ()
void AddImage (BioImage im)
void UpdateRGBChannels ()
void InitGUI ()
void UpdateSelectBoxSize (float size)
void UpdateOverlay ()
void UpdateStatus ()
void UpdateView ()
void RenderFrame ()
void UpdateView (bool refresh)
void UpdateImages ()
void RemoveImage (int i)
void RemoveImages ()
void UpdateImage ()
void GetRange ()
void DrawView (System.Drawing.Graphics g)
Draws the viewport when Hardware Acceleration is off.
double GetScale ()
void CopySelection ()
It takes the selected ROIs and copies them to the clipboard.
void PasteSelection ()
PointD ImageToViewSpace (double x, double y)
PointF ToViewSpace (PointF p)
PointD ToViewSpace (PointD p)
PointD ToViewSpace (double x, double y)
double ToViewSizeH (double d)
double ToViewW (double d)
double ToViewH (double d)
PointD ToScreenSpace (double x, double y)
PointD ToScreenSpace (PointD p)
System.Drawing.PointF ToScreenSpace (PointF p)
System.Drawing.PointF[] ToScreenSpace (PointF[] p)
PointF ToScreenSpace (Point3D p)
float ToScreenScaleW (double x)
float ToScreenScaleH (double y)
PointF ToScreenScale (PointD p)
System.Drawing.RectangleF ToScreenRectF (double x, double y, double w, double h)
RawRectangleF ToRawRectF (double x, double y, double w, double h)
System.Drawing.RectangleF ToScreenSpace (RectangleD p)
System.Drawing.RectangleF ToScreenSpace (RectangleF p)
System.Drawing.RectangleF[] ToScreenSpace (RectangleD[] p)
System.Drawing.RectangleF[] ToScreenSpace (RectangleF[] p)
PointF[] ToScreenSpace (PointD[] p)
float ToScreenW (double x)
float ToScreenH (double y)
void ImageView_KeyDown (object sender, KeyEventArgs e)
void GoToImage ()
void GoToImage (int i)
new void Dispose ()
void GoToStage ()
void MoveStageToImage ()
void MoveStageToImage (int i)
Public Attributes
Direct2D dx = null
Image Buf = null
bool init = false
List< BioImage > Images = new List<BioImage>()
string filepath = ""
int serie = 0
int minSizeX = 50
int minSizeY = 20
bool loopZ = true
bool loopT = true
bool loopC = true
bool showRROIs = true
bool showGROIs = true
bool showBROIs = true
Static Public Attributes
static List< ROI > selectedAnnotations = new List<ROI>()
static PointD mouseDown
static bool down
static PointD mouseUp
static bool up
static MouseButtons mouseUpButtons
static MouseButtons mouseDownButtons
static bool showBounds = true
static bool showText = true
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
List< Layer > Layers [get, set]
static BioImage SelectedImage [get]
static Bitmap SelectedBuffer [get]
static bool Ctrl [get]
int SelectedIndex [get, set]
A property that is used to set the selected index of the image. *‍/.
Tools tools [get]
bool ShowStage [get, set]
bool ShowOverview [get, set]
bool ShowControls [get, set]
Setting the visibility of the trackBarPanel. *‍/.
bool ShowStatus [get, set]
Setting the value of the property ShowStatus. *‍/.
double PxWmicron [get, set]
Only used when opening stacks.
double PxHmicron [get, set]
Only used when opening stacks.
ViewMode Mode [get, set]
Setting the view mode of the application. *‍/.
string Path [get]
A property that returns the filepath. *‍/.
Channel RChannel [get]
A property that returns the R channel of the selected image. *‍/.
Channel GChannel [get]
A property that returns the G channel of the image. *‍/.
Channel BChannel [get]
Getting the B channel of the image. *‍/.
bool OpenSlide [get]
int? MacroResolution [get]
int? LabelResolution [get]
int ViewWidth [get]
int ViewHeight [get]
PointD Origin [get, set]
A property of the class PointD. *‍/.
PointD PyramidalOrigin [get, set]
Setting the value of the pyramidalOrigin variable. *‍/.
double Resolution [get, set]
A property of the class ImageViewer. It is a getter and setter for the resolution of the image.
int Level [get]
Current level when viewing whole-slide and pyramidal images.
new AForge.SizeF Scale [get, set]
Scale when opening image stacks.
bool HardwareAcceleration [get, set]
Whether or not Hardware Acceleration should be used for rendering.
ContextMenuStrip ViewContextMenu [get]
A property that returns a ContextMenuStrip object. *‍/.
int ZFps [get, set]
Setting the interval of the timer to the value of the fps. *‍/.
int TimeFps [get, set]
Setting the interval of the timer to the value of the timefps variable. *‍/.
int CFps [get, set]
Setting the interval of the timer to the inverse of the fps. *‍/.
List< ROI > AnnotationsR [get]
List< ROI > AnnotationsG [get]
List< ROI > AnnotationsB [get]
List< ROI > AnnotationsRGB [get]
PointD PyramidalOriginTransformed [get, set]
PointD MouseDownInt [get, set]
PointD MouseMoveInt [get, set]
Detailed Description
ImageView control for image stacks, pyramidal and whole-slide-images.
Definition at line 18 of file ImageView.cs.
Member Enumeration Documentation
ViewMode
enum BioImager.ImageView.ViewMode
Definition at line 487 of file ImageView.cs.
        {
            Raw,
            Filtered,
            RGBImage,
            Emission,
        }
Constructor & Destructor Documentation
ImageView() [1/2]
BioImager.ImageView.ImageView (BioImage im, bool OpenWithOpenSlide = true)
Initializing the image viewer. *‍/.
Definition at line 21 of file ImageView.cs.
        {
            string file = im.ID.Replace("\\", "/");
            InitializeComponent();
            App.viewer = this;
            if (im.slideImage != null && im.isPyramidal && OpenSlide)
                openSlide = true;
            serie = im.series;
            Dock = DockStyle.Fill;
            AddImage(im);
            App.viewer = this;
            if (file == "" || file == null)
                return;
            SetCoordinate(0, 0, 0);
            InitGUI();
            MouseWheel += new System.Windows.Forms.MouseEventHandler(ImageView_MouseWheel);
            zBar.MouseWheel += new System.Windows.Forms.MouseEventHandler(ZTrackBar_MouseWheel);
            cBar.MouseWheel += new System.Windows.Forms.MouseEventHandler(CTrackBar_MouseWheel);
            tBar.MouseWheel += new System.Windows.Forms.MouseEventHandler(TimeTrackBar_MouseWheel);
            //We set the trackbar event to handled so that it only scrolls one tick not the default multiple.
            zBar.MouseWheel += (sender, e) => ((HandledMouseEventArgs)e).Handled = true;
            tBar.MouseWheel += (sender, e) => ((HandledMouseEventArgs)e).Handled = true;
            cBar.MouseWheel += (sender, e) => ((HandledMouseEventArgs)e).Handled = true;
            TimeFps = 60;
            ZFps = 60;
            CFps = 1;
            // Change parent for overlay PictureBox.
            overlayPictureBox.Parent = pictureBox;
            overlayPictureBox.Location = new System.Drawing.Point(0, 0);
            resolutions = im.Resolutions;
            if (im.isPyramidal)
            {
                dxPanel.Size = new System.Drawing.Size(800, 600);
                if (im.openSlideImage != null && OpenWithOpenSlide)
                {
                    openSlide = true;
                    Initialize(im.file);
                }
                else
                    Initialize(im.file);
                hScrollBar.Maximum = im.Resolutions[Level].SizeX;
                vScrollBar.Maximum = im.Resolutions[Level].SizeY;
                hScrollBar.Visible = true;
                vScrollBar.Visible = true;
            }
            else
            {
                hScrollBar.Visible = false;
                vScrollBar.Visible = false;
                pictureBox.Width += 18;
                pictureBox.Height += 18;
                overlayPictureBox.Width += 18;
                overlayPictureBox.Height += 18;
                Tools.selectBoxSize = ROI.selectBoxSize;
            }
            update = true;
            InitPreview();
            GoToImage();
            UpdateImages();
            Mode = ViewMode.Filtered;
            UpdateView();
            if (HardwareAcceleration)
            {
                dx = new Direct2D();
                dx.Initialize(new Configuration("BioImager", dxPanel.Width, dxPanel.Height), dxPanel.Handle);
            }
        }
References BioImager.ImageView.AddImage(), BioImager.ImageView.CFps, BioImager.ImageView.GoToImage(), BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.InitGUI(), BioImager.ImageView.Level, BioImager.ImageView.Mode, BioImager.ImageView.SetCoordinate(), BioImager.ImageView.TimeFps, BioImager.ImageView.UpdateImages(), BioImager.ImageView.UpdateView(), and BioImager.ImageView.ZFps.
ImageView() [2/2]
BioImager.ImageView.ImageView ()
Initializing the ImageView class. *‍/.
Definition at line 90 of file ImageView.cs.
        {
            InitializeComponent();
            Dock = DockStyle.Fill;
            App.viewer = this;
            SetCoordinate(0, 0, 0);
            InitGUI();
            //Buf = image.GetBufByCoord(GetCoordinate());
            MouseWheel += new System.Windows.Forms.MouseEventHandler(ImageView_MouseWheel);
            zBar.MouseWheel += new System.Windows.Forms.MouseEventHandler(ZTrackBar_MouseWheel);
            cBar.MouseWheel += new System.Windows.Forms.MouseEventHandler(CTrackBar_MouseWheel);
            tBar.MouseWheel += new System.Windows.Forms.MouseEventHandler(TimeTrackBar_MouseWheel);
            //We set the trackbar event to handled so that it only scrolls one tick not the default multiple.
            zBar.MouseWheel += (sender, e) => ((HandledMouseEventArgs)e).Handled = true;
            tBar.MouseWheel += (sender, e) => ((HandledMouseEventArgs)e).Handled = true;
            cBar.MouseWheel += (sender, e) => ((HandledMouseEventArgs)e).Handled = true;
            TimeFps = 60;
            ZFps = 60;
            CFps = 1;
            // Change parent for overlay PictureBox.
            overlayPictureBox.Parent = pictureBox;
            overlayPictureBox.Location = new System.Drawing.Point(0, 0);
            update = true;
            UpdateImages();
            GoToImage();
            UpdateView();
            if (HardwareAcceleration)
            {
                dx = new Direct2D();
                dx.Initialize(new Configuration("BioImager", dxPanel.Width, dxPanel.Height), dxPanel.Handle);
            }
        }
References BioImager.ImageView.CFps, BioImager.ImageView.GoToImage(), BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.InitGUI(), BioImager.ImageView.SetCoordinate(), BioImager.ImageView.TimeFps, BioImager.ImageView.UpdateImages(), BioImager.ImageView.UpdateView(), and BioImager.ImageView.ZFps.
Member Function Documentation
AddImage()
void BioImager.ImageView.AddImage (BioImage im)
This function adds an image to the list of images, and then updates the GUI to reflect the new image
Parameters
BioImage This is a class that contains the image data, and some other information about the image.
Definition at line 285 of file ImageView.cs.
        {
            Images.Add(im);
            SelectedIndex = Images.Count - 1;
            bool c = false;
            foreach (var item in layers)
            {
                if (item.Resolution == im.PhysicalSizeX)
                    c = true;
            }
            if (!c)
                Layers.Add(new Layer(im.PhysicalSizeX));
            if (im.isPyramidal)
            {
                hScrollBar.Maximum = im.Resolutions[Level].SizeX;
                vScrollBar.Maximum = im.Resolutions[Level].SizeY;
                hScrollBar.Visible = true;
                vScrollBar.Visible = true;
            }
            else
            {
                hScrollBar.Visible = false;
                vScrollBar.Visible = false;
                pictureBox.Width += 18;
                pictureBox.Height += 18;
                overlayPictureBox.Width += 18;
                overlayPictureBox.Height += 18;
                Tools.selectBoxSize = ROI.selectBoxSize;
            }
            InitGUI();
            UpdateImages();
            GoToImage(Images.Count - 1);
        }
References BioImager.ImageView.GoToImage(), BioImager.ImageView.InitGUI(), BioImager.ImageView.Level, BioImager.ImageView.SelectedIndex, and BioImager.ImageView.UpdateImages().
Referenced by BioImager.ImageView.ImageView().
CopySelection()
void BioImager.ImageView.CopySelection ()
It takes the selected ROIs and copies them to the clipboard.
Definition at line 2728 of file ImageView.cs.
        {
            copys.Clear();
            string s = "";
            foreach (ROI item in AnnotationsRGB)
            {
                if (item.selected)
                {
                    copys.Add(item);
                    s += BioImage.ROIToString(item);
                }
            }
            Clipboard.SetText(s);
        }
References BioImager.BioImage.ROIToString().
Referenced by BioImager.ImageView.ImageView_KeyDown().
Dispose() [1/2]
new void BioImager.ImageView.Dispose ()
Definition at line 3392 of file ImageView.cs.
        {
            for (int i = 0; i < Bitmaps.Count; i++)
            {
                if (Bitmaps[i] != null)
                    Bitmaps[i].Dispose();
            }
            for (int i = 0; i < dBitmaps.Count; i++)
            {
                if (dBitmaps[i] != null)
                    dBitmaps[i].Dispose();
            }
        }
Dispose() [2/2]
override void BioImager.ImageView.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file ImageView.designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
DrawView()
void BioImager.ImageView.DrawView (System.Drawing.Graphics g)
Draws the viewport when Hardware Acceleration is off.
Parameters
g
Definition at line 2216 of file ImageView.cs.
        {
            if (HardwareAcceleration)
            {
                RenderFrame();
                return;
            }
            drawing = true;
            if (Bitmaps.Count == 0 || Bitmaps.Count != Images.Count)
                UpdateImages();
            g.TranslateTransform(ViewWidth / 2, ViewHeight / 2);
            if (Scale.Width == 0 || float.IsInfinity(Scale.Width))
                Scale = new SizeF(1, 1);
            g.ScaleTransform(Scale.Width, Scale.Height);
            if (Bitmaps.Count == 0)
                return;
            System.Drawing.RectangleF[] rf = new System.Drawing.RectangleF[1];
            System.Drawing.Pen blue = new System.Drawing.Pen(Brushes.Blue, 1 / Scale.Width);
            int i = 0;
            foreach (BioImage im in Images)
            {
                if (!IsLayerEnabled(im.PhysicalSizeX) && !im.isPyramidal)
                    continue;
                if (Bitmaps[i] == null)
                    UpdateImages();
                System.Drawing.RectangleF r = ToScreenRectF(im.Volume.Location.X, im.Volume.Location.Y, im.Volume.Width, im.Volume.Height);
                double w = ToViewW(ViewWidth);
                double h = ToViewH(ViewHeight);
                RectangleF rg = new RectangleF((float)((-Origin.X) - (w / 2)), (float)((-Origin.Y) - (h / 2)), (float)(w), (float)(h));
                RectangleF rec = new RectangleF((float)im.Volume.Location.X, (float)im.Volume.Location.Y, (float)im.Volume.Width, (float)im.Volume.Height);
                if (SelectedImage.isPyramidal)
                {
                    var tr = g.Transform;
                    g.ResetTransform();
                    g.DrawImage(ToSysBitmap(Bitmaps[i]), 0, 0);
                    g.Transform = tr;
                }
                else
                if (rg.IntersectsWith(rec))
                {
                    g.DrawImage(ToSysBitmap(Bitmaps[i]), r.X, r.Y, r.Width, r.Height);
                }
                if (i == SelectedIndex && !SelectedImage.isPyramidal)
                {
                    rf[0] = r;
                    g.DrawRectangles(blue, rf);
                }
                i++;
            }
            if (ShowOverview)
            {
                g.ResetTransform();
                g.DrawImage(ToSysBitmap(overviewBitmap), new System.Drawing.Point(0, 0));
                g.DrawRectangle(Pens.Gray, overview.X, overview.Y, overview.Width, overview.Height);
                if (!openSlide)
                {
                    double dsx = _slideBase.Schema.Resolutions[Level].UnitsPerPixel / Resolution;
                    Resolution rs = SelectedImage.Resolutions[Level];
                    double dx = ((double)PyramidalOrigin.X / (rs.SizeX * dsx)) * overview.Width;
                    double dy = ((double)PyramidalOrigin.Y / (rs.SizeY * dsx)) * overview.Height;
                    double dw = ((double)ViewWidth / (rs.SizeX * dsx)) * overview.Width;
                    double dh = ((double)ViewHeight / (rs.SizeY * dsx)) * overview.Height;
                    g.DrawRectangle(Pens.Red, (int)dx, (int)dy, (int)dw, (int)dh);
                }
                else
                {
                    double dsx = _openSlideBase.Schema.Resolutions[Level].UnitsPerPixel / Resolution;
                    Resolution rs = SelectedImage.Resolutions[Level];
                    double dx = ((double)PyramidalOrigin.X / (rs.SizeX * dsx)) * overview.Width;
                    double dy = ((double)PyramidalOrigin.Y / (rs.SizeY * dsx)) * overview.Height;
                    double dw = ((double)ViewWidth / (rs.SizeX * dsx)) * overview.Width;
                    double dh = ((double)ViewHeight / (rs.SizeY * dsx)) * overview.Height;
                    g.DrawRectangle(Pens.Red, (int)dx, (int)dy, (int)dw, (int)dh);
                }
            }
            if (ShowStage)
            {
                RectangleD d = Microscope.GetViewRectangle(false);
                System.Drawing.RectangleF[] rfs = new System.Drawing.RectangleF[1] { new System.Drawing.RectangleF((float)d.X, (float)d.Y, (float)d.W, (float)d.H) };
                rfs[0] = ToScreenRectF(rfs[0].X, rfs[0].Y, rfs[0].Width, rfs[0].Height);
                System.Drawing.Pen red = new System.Drawing.Pen(Brushes.Red, 1 / Scale.Width);
                g.DrawRectangles(red, rfs);
            }
            blue.Dispose();
            update = false;
            drawing = false;
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.Level, BioImager.ImageView.Origin, BioImager.ImageView.PyramidalOrigin, BioImager.ImageView.RenderFrame(), BioImager.ImageView.Resolution, BioImager.ImageView.Scale, BioImager.ImageView.SelectedIndex, BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToViewH(), BioImager.ImageView.ToViewW(), and BioImager.ImageView.UpdateImages().
GetCoordinate()
ZCT BioImager.ImageView.GetCoordinate ()
It returns the coordinate of the selected image
Returns
The Coordinate property of the SelectedImage object.
Definition at line 276 of file ImageView.cs.
        {
            return SelectedImage.Coordinate;
        }
Referenced by BioImager.ImageView.PasteSelection(), BioImager.SlideImage.ReadRegion(), BioImager.Tools.ToolDown(), BioImager.Tools.ToolUp(), and BioImager.SlideImage.TryReadRegion().
GetRange()
void BioImager.ImageView.GetRange ()
It creates a new RangeTool object, which is a form that allows the user to set the range of the data to be displayed.
The RangeTool object is created with the following parameters:
timeEnabled: a boolean that indicates whether the data has a time component.
Mode: a ViewMode enum that indicates whether the data is filtered or not.
zBar.Minimum: the minimum value of the zBar.
zBar.Maximum: the maximum value of the zBar.
tBar.Minimum: the minimum value of the tBar.
tBar.Maximum: the maximum value of the tBar.
cBar.Minimum: the minimum value of the cBar.
cBar.Maximum: the maximum value of the cBar.
The RangeTool object is then shown to the user.
If the user clicks the
Returns
A RangeTool object.
Definition at line 1672 of file ImageView.cs.
        {
            RangeTool t;
            if (Mode == ViewMode.Filtered)
                t = new RangeTool(timeEnabled, true, zBar.Minimum, zBar.Maximum, tBar.Minimum, tBar.Maximum, cBar.Minimum, cBar.Maximum);
            else
                t = new RangeTool(timeEnabled, false, zBar.Minimum, zBar.Maximum, tBar.Minimum, tBar.Maximum, cBar.Minimum, cBar.Maximum);
            if (t.ShowDialog() != DialogResult.OK)
                return;
            zBar.Minimum = t.ZMin;
            zBar.Maximum = t.ZMax;
            tBar.Minimum = t.TimeMin;
            tBar.Maximum = t.TimeMax;
            cBar.Minimum = t.CMin;
            cBar.Maximum = t.CMax;
        }
References BioImager.ImageView.Mode.
GetScale()
double BioImager.ImageView.GetScale ()
GetScale() returns the scale of the image in the viewport.
Returns
The scale of the image.
Definition at line 2317 of file ImageView.cs.
        {
            return ToViewSizeW(ROI.selectBoxSize / Scale.Width);
        }
References BioImager.ImageView.Scale.
Referenced by BioImager.Tools.ToolUp().
GoToImage() [1/2]
void BioImager.ImageView.GoToImage ()
If the selected image is not null, set the origin to the center of the image, and set the scale to the height of the image.
Returns
The method is returning the value of the variable "Scale"
Definition at line 3261 of file ImageView.cs.
        {
            GoToImage(0);
        }
References BioImager.ImageView.GoToImage().
Referenced by BioImager.ImageView.AddImage(), BioImager.ImageView.GoToImage(), BioImager.ImageView.ImageView(), and BioImager.TabsView.ResizeView().
GoToImage() [2/2]
void BioImager.ImageView.GoToImage (int i)
It takes an image index and centers the image in the viewport
Parameters
i the index of the image to go to
Returns
The method is returning the value of the variable "i"
Definition at line 3289 of file ImageView.cs.
        {
            if (Images.Count <= i)
                return;
            if (SelectedImage.Type == BioImage.ImageType.pyramidal)
            {
                if (SelectedImage.openSlideBase != null)
                {
                    if (MacroResolution.HasValue)
                    {
                        int lev = MacroResolution.Value - 2;
                        Resolution = _openSlideBase.Schema.Resolutions[lev].UnitsPerPixel*0.98;
                    }
                    else
                    {
                        Resolution = _openSlideBase.Schema.Resolutions[0].UnitsPerPixel;
                    }
                }
                else
                {
                    if (MacroResolution.HasValue)
                    {
                        int lev = MacroResolution.Value-1;
                        Resolution = SelectedImage.slideBase.Schema.Resolutions[lev].UnitsPerPixel*0.98;
                        PyramidalOrigin = new PointD(0, 0);
                    }
                    else
                    {
                        Resolution = SelectedImage.GetUnitPerPixel(SelectedImage.Resolutions.Count - 1)*0.98;
                    }
                }
            }
            double dx = Images[i].Volume.Width / 2;
            double dy = Images[i].Volume.Height / 2;
            Origin = new PointD(-(Images[i].Volume.Location.X + dx), -(Images[i].Volume.Location.Y + dy));
            double wx, wy;
            if (HardwareAcceleration)
            {
                wx = ViewWidth / ToScreenW(SelectedImage.Volume.Width);
                wy = ViewHeight / ToScreenH(SelectedImage.Volume.Height);
            }
            else
            {
                wx = ViewWidth / ToScreenScaleW(SelectedImage.Volume.Width);
                wy = ViewHeight / ToScreenScaleH(SelectedImage.Volume.Height);
            }
            Scale = new SizeF((float)wy, (float)wy);
            UpdateView();
        }
References BioImager.BioImage.GetUnitPerPixel(), BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.Origin, BioImager.ImageView.PyramidalOrigin, BioImager.ImageView.Scale, BioImager.ImageView.ToScreenH(), BioImager.ImageView.ToScreenScaleH(), BioImager.ImageView.ToScreenScaleW(), BioImager.ImageView.ToScreenW(), and BioImager.ImageView.UpdateView().
GoToStage()
void BioImager.ImageView.GoToStage ()
Definition at line 3514 of file ImageView.cs.
        {
            RectangleD d = Microscope.GetViewRectangle(false);
            double dx = d.W / 2;
            double dy = d.H / 2;
            Origin = new PointD(-(d.X + dx), -(d.Y + dy));
            double wx, wy;
            if (HardwareAcceleration)
            {
                wx = Math.Abs(ViewWidth / ToScreenW(d.W));
                wy = Math.Abs(ViewHeight / ToScreenH(d.H));
            }
            else
            {
                wx = Math.Abs(ViewWidth / ToScreenScaleW(d.W));
                wy = Math.Abs(ViewHeight / ToScreenScaleH(d.H));
            }
            scale.Width = (float)wy;
            scale.Height = (float)wy;
            update = true;
            UpdateView();
        }
ImageToViewSpace()
PointD BioImager.ImageView.ImageToViewSpace (double x, double y)
It takes a point in the image space and returns the point in the view space
Parameters
x the x coordinate of the point in the image
y the y coordinate of the point in the image
Returns
The point in the image space that corresponds to the point in the view space.
Definition at line 2842 of file ImageView.cs.
        {
            if(SelectedImage==null)
                return ToViewSpace(x, y);
            if (SelectedImage.isPyramidal)
            {
                return new PointD((PyramidalOrigin.X + x) * Resolution, (PyramidalOrigin.Y + y) * Resolution);
            }
            else
                return ToViewSpace(x, y);
        }
References BioImager.ImageView.PyramidalOrigin, and BioImager.ImageView.ToViewSpace().
ImageView_KeyDown()
void BioImager.ImageView.ImageView_KeyDown (object sender, KeyEventArgs e)
If the user presses the "C" key while holding down the "Control" key, then the function "CopySelection" is called
Parameters
sender The object that raised the event.
KeyEventArgs The event arguments for the key press.
Returns
The return value is a PointD object.
Definition at line 3202 of file ImageView.cs.
        {
            double moveAmount = 5 * Scale.Width;
            Plugins.KeyDownEvent(sender,e);
            if (e.KeyCode == Keys.C && e.Control)
            {
                CopySelection();
                return;
            }
            if (e.KeyCode == Keys.V && e.Control)
            {
                PasteSelection();
                return;
            }
            if (e.KeyCode == Keys.Subtract || e.KeyCode == Keys.NumPad7)
            {
                Scale = new SizeF(Scale.Width - 0.1f, Scale.Height - 0.1f);
                UpdateOverlay();
            }
            if (e.KeyCode == Keys.Add || e.KeyCode == Keys.NumPad9)
            {
                Scale = new SizeF(Scale.Width + 0.1f, Scale.Height + 0.1f);
                UpdateOverlay();
            }
            if (e.KeyCode == Keys.W || e.KeyCode == Keys.NumPad8)
            {
                Origin = new PointD(Origin.X, Origin.Y + moveAmount);
                UpdateView();
            }
            if (e.KeyCode == Keys.S || e.KeyCode == Keys.NumPad2)
            {
                Origin = new PointD(Origin.X, Origin.Y - moveAmount);
                UpdateView();
            }
            if (e.KeyCode == Keys.A || e.KeyCode == Keys.NumPad4)
            {
                Origin = new PointD(Origin.X + moveAmount, Origin.Y);
                UpdateView();
            }
            if (e.KeyCode == Keys.D || e.KeyCode == Keys.NumPad6)
            {
                Origin = new PointD(Origin.X - moveAmount, Origin.Y);
                UpdateView();
            }
        }
References BioImager.ImageView.CopySelection(), BioImager.ImageView.Origin, BioImager.ImageView.PasteSelection(), BioImager.ImageView.Scale, BioImager.ImageView.UpdateOverlay(), and BioImager.ImageView.UpdateView().
InitGUI()
void BioImager.ImageView.InitGUI ()
It initializes the GUI
Returns
The image is being returned.
Definition at line 908 of file ImageView.cs.
        {
            if (SelectedImage == null)
                return;
            zBar.Maximum = SelectedImage.SizeZ - 1;
            if (SelectedImage.Buffers[0].RGBChannelsCount == 3)
                cBar.Maximum = 0;
            else
                cBar.Maximum = SelectedImage.SizeC - 1;
            if (SelectedImage.SizeT > 1)
            {
                tBar.Maximum = SelectedImage.SizeT - 1;
                timeEnabled = true;
            }
            else
            {
                tBar.Enabled = false;
                timeEnabled = false;
                tBar.Maximum = SelectedImage.SizeT - 1;
            }
            //rgbPictureBox.Image = image.plane.GetBitmap();
            //we clear the channel comboboxes incase we have channels from previous loaded image.
            channelBoxR.Items.Clear();
            channelBoxG.Items.Clear();
            channelBoxB.Items.Clear();
            foreach (Channel ch in SelectedImage.Channels)
            {
                channelBoxR.Items.Add(ch);
                channelBoxG.Items.Add(ch);
                channelBoxB.Items.Add(ch);
            }
            if (SelectedImage.Channels.Count > 2)
            {
                channelBoxR.SelectedIndex = 0;
                channelBoxG.SelectedIndex = 1;
                channelBoxB.SelectedIndex = 2;
            }
            else
            if (SelectedImage.Channels.Count == 2)
            {
                channelBoxR.SelectedIndex = 0;
                channelBoxG.SelectedIndex = 1;
            }
            UpdateRGBChannels();
            init = true;
        }
References BioImager.ImageView.UpdateRGBChannels().
Referenced by BioImager.ImageView.AddImage(), BioImager.ImageView.ImageView(), and BioImager.ImageView.UpdateImages().
MoveStageToImage() [1/2]
void BioImager.ImageView.MoveStageToImage ()
Move the stage to the location of the selected image
Returns
The method is returning the value of the SelectedImage property.
Definition at line 3539 of file ImageView.cs.
        {
            if (SelectedImage == null)
                return;
            Microscope.Stage.SetPosition(SelectedImage.Volume.Location.X, SelectedImage.Volume.Location.Y);
            update = true;
            UpdateView();
        }
References BioImager.ImageView.UpdateView().
MoveStageToImage() [2/2]
void BioImager.ImageView.MoveStageToImage (int i)
Move the stage to the location of the image at index i
Parameters
i the index of the image in the list of images
Definition at line 3550 of file ImageView.cs.
        {
            update = true;
            Microscope.Stage.SetPosition(Images[i].Volume.Location.X, Images[i].Volume.Location.Y);
            UpdateView();
        }
References BioImager.ImageView.UpdateView().
PasteSelection()
void BioImager.ImageView.PasteSelection ()
We get the text from the clipboard, split it into lines, and then for each line, if it's longer than 8 characters, we convert it to an ROI and add it to the image
Definition at line 2744 of file ImageView.cs.
        {
            string[] sts = Clipboard.GetText().Split(BioImage.NewLine);
            foreach (string line in sts)
            {
                if (line.Length > 8)
                {
                    ROI an = BioImage.StringToROI(line);
                    //We set the coordinates of the ROI's we are pasting
                    an.coord = GetCoordinate();
                    SelectedImage.Annotations.Add(an);
                }
            }
            UpdateOverlay();
        }
References BioImager.ImageView.GetCoordinate(), BioImager.BioImage.StringToROI(), and BioImager.ImageView.UpdateOverlay().
Referenced by BioImager.ImageView.ImageView_KeyDown().
RemoveImage()
void BioImager.ImageView.RemoveImage (int i)
Definition at line 1376 of file ImageView.cs.
        {
            do
            {
                System.Threading.Thread.Sleep(50);
                Application.DoEvents();
            } while (drawing || updating);
            Images[i].Dispose();
            Images.RemoveAt(i);
            UpdateImages();
        }
RemoveImages()
void BioImager.ImageView.RemoveImages ()
Definition at line 1387 of file ImageView.cs.
        {
            do
            {
                Thread.Sleep(50);
                Application.DoEvents();
            } while (drawing || updating);
            for (int i = 0; i < Images.Count; i++)
            {
                Images[i].Dispose();
            }
            Images.Clear();
            UpdateImages();
        }
RenderFrame()
void BioImager.ImageView.RenderFrame ()
It draws the images and annotations to the screen
Returns
A Bitmap
Definition at line 1037 of file ImageView.cs.
        {
            drawing = true;
            if (HardwareAcceleration && dx != null)
            {
                Plugins.Render(this, dx);
                dx.BeginDraw();
                dx.RenderTarget2D.Clear(new RawColor4(1.0f, 1.0f, 1.0f, 1.0f));
                System.Drawing.RectangleF rg = ToScreenRectF(PointD.MinX, PointD.MinY, PointD.MaxX - PointD.MinX, PointD.MaxY - PointD.MinY);
                //dx.RenderTarget2D.Transform = SharpDX.Matrix3x2.Rotation((float)Math.PI);
                SharpDX.Direct2D1.SolidColorBrush pen = new SharpDX.Direct2D1.SolidColorBrush(dx.RenderTarget2D, new RawColor4(1.0f, 0.0f, 0.0f, 1.0f));
                SharpDX.Direct2D1.SolidColorBrush red = new SharpDX.Direct2D1.SolidColorBrush(dx.RenderTarget2D, new RawColor4(1.0f, 0.0f, 0.0f, 1.0f));
                SharpDX.Direct2D1.SolidColorBrush green = new SharpDX.Direct2D1.SolidColorBrush(dx.RenderTarget2D, new RawColor4(0.0f, 1.0f, 0.0f, 1.0f));
                SharpDX.Direct2D1.SolidColorBrush mag = new SharpDX.Direct2D1.SolidColorBrush(dx.RenderTarget2D, new RawColor4(1.0f, 0.0f, 1.0f, 1.0f));
                SharpDX.Direct2D1.SolidColorBrush blue = new SharpDX.Direct2D1.SolidColorBrush(dx.RenderTarget2D, new RawColor4(0.0f, 0.0f, 1.0f, 1.0f));
                SharpDX.Direct2D1.SolidColorBrush b = new SharpDX.Direct2D1.SolidColorBrush(dx.RenderTarget2D, new RawColor4(1.0f, 1.0f, 0.0f, 1.0f));
                SharpDX.Direct2D1.SolidColorBrush gray = new SharpDX.Direct2D1.SolidColorBrush(dx.RenderTarget2D, new RawColor4(0.5f, 0.5f, 0.5f, 1.0f));
                dx.RenderTarget2D.FillRectangle(ToRawRectF(rg.X, rg.Y, rg.Width, rg.Height), gray);
                for (int x = 0; x < Images.Count; x++)
                {
                    if (!IsLayerEnabled(Images[x].PhysicalSizeX) && !Images[x].isPyramidal)
                        continue;
                    if (dBitmaps == null)
                        UpdateImages();
                    if (dBitmaps.Count != Images.Count)
                        UpdateImages();
                    if (dBitmaps[x] == null)
                        UpdateImages();
                    System.Drawing.RectangleF r = ToScreenRectF(Images[x].Volume.Location.X, Images[x].Volume.Location.Y, Images[x].Volume.Width, Images[x].Volume.Height);
                    double w = ToViewW(ViewWidth);
                    double h = ToViewH(ViewHeight);
                    RectangleF rge = new RectangleF((float)((-Origin.X) - (w / 2)), (float)((-Origin.Y) - (h / 2)), (float)(Math.Abs(w)), (float)(Math.Abs(h)));
                    RectangleF rec = new RectangleF((float)Images[x].Volume.Location.X, (float)Images[x].Volume.Location.Y, (float)Images[x].Volume.Width, (float)Images[x].Volume.Height);
                    //if (rge.IntersectsWith(rec))
                    dx.RenderTarget2D.DrawBitmap(dBitmaps[x], ToRawRectF(r.X, r.Y, r.Width, r.Height), 1.0f, SharpDX.Direct2D1.BitmapInterpolationMode.Linear);
                    if (x == selectedIndex)
                        dx.RenderTarget2D.DrawRectangle(ToRawRectF(r.X, r.Y, r.Width, r.Height), blue);
                }
                bool bounds = showBounds;
                bool labels = showText;
                foreach (BioImage bi in Images)
                {
                    if (!IsLayerEnabled(bi.PhysicalSizeX) && !bi.isPyramidal)
                        continue;
                    foreach (ROI an in bi.Annotations)
                    {
                        if (zBar.Value != an.coord.Z || cBar.Value != an.coord.C || tBar.Value != an.coord.T)
                            continue;
                        float w = Math.Abs(Scale.Width);
                        Font fo = new Font(new FontFamily(an.family), (float)((an.strokeWidth / w) * an.fontSize));
                        PointF pc = new PointF((float)(an.BoundingBox.X + (an.BoundingBox.W / 2)), (float)(an.BoundingBox.Y + (an.BoundingBox.H / 2)));
                        float width = 1;
                        dx.RenderTarget2D.StrokeWidth = width;
                        if (an.type == ROI.Type.Point)
{
                            System.Drawing.PointF pf = ToScreenSpace(new PointF((float)an.Point.X + 1, (float)an.Point.Y + 1));
                            dx.RenderTarget2D.DrawLine(new RawVector2((float)an.Point.X, (float)an.Point.Y), new RawVector2(pf.X, pf.Y), b);
                            System.Drawing.RectangleF[] rfs = ToScreenSpace(an.GetSelectBoxes(Tools.selectBoxSize));
                            for (int i = 0; i < rfs.Length; i++)
{
                                dx.RenderTarget2D.DrawRectangle(ToRawRectF(rfs[i].X, rfs[i].Y, rfs[i].Width, rfs[i].Height), red);
                            }
                        }
                        else
                        if (an.type == ROI.Type.Line)
{
                            PointD pf = ToScreenSpace(an.GetPoint(0));
                            PointD pf2 = ToScreenSpace(an.GetPoint(1));
                            dx.RenderTarget2D.DrawLine(new RawVector2((float)pf.X, (float)pf.Y), new RawVector2((float)pf2.X, (float)pf2.Y), b);
                            System.Drawing.RectangleF[] rfs = ToScreenSpace(an.GetSelectBoxes(Tools.selectBoxSize));
                            for (int i = 0; i < rfs.Length; i++)
{
                                dx.RenderTarget2D.DrawRectangle(ToRawRectF(rfs[i].X, rfs[i].Y, rfs[i].Width, rfs[i].Height), red);
                            }
                        }
                        else
                        if (an.type == ROI.Type.Rectangle && an.Rect.W > 0 && an.Rect.H > 0)
{
                            System.Drawing.RectangleF rec = ToScreenSpace(an.Rect);
                            dx.RenderTarget2D.DrawRectangle(ToRawRectF(rec.X, rec.Y, rec.Width, rec.Height), red);
                            System.Drawing.RectangleF[] rfs = ToScreenSpace(an.GetSelectBoxes(Tools.selectBoxSize));
                            for (int i = 0; i < rfs.Length; i++)
{
                                dx.RenderTarget2D.DrawRectangle(ToRawRectF(rfs[i].X, rfs[i].Y, rfs[i].Width, rfs[i].Height), red);
                            }
                        }
                        else
                        if (an.type == ROI.Type.Ellipse)
{
                            System.Drawing.RectangleF r = ToScreenSpace(an.BoundingBox);
                            System.Drawing.RectangleF[] rfs = ToScreenSpace(an.GetSelectBoxes(Tools.selectBoxSize));
                            RawRectangleF rf = ToRawRectF(rfs[0].X, rfs[0].Y, rfs[0].Width, rfs[0].Height);
                            SharpDX.Direct2D1.Ellipse e = new SharpDX.Direct2D1.Ellipse(new RawVector2(rf.Left + (Math.Abs(r.Width) / 2) - (rfs[0].Width / 2), rf.Top + (Math.Abs(r.Height) / 2) - (rfs[0].Height / 2)), -r.Width / 2, -r.Height / 2);
                            dx.RenderTarget2D.DrawEllipse(e, b);
                            for (int i = 0; i < rfs.Length; i++)
{
                                dx.RenderTarget2D.DrawRectangle(ToRawRectF(rfs[i].X, rfs[i].Y, rfs[i].Width, rfs[i].Height), red);
                            }
                        }
                        else
                        if (an.type == ROI.Type.Polygon && an.closed)
{
                            RawVector2 pf;
                            RawVector2 pf2;
                            for (int i = 0; i < an.PointsD.Count - 1; i++)
{
                                pf = new RawVector2((float)ToScreenSpace(an.GetPoint(i).X, an.GetPoint(i).Y).X, (float)ToScreenSpace(an.GetPoint(i).X, an.GetPoint(i).Y).Y);
                                pf2 = new RawVector2((float)ToScreenSpace(an.GetPoint(i + 1).X, an.GetPoint(i + 1).Y).X, (float)ToScreenSpace(an.GetPoint(i + 1).X, an.GetPoint(i + 1).Y).Y);
                                dx.RenderTarget2D.DrawLine(pf, pf2, b);
                            }
                            pf = new RawVector2((float)ToScreenSpace(an.GetPoint(0)).X, (float)ToScreenSpace(an.GetPoint(0)).Y);
                            pf2 = new RawVector2((float)ToScreenSpace(an.GetPoint(an.PointsD.Count - 1)).X, (float)ToScreenSpace(an.GetPoint(an.PointsD.Count - 1)).Y);
                            dx.RenderTarget2D.DrawLine(pf, pf2, b);
                            System.Drawing.RectangleF[] rfs = ToScreenSpace(an.GetSelectBoxes(Tools.selectBoxSize));
                            for (int i = 0; i < rfs.Length; i++)
{
                                dx.RenderTarget2D.DrawRectangle(ToRawRectF(rfs[i].X, rfs[i].Y, rfs[i].Width, rfs[i].Height), red);
                            }
                        }
                        else
                        if (an.type == ROI.Type.Polygon && !an.closed || an.type == ROI.Type.Polyline)
{
                            RawVector2 pf;
                            RawVector2 pf2;
                            for (int i = 0; i < an.PointsD.Count - 1; i++)
{
                                pf = new RawVector2((float)ToScreenSpace(an.GetPoint(i).X, an.GetPoint(i).Y).X, (float)ToScreenSpace(an.GetPoint(i).X, an.GetPoint(i).Y).Y);
                                pf2 = new RawVector2((float)ToScreenSpace(an.GetPoint(i + 1).X, an.GetPoint(i + 1).Y).X, (float)ToScreenSpace(an.GetPoint(i + 1).X, an.GetPoint(i + 1).Y).Y);
                                dx.RenderTarget2D.DrawLine(pf, pf2, b);
                                dx.RenderTarget2D.DrawLine(pf, pf2, b);
                            }
                            System.Drawing.RectangleF[] rfs = ToScreenSpace(an.GetSelectBoxes(Tools.selectBoxSize));
                            for (int i = 0; i < rfs.Length; i++)
{
                                dx.RenderTarget2D.DrawRectangle(ToRawRectF(rfs[i].X, rfs[i].Y, rfs[i].Width, rfs[i].Height), red);
                            }
                        }
                        else
                        if (an.type == ROI.Type.Freeform && an.closed)
{
                            RawVector2 pf;
                            RawVector2 pf2;
                            for (int i = 0; i < an.PointsD.Count - 1; i++)
{
                                pf = new RawVector2((float)ToScreenSpace(an.GetPoint(i).X, an.GetPoint(i).Y).X, (float)ToScreenSpace(an.GetPoint(i).X, an.GetPoint(i).Y).Y);
                                pf2 = new RawVector2((float)ToScreenSpace(an.GetPoint(i + 1).X, an.GetPoint(i + 1).Y).X, (float)ToScreenSpace(an.GetPoint(i + 1).X, an.GetPoint(i + 1).Y).Y);
                                dx.RenderTarget2D.DrawLine(pf, pf2, b);
                                dx.RenderTarget2D.DrawLine(pf, pf2, b);
                            }
                            pf = new RawVector2((float)ToScreenSpace(an.GetPoint(0)).X, (float)ToScreenSpace(an.GetPoint(0)).Y);
                            pf2 = new RawVector2((float)ToScreenSpace(an.GetPoint(an.PointsD.Count - 1)).X, (float)ToScreenSpace(an.GetPoint(an.PointsD.Count - 1)).Y);
                            dx.RenderTarget2D.DrawLine(pf, pf2, b);
                        }
                        if (an.type == ROI.Type.Label)
{
                            System.Drawing.RectangleF rec = ToScreenSpace(an.Rect);
                            RawRectangleF r = ToRawRectF(rec.X, rec.Y, rec.Width, rec.Height);
                            SharpDX.DirectWrite.TextFormat tex = new SharpDX.DirectWrite.TextFormat(dx.FactoryDWrite, an.family.ToString(), an.fontSize);
                            dx.RenderTarget2D.DrawText(an.Text, tex, r, b);
                            tex.Dispose();
                            System.Drawing.RectangleF[] rfs = ToScreenSpace(an.GetSelectBoxes(Tools.selectBoxSize));
                            for (int i = 0; i < rfs.Length; i++)
{
                                dx.RenderTarget2D.DrawRectangle(ToRawRectF(rfs[i].X, rfs[i].Y, rfs[i].Width, rfs[i].Height), red);
                            }
                        }
                        if (labels)
{
                            if (an.Text != null)
{
                                System.Drawing.Size s = TextRenderer.MeasureText(an.Text, new Font(an.family, an.fontSize));
                                //Lets draw the text of this ROI in the middle of the ROI.
                                float fw = ((float)an.Rect.X + ((float)an.Rect.W / 2)) - ((float)s.Width / 2);
                                float fh = ((float)an.Rect.Y + ((float)an.Rect.H / 2)) - ((float)s.Height / 2);
                                RawRectangleF r = ToRawRectF(fw, fh, s.Width, s.Height);
                                SharpDX.DirectWrite.TextFormat tex = new SharpDX.DirectWrite.TextFormat(dx.FactoryDWrite, an.family.ToString(), an.fontSize);
                                dx.RenderTarget2D.DrawText(an.Text, tex, r, b);
                                tex.Dispose();
                            }
                        }
                        if (bounds)
{
                            System.Drawing.RectangleF r = ToScreenSpace(an.Rect);
                            dx.RenderTarget2D.DrawRectangle(ToRawRectF(r.X, r.Y, r.Width, r.Height), green);
                        }
                        if (an.selected)
{
                            //Lets draw the selected bounding box.
                            System.Drawing.RectangleF r = ToScreenSpace(an.Rect);
                            dx.RenderTarget2D.DrawRectangle(ToRawRectF(r.X, r.Y, r.Width, r.Height), mag);
                            //Lets draw the selectBoxes.
                            List<RectangleD> rects = new List<RectangleD>();
                            RectangleD[] sels = an.GetSelectBoxes(Tools.selectBoxSize);
                            for (int i = 0; i < an.selectedPoints.Count; i++)
{
                                if (an.selectedPoints[i] < an.GetPointCount())
{
                                    rects.Add(sels[an.selectedPoints[i]]);
                                }
                            }
                            if (rects.Count > 0)
{
                                for (int i = 0; i < rects.Count; i++)
{
                                    System.Drawing.RectangleF ri = ToScreenSpace(rects[i]);
                                    dx.RenderTarget2D.DrawRectangle(ToRawRectF(ri.X, ri.Y, ri.Width, ri.Height), blue);
                                }
                            }
                            rects.Clear();
                        }
                    }
                }
                if (ShowStage)
                {
                    AForge.RectangleD re = Microscope.GetViewRectangle(false);
                    System.Drawing.RectangleF vr = ToScreenRectF(re.X, re.Y, re.W, re.H);
                    RawRectangleF rr = ToRawRectF(vr.X, vr.Y, vr.Width, vr.Height);
                    dx.RenderTarget2D.DrawRectangle(rr, red);
                }
                pen.Dispose();
                red.Dispose();
                mag.Dispose();
                green.Dispose();
                blue.Dispose();
                gray.Dispose();
                b.Dispose();
                dx.EndDraw();
            }
            drawing = false;
        }
References BioImager.ROI.GetPoint(), BioImager.ROI.GetPointCount(), BioImager.ROI.GetSelectBoxes(), BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.Origin, BioImager.ImageView.Scale, BioImager.ImageView.ToRawRectF(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenSpace(), BioImager.ImageView.ToViewH(), BioImager.ImageView.ToViewW(), and BioImager.ImageView.UpdateImages().
Referenced by BioImager.ImageView.DrawView(), BioImager.ImageView.UpdateOverlay(), and BioImager.ImageView.UpdateView().
SetCoordinate()
void BioImager.ImageView.SetCoordinate (int z, int c, int t)
‍Sets the coordinate of the image to the specified Z, C, and T values
Parameters
z the z-coordinate of the image
c channel
t time
Returns
The method is returning the value of the zBar.Value, cBar.Value, and tBar.Value.
Definition at line 253 of file ImageView.cs.
        {
            System.Threading.Tasks.Task.Run(() =>
            {
                App.viewer.Invoke((MethodInvoker)delegate
                {
                    if (SelectedImage == null)
                        return;
                    if (z >= SelectedImage.SizeZ)
                        zBar.Value = zBar.Maximum;
                    if (c >= SelectedImage.SizeC)
                        cBar.Value = cBar.Maximum;
                    if (t >= SelectedImage.SizeT)
                        tBar.Value = tBar.Maximum;
                    zBar.Value = z;
                    cBar.Value = c;
                    tBar.Value = t;
                });
            });
        }
Referenced by BioImager.ImageView.ImageView().
ToRawRectF()
RawRectangleF BioImager.ImageView.ToRawRectF (double x, double y, double w, double h)
‍It takes a rectangle in the coordinate system of the stage and returns a rectangle in the
coordinate system of the picturebox
Parameters
x The x coordinate of the upper-left corner of the rectangle.
y The y-coordinate of the upper-left corner of the rectangle.
w width of the rectangle
h height of the rectangle
Returns
A RawRectangleF object.
Definition at line 3102 of file ImageView.cs.
        {
            double xd = dxPanel.Width / 2;
            double yd = dxPanel.Height / 2;
            return new RawRectangleF((float)(xd - x), (float)(yd - y), (float)(xd - (x + w)), (float)(yd - (y + h)));
        }
Referenced by BioImager.ImageView.RenderFrame(), and BioImager.ImageView.ToScreenSpace().
ToScreenH()
float BioImager.ImageView.ToScreenH (double y)
‍Convert a value in microns to a value in pixels
Parameters
y the y coordinate of the point to be converted
Returns
The return value is a float.
Definition at line 3187 of file ImageView.cs.
        {
            if (HardwareAcceleration)
            {
                return (float)(y * PxHmicron);
            }
            return (float)(y * PxHmicron);
        }
References BioImager.ImageView.HardwareAcceleration, and BioImager.ImageView.PxHmicron.
Referenced by BioImager.ImageView.GoToImage().
ToScreenRectF()
System.Drawing.RectangleF BioImager.ImageView.ToScreenRectF (double x, double y, double w, double h)
It converts a rectangle in microns to a rectangle in pixels
Parameters
x The x coordinate of the rectangle
y -0.0015
w width of the image in microns
h height of the rectangle
Returns
A RectangleF object.
Definition at line 3057 of file ImageView.cs.
        {
            if (SelectedImage == null)
            {
                PointD pf;
                if (HardwareAcceleration)
                {
                    double dx = (pxWmicron * (-Origin.X)) * Scale.Width;
                    double dy = (pxHmicron * (-Origin.Y)) * Scale.Height;
                    System.Drawing.RectangleF rf = new System.Drawing.RectangleF((float)(PxWmicron * -x * Scale.Width + dx), (float)(PxHmicron * -y * Scale.Height + dy), (float)(PxWmicron * -w * Scale.Width), (float)(PxHmicron * -h * Scale.Height));
                    return rf;
                }
                pf = ToScreenSpace(x, y);
                return new System.Drawing.RectangleF((float)pf.X, (float)pf.Y, ToScreenScaleW(w), ToScreenScaleH(h));
            }
            if (SelectedImage.isPyramidal)
            {
                PointD d = ToViewSpace(x, y);
                double dw = ToViewSizeW(w);
                double dh = ToViewSizeH(h);
                return new System.Drawing.RectangleF((float)(d.X - PyramidalOrigin.X), (float)(d.Y - PyramidalOrigin.Y), (float)dw, (float)dh);
            }
            else
            {
                PointD pf;
                if (HardwareAcceleration)
                {
                    double dx = (pxWmicron * (-Origin.X)) * Scale.Width;
                    double dy = (pxHmicron * (-Origin.Y)) * Scale.Height;
                    System.Drawing.RectangleF rf = new System.Drawing.RectangleF((float)(PxWmicron * -x * Scale.Width + dx), (float)(PxHmicron * -y * Scale.Height + dy), (float)(PxWmicron * -w * Scale.Width), (float)(PxHmicron * -h * Scale.Height));
                    return rf;
                }
                pf = ToScreenSpace(x, y);
                return new System.Drawing.RectangleF((float)pf.X, (float)pf.Y, ToScreenScaleW(w), ToScreenScaleH(h));
            }
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.Origin, BioImager.ImageView.PxHmicron, BioImager.ImageView.PxWmicron, BioImager.ImageView.PyramidalOrigin, BioImager.ImageView.Scale, BioImager.ImageView.ToScreenScaleH(), BioImager.ImageView.ToScreenScaleW(), BioImager.ImageView.ToScreenSpace(), BioImager.ImageView.ToViewSizeH(), and BioImager.ImageView.ToViewSpace().
Referenced by BioImager.ImageView.DrawView(), BioImager.ImageView.RenderFrame(), and BioImager.ImageView.ToScreenSpace().
ToScreenScale()
PointF BioImager.ImageView.ToScreenScale (PointD p)
‍Convert a point in the world coordinate system to a point in the screen coordinate system
Parameters
PointD
Returns
A PointF object.
Definition at line 3043 of file ImageView.cs.
        {
            float x = ToScreenScaleW((float)p.X);
            float y = ToScreenScaleH((float)p.Y);
            return new PointF(x, y);
        }
References BioImager.ImageView.ToScreenScaleH(), and BioImager.ImageView.ToScreenScaleW().
ToScreenScaleH()
float BioImager.ImageView.ToScreenScaleH (double y)
‍Convert a value in microns to a value in pixels
Parameters
y the y coordinate of the point to be converted
Returns
The return value is a float.
Definition at line 3030 of file ImageView.cs.
        {
            if (HardwareAcceleration)
            {
                return (float)(-y * PxHmicron * Scale.Height);
            }
            return (float)(y * PxHmicron);
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.PxHmicron, and BioImager.ImageView.Scale.
Referenced by BioImager.ImageView.GoToImage(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenScale(), and BioImager.ImageView.ToScreenSpace().
ToScreenScaleW()
float BioImager.ImageView.ToScreenScaleW (double x)
ToScreenScaleW() returns the number of pixels that correspond to the given number of microns
Parameters
x the x coordinate of the point to be converted
Returns
The return value is a float.
Definition at line 3017 of file ImageView.cs.
        {
            if (HardwareAcceleration)
            {
                return (float)(-x * PxWmicron * Scale.Width);
            }
            return (float)(x * PxWmicron);
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.PxWmicron, and BioImager.ImageView.Scale.
Referenced by BioImager.ImageView.GoToImage(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenScale(), and BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [1/10]
PointD BioImager.ImageView.ToScreenSpace (double x, double y)
‍It converts a point in world space to a point in screen space
Parameters
x The x coordinate of the point to convert.
y The y coordinate of the point to transform.
Returns
A PointD object.
Definition at line 2956 of file ImageView.cs.
        {
            if (HardwareAcceleration)
            {
                System.Drawing.RectangleF f = ToScreenRectF(x, y, 1, 1);
                RawRectangleF rf = ToRawRectF(f.X, f.Y, f.Width, f.Height);
                return new PointD(rf.Left, rf.Top);
            }
            double fx = ToScreenScaleW(Origin.X + x);
            double fy = ToScreenScaleH(Origin.Y + y);
            return new PointD(fx, fy);
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.Origin, BioImager.ImageView.ToRawRectF(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenScaleH(), and BioImager.ImageView.ToScreenScaleW().
Referenced by BioImager.ImageView.RenderFrame(), BioImager.ImageView.ToScreenRectF(), and BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [2/10]
PointF BioImager.ImageView.ToScreenSpace (Point3D p)
‍It converts a 3D point to a 2D point
Parameters
Point3D
Returns
A PointF object.
Definition at line 3007 of file ImageView.cs.
        {
            PointD pd = ToScreenSpace(p.X, p.Y);
            return new PointF((float)pd.X, (float)pd.Y);
        }
References BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [3/10]
PointD BioImager.ImageView.ToScreenSpace (PointD p)
‍Converts a point from world space to screen space
Parameters
PointD A class that contains an X and Y value.
Returns
A PointD object.
Definition at line 2974 of file ImageView.cs.
        {
            return ToScreenSpace(p.X, p.Y);
        }
References BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [4/10]
PointF[] BioImager.ImageView.ToScreenSpace (PointD[] p)
‍Convert a list of points from world space to screen space
Parameters
p The point to convert
Returns
A PointF[] array of points.
Definition at line 3159 of file ImageView.cs.
        {
            PointF[] rs = new PointF[p.Length];
            for (int i = 0; i < p.Length; i++)
            {
                PointD pd = ToScreenSpace(p[i]);
                rs[i] = new PointF((float)pd.X, (float)pd.Y);
            }
            return rs;
        }
References BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [5/10]
System.Drawing.PointF BioImager.ImageView.ToScreenSpace (PointF p)
Convert a point in the world coordinate system to the screen coordinate system
Parameters
PointF The point you want to convert to screen space.
Returns
A PointD object.
Definition at line 2983 of file ImageView.cs.
        {
            PointD pd = ToScreenSpace(p.X, p.Y);
            return new System.Drawing.PointF((float)pd.X, (float)pd.Y);
        }
References BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [6/10]
System.Drawing.PointF[] BioImager.ImageView.ToScreenSpace (PointF[] p)
‍It takes an array of points and returns an array of points
Parameters
p The point to convert
Returns
A PointF array.
Definition at line 2993 of file ImageView.cs.
        {
            System.Drawing.PointF[] pf = new System.Drawing.PointF[p.Length];
            for (int i = 0; i < p.Length; i++)
            {
                pf[i] = ToScreenSpace(p[i]);
            }
            return pf;
        }
References BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [7/10]
System.Drawing.RectangleF BioImager.ImageView.ToScreenSpace (RectangleD p)
‍It converts a rectangle from world space to screen space
Parameters
RectangleD The rectangle to convert.
Returns
A RectangleF object.
Definition at line 3113 of file ImageView.cs.
        {
            return ToScreenRectF(p.X, p.Y, p.W, p.H);
        }
References BioImager.ImageView.ToScreenRectF().
ToScreenSpace() [8/10]
System.Drawing.RectangleF[] BioImager.ImageView.ToScreenSpace (RectangleD[] p)
It takes an array of RectangleD objects and returns an array of RectangleF objects
Parameters
p The rectangle to convert
Returns
A RectangleF[]
Definition at line 3131 of file ImageView.cs.
        {
            System.Drawing.RectangleF[] rs = new System.Drawing.RectangleF[p.Length];
            for (int i = 0; i < p.Length; i++)
            {
                rs[i] = ToScreenSpace(p[i]);
            }
            return rs;
        }
References BioImager.ImageView.ToScreenSpace().
ToScreenSpace() [9/10]
System.Drawing.RectangleF BioImager.ImageView.ToScreenSpace (RectangleF p)
‍It converts a rectangle from world space to screen space
Parameters
RectangleF The rectangle to convert.
Returns
A RectangleF object.
Definition at line 3122 of file ImageView.cs.
        {
            return ToScreenRectF(p.X, p.Y, p.Width, p.Height);
        }
References BioImager.ImageView.ToScreenRectF().
ToScreenSpace() [10/10]
System.Drawing.RectangleF[] BioImager.ImageView.ToScreenSpace (RectangleF[] p)
It takes an array of RectangleF objects and returns an array of RectangleF objects
Parameters
p The rectangle to convert
Returns
A RectangleF[]
Definition at line 3145 of file ImageView.cs.
        {
            System.Drawing.RectangleF[] rs = new System.Drawing.RectangleF[p.Length];
            for (int i = 0; i < p.Length; i++)
            {
                rs[i] = ToScreenSpace(p[i]);
            }
            return rs;
        }
References BioImager.ImageView.ToScreenSpace().
ToScreenW()
float BioImager.ImageView.ToScreenW (double x)
ToScreenW(x) = x * PxWmicron
Parameters
x the x coordinate of the point to be converted
Returns
The return value is a float.
Definition at line 3174 of file ImageView.cs.
        {
            if (HardwareAcceleration)
            {
                return (float)(x * PxWmicron);
            }
            return (float)(x * PxWmicron);
        }
References BioImager.ImageView.HardwareAcceleration, and BioImager.ImageView.PxWmicron.
Referenced by BioImager.ImageView.GoToImage().
ToViewH()
double BioImager.ImageView.ToViewH (double d)
‍Convert a distance in microns to a distance in pixels
Parameters
d the distance in microns
Returns
The return value is the y-coordinate of the point in the view.
Definition at line 2945 of file ImageView.cs.
        {
            double y = (double)(d / PxHmicron) / scale.Height;
            return y;
        }
References BioImager.ImageView.PxHmicron.
Referenced by BioImager.ImageView.DrawView(), and BioImager.ImageView.RenderFrame().
ToViewSizeH()
double BioImager.ImageView.ToViewSizeH (double d)
‍Convert a value in microns to a value in pixels
Parameters
d the size in microns
Returns
The return value is the size of the object in pixels.
Definition at line 2920 of file ImageView.cs.
        {
            if (SelectedImage != null)
                if (SelectedImage.isPyramidal)
            {
                return d / Resolution;
            }
            double y = (double)(d / PxHmicron);
            return y;
        }
References BioImager.ImageView.PxHmicron, and BioImager.ImageView.Resolution.
Referenced by BioImager.ImageView.ToScreenRectF(), and BioImager.ImageView.ToViewSpace().
ToViewSpace() [1/3]
PointD BioImager.ImageView.ToViewSpace (double x, double y)
‍ToViewSpace(x, y) = (ToViewSizeW(x - (ViewWidth / 2)) / Scale.Width) - Origin.X;
Parameters
x The x coordinate of the point to convert
y The y coordinate of the point to convert.
Returns
A PointD object.
Definition at line 2878 of file ImageView.cs.
        {
            if(SelectedImage!=null)
            if (SelectedImage.isPyramidal)
            {
                double ddx = x / Resolution;
                double ddy = y / Resolution;
                return new PointD(ddx, ddy);
            }
            double dx, dy;
            if (HardwareAcceleration)
            {
                dx = (ToViewSizeW(x - (dxPanel.Width / 2)) / Scale.Width) - Origin.X;
                dy = (ToViewSizeH(y - (dxPanel.Height / 2)) / Scale.Height) - Origin.Y;
            }
            else
            {
                dx = (ToViewSizeW(x - (ViewWidth / 2)) / Scale.Width) - Origin.X;
                dy = (ToViewSizeH(y - (ViewHeight / 2)) / Scale.Height) - Origin.Y;
            }
            return new PointD(dx, dy);
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.Origin, BioImager.ImageView.Resolution, BioImager.ImageView.Scale, and BioImager.ImageView.ToViewSizeH().
ToViewSpace() [2/3]
PointD BioImager.ImageView.ToViewSpace (PointD p)
‍Converts a point from world space to view space
Parameters
PointD A class that contains an X and Y value.
Returns
A PointD object.
Definition at line 2868 of file ImageView.cs.
        {
            return ToViewSpace(p.X, p.Y); ;
        }
References BioImager.ImageView.ToViewSpace().
ToViewSpace() [3/3]
PointF BioImager.ImageView.ToViewSpace (PointF p)
Convert a point from world space to view space
Parameters
PointF The point to convert
Returns
A PointD object.
Definition at line 2858 of file ImageView.cs.
        {
            PointD d = ToViewSpace(p.X, p.Y);
            return new PointF((float)d.X, (float)d.Y);
        }
References BioImager.ImageView.ToViewSpace().
Referenced by BioImager.ImageView.ImageToViewSpace(), BioImager.ImageView.ToScreenRectF(), and BioImager.ImageView.ToViewSpace().
ToViewW()
double BioImager.ImageView.ToViewW (double d)
Convert a distance in microns to a distance in pixels on the screen
Parameters
d the distance in microns
Returns
The width of the image in pixels.
Definition at line 2935 of file ImageView.cs.
        {
            double x = (double)(d / PxWmicron) / scale.Width;
            return x;
        }
References BioImager.ImageView.PxWmicron.
Referenced by BioImager.ImageView.DrawView(), and BioImager.ImageView.RenderFrame().
UpdateImage()
void BioImager.ImageView.UpdateImage ()
It takes a 16-bit image, converts it to 8-bit, and then converts it to a DirectX texture
Returns
A bitmap
Definition at line 1405 of file ImageView.cs.
        {
            UpdateImages();
        }
References BioImager.ImageView.UpdateImages().
Referenced by BioImager.ImageJ.RunOnImage().
UpdateImages()
void BioImager.ImageView.UpdateImages ()
It takes a list of images, and for each image, it gets the image at the current Z, C, T coordinates, and then converts it to a bitmap
Returns
A Bitmap
Definition at line 1295 of file ImageView.cs.
        {
            if (SelectedImage == null)
            {
                if (Images.Count > 0)
                    SelectedIndex = 0;
                else
                    return;
            }
            for (int i = 0; i < Bitmaps.Count; i++)
            {
                Bitmaps[i] = null;
            }
            Bitmaps.Clear();
            if (zBar.Maximum != SelectedImage.SizeZ - 1 || tBar.Maximum != SelectedImage.SizeT - 1)
            {
                InitGUI();
            }
            for (int i = 0; i < Images.Count; i++)
            {
                if (dBitmaps != null)
                {
                    if (dBitmaps.Count > i)
                        if (dBitmaps[i] != null)
{
                            dBitmaps[i].Dispose();
                            dBitmaps[i] = null;
                        }
                }
            }
            dBitmaps = new List<SharpDX.Direct2D1.Bitmap>();
            int bi = 0;
            foreach (BioImage b in Images)
            {
                b.PyramidalOrigin = PyramidalOrigin;
                b.PyramidalSize = new AForge.Size(dxPanel.Width, dxPanel.Height);
                b.UpdateBuffersPyramidal();
                ZCT coords = new ZCT(zBar.Value, cBar.Value, tBar.Value);
                Bitmap bitmap = null;
                int index = b.Coords[zBar.Value, cBar.Value, tBar.Value];
                if (Mode == ViewMode.Filtered)
                {
                    bitmap = b.GetFiltered(coords, b.RChannel.RangeR, b.GChannel.RangeG, b.BChannel.RangeB);
                }
                else if (Mode == ViewMode.RGBImage)
                {
                    bitmap = b.GetRGBBitmap(coords, b.RChannel.RangeR, b.GChannel.RangeG, b.BChannel.RangeB);
                }
                else if (Mode == ViewMode.Raw)
                {
                    bitmap = (Bitmap)b.Buffers[index].ImageRGB;
                }
                else
                {
                    bitmap = b.GetEmission(coords, b.RChannel.RangeR, b.GChannel.RangeG, b.BChannel.RangeB);
                }
                if (bitmap != null)
                    if (bitmap.PixelFormat == PixelFormat.Format16bppGrayScale || bitmap.PixelFormat == PixelFormat.Format48bppRgb)
                        bitmap = AForge.Imaging.Image.Convert16bppTo8bpp((Bitmap)bitmap);
                if (HardwareAcceleration && dx != null)
                {
                    if (dBitmaps[bi] != null)
                    {
                        dBitmaps[bi].Dispose();
                        dBitmaps[bi] = null;
                    }
                    Bitmap bf = new Bitmap("", bitmap, new ZCT(), 0);
                    dBitmaps[bi] = DBitmap.FromImage(dx.RenderTarget2D, (bf));
                }
                else
                    Bitmaps.Add(bitmap);
                bi++;
            }
            update = true;
            UpdateView();
        }
References BioImager.DBitmap.FromImage(), BioImager.BioImage.GetEmission(), BioImager.BioImage.GetFiltered(), BioImager.BioImage.GetRGBBitmap(), BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.InitGUI(), BioImager.ImageView.Mode, BioImager.ImageView.PyramidalOrigin, BioImager.ImageView.SelectedIndex, BioImager.BioImage.UpdateBuffersPyramidal(), and BioImager.ImageView.UpdateView().
Referenced by BioImager.ImageView.AddImage(), BioImager.ImageView.DrawView(), BioImager.ImageView.ImageView(), BioImager.ImageView.RenderFrame(), BioImager.BioImage.To16Bit(), BioImager.BioImage.To24Bit(), BioImager.BioImage.To32Bit(), BioImager.BioImage.To48Bit(), BioImager.BioImage.To8Bit(), BioImager.Tools.ToolUp(), and BioImager.ImageView.UpdateImage().
UpdateOverlay()
void BioImager.ImageView.UpdateOverlay ()
If hardware acceleration is enabled, render the frame. Otherwise, set a flag to update the overlay and invalidate the overlay picture box
Returns
The return value is the value of the last expression evaluated in the method.
Definition at line 967 of file ImageView.cs.
        {
            if (HardwareAcceleration)
            {
                RenderFrame();
                return;
            }
            updateOverlay = true;
            overlayPictureBox.Invalidate();
        }
References BioImager.ImageView.HardwareAcceleration, and BioImager.ImageView.RenderFrame().
Referenced by BioImager.ImageView.ImageView_KeyDown(), and BioImager.ImageView.PasteSelection().
UpdateRGBChannels()
void BioImager.ImageView.UpdateRGBChannels ()
"If the user has selected a channel, then set the channel to the selected index, otherwise set it to 0."
The above function is called when the user changes the channel selection
Definition at line 842 of file ImageView.cs.
        {
            //Buf = image.GetBufByCoord(GetCoordinate());
            if (channelBoxR.SelectedIndex == -1)
                SelectedImage.rgbChannels[0] = 0;
            else
                SelectedImage.rgbChannels[1] = channelBoxR.SelectedIndex;
            if (channelBoxG.SelectedIndex == -1)
                SelectedImage.rgbChannels[1] = 0;
            else
                SelectedImage.rgbChannels[1] = channelBoxG.SelectedIndex;
            if (channelBoxB.SelectedIndex == -1)
                SelectedImage.rgbChannels[2] = 0;
            else
                SelectedImage.rgbChannels[2] = channelBoxB.SelectedIndex;
        }
Referenced by BioImager.ImageView.InitGUI().
UpdateSelectBoxSize()
void BioImager.ImageView.UpdateSelectBoxSize (float size)
This function is called from the Unity Editor when the user changes the size of the select box
Parameters
size The size of the box that will be drawn around the ROI.
Definition at line 959 of file ImageView.cs.
        {
            ROI.selectBoxSize = size;
        }
UpdateStatus()
void BioImager.ImageView.UpdateStatus ()
It updates the status bar of the image viewer
Returns
The statusLabel.Text is being returned.
Definition at line 980 of file ImageView.cs.
        {
            if (SelectedImage == null)
                return;
            string res = "";
            if (SelectedImage.Type == BioImage.ImageType.well)
                res = "Well:" + SelectedImage.Level;
            else if(SelectedImage.Type == BioImage.ImageType.pyramidal)
            {
                res = "Res.:" + Resolution;
            }
            if (Mode == ViewMode.RGBImage)
            {
                if (timeEnabled)
                {
                    statusLabel.Text = (zBar.Value + 1) + "/" + (zBar.Maximum + 1) + ", " + (tBar.Value + 1) + "/" + (tBar.Maximum + 1) + ", " +
                        mousePoint + mouseColor + ", " + SelectedImage.Buffers[0].PixelFormat.ToString() + ", (" + -Origin.X + ", " + -Origin.Y + "), (" + SelectedImage.Volume.Location.X + ", " + SelectedImage.Volume.Location.Y + ") " + res;
                }
                else
                {
                    statusLabel.Text = (zBar.Value + 1) + "/" + (cBar.Maximum + 1) + ", " + mousePoint + mouseColor + ", " + SelectedImage.Buffers[0].PixelFormat.ToString()
                        + ", (" + -Origin.X + ", " + -Origin.Y + "), (" + SelectedImage.Volume.Location.X + ", " + SelectedImage.Volume.Location.Y + ") " + res;
                }
            }
            else
            {
                if (timeEnabled)
                {
                    statusLabel.Text = (zBar.Value + 1) + "/" + (zBar.Maximum + 1) + ", " + (cBar.Value + 1) + "/" + (cBar.Maximum + 1) + ", " + (tBar.Value + 1) + "/" + (tBar.Maximum + 1) + ", " +
                        mousePoint + mouseColor + ", " + SelectedImage.Buffers[0].PixelFormat.ToString() + ", (" + -Origin.X + ", " + -Origin.Y + "), (" + SelectedImage.Volume.Location.X + ", " + SelectedImage.Volume.Location.Y + ") " + res;
                }
                else
                {
                    statusLabel.Text = (zBar.Value + 1) + "/" + (zBar.Maximum + 1) + ", " + (cBar.Value + 1) + "/" + (cBar.Maximum + 1) + ", " + mousePoint + mouseColor + ", " +
                        SelectedImage.Buffers[0].PixelFormat.ToString() + ", (" + -Origin.X + ", " + -Origin.Y + "), (" + SelectedImage.Volume.Location.X + ", " + SelectedImage.Volume.Location.Y + ") " + res;
                }
            }
        }
References BioImager.ImageView.Mode, and BioImager.ImageView.Resolution.
Referenced by BioImager.ImageView.UpdateView().
UpdateView() [1/2]
void BioImager.ImageView.UpdateView ()
If hardware acceleration is enabled, render the frame. Otherwise, invalidate the picture box.
Returns
The method is returning void.
Definition at line 1023 of file ImageView.cs.
        {
            UpdateStatus();
            if (HardwareAcceleration)
            {
                RenderFrame();
                return;
            }
            pictureBox.Invalidate();
            overlayPictureBox.Invalidate();
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.RenderFrame(), and BioImager.ImageView.UpdateStatus().
Referenced by BioImager.ImageView.GoToImage(), BioImager.ImageView.ImageView(), BioImager.ImageView.ImageView_KeyDown(), BioImager.ImageView.MoveStageToImage(), BioImager.ImageJ.RunOnImage(), BioImager.Stage.SetPosition(), BioImager.BioImage.To16Bit(), BioImager.BioImage.To24Bit(), BioImager.BioImage.To32Bit(), BioImager.BioImage.To48Bit(), BioImager.BioImage.To8Bit(), and BioImager.ImageView.UpdateImages().
UpdateView() [2/2]
void BioImager.ImageView.UpdateView (bool refresh)
‍Update the status of the application and then render the frame
Parameters
refresh boolean
Definition at line 1276 of file ImageView.cs.
        {
            UpdateStatus();
            update = refresh;
            if (HardwareAcceleration)
            {
                RenderFrame();
            }
            if (update)
            {
                pictureBox.Invalidate();
                overlayPictureBox.Invalidate();
            }
        }
References BioImager.ImageView.HardwareAcceleration, BioImager.ImageView.RenderFrame(), and BioImager.ImageView.UpdateStatus().
Member Data Documentation
Buf
Image BioImager.ImageView.Buf = null
Definition at line 207 of file ImageView.cs.
down
bool BioImager.ImageView.down static
Definition at line 190 of file ImageView.cs.
dx
Direct2D BioImager.ImageView.dx = null
Definition at line 165 of file ImageView.cs.
filepath
string BioImager.ImageView.filepath = ""
Definition at line 232 of file ImageView.cs.
Images
List<BioImage> BioImager.ImageView.Images = new List<BioImage>()
Definition at line 211 of file ImageView.cs.
init
bool BioImager.ImageView.init = false
Definition at line 208 of file ImageView.cs.
loopC
bool BioImager.ImageView.loopC = true
Definition at line 238 of file ImageView.cs.
loopT
bool BioImager.ImageView.loopT = true
Definition at line 237 of file ImageView.cs.
loopZ
bool BioImager.ImageView.loopZ = true
Definition at line 236 of file ImageView.cs.
minSizeX
int BioImager.ImageView.minSizeX = 50
Definition at line 234 of file ImageView.cs.
minSizeY
int BioImager.ImageView.minSizeY = 20
Definition at line 235 of file ImageView.cs.
mouseDown
PointD BioImager.ImageView.mouseDown static
Definition at line 189 of file ImageView.cs.
mouseDownButtons
MouseButtons BioImager.ImageView.mouseDownButtons static
Definition at line 203 of file ImageView.cs.
mouseUp
PointD BioImager.ImageView.mouseUp static
Definition at line 191 of file ImageView.cs.
mouseUpButtons
MouseButtons BioImager.ImageView.mouseUpButtons static
Definition at line 202 of file ImageView.cs.
selectedAnnotations
List<ROI> BioImager.ImageView.selectedAnnotations = new List<ROI>() static
Definition at line 163 of file ImageView.cs.
serie
int BioImager.ImageView.serie = 0
Definition at line 233 of file ImageView.cs.
showBounds
bool BioImager.ImageView.showBounds = true static
Definition at line 205 of file ImageView.cs.
showBROIs
bool BioImager.ImageView.showBROIs = true
Definition at line 1934 of file ImageView.cs.
showGROIs
bool BioImager.ImageView.showGROIs = true
Definition at line 1933 of file ImageView.cs.
showRROIs
bool BioImager.ImageView.showRROIs = true
Definition at line 1932 of file ImageView.cs.
showText
bool BioImager.ImageView.showText = true static
Definition at line 206 of file ImageView.cs.
up
bool BioImager.ImageView.up static
Definition at line 192 of file ImageView.cs.
Property Documentation
AnnotationsB
List<ROI> BioImager.ImageView.AnnotationsB get
Definition at line 1953 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.GetAnnotations(SelectedImage.Coordinate.Z, SelectedImage.BChannel.Index, SelectedImage.Coordinate.T);
            }
        }
AnnotationsG
List<ROI> BioImager.ImageView.AnnotationsG get
Definition at line 1945 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.GetAnnotations(SelectedImage.Coordinate.Z, SelectedImage.GChannel.Index, SelectedImage.Coordinate.T);
            }
        }
AnnotationsR
List<ROI> BioImager.ImageView.AnnotationsR get
Definition at line 1937 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.GetAnnotations(SelectedImage.Coordinate.Z, SelectedImage.RChannel.Index, SelectedImage.Coordinate.T);
            }
        }
AnnotationsRGB
List<ROI> BioImager.ImageView.AnnotationsRGB get
Definition at line 1960 of file ImageView.cs.
        {
            get
            {
                if (SelectedImage == null)
                    return null;
                List<ROI> ans = new List<ROI>();
                if (Mode == ViewMode.RGBImage)
                {
                    if (showRROIs)
                        ans.AddRange(AnnotationsR);
                    if (showGROIs)
                        ans.AddRange(AnnotationsG);
                    if (showBROIs)
                        ans.AddRange(AnnotationsB);
                }
                else
                {
                    ans.AddRange(SelectedImage.GetAnnotations(SelectedImage.Coordinate));
                }
                return ans;
            }
        }
BChannel
Channel BioImager.ImageView.BChannel get
Getting the B channel of the image. *‍/.
Definition at line 606 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.Channels[SelectedImage.rgbChannels[2]];
            }
        }
CFps
int BioImager.ImageView.CFps get set
Setting the interval of the timer to the inverse of the fps. *‍/.
Definition at line 892 of file ImageView.cs.
        {
            get
            {
                return cfps;
            }
            set
            {
                cfps = value;
                float f = value;
                cTimer.Interval = (int)Math.Floor(1000 / f);
            }
        }
Referenced by BioImager.ImageView.ImageView().
Ctrl
bool BioImager.ImageView.Ctrl static get
Definition at line 193 of file ImageView.cs.
        {
            get
            {
                return Win32.GetKeyState(Keys.LControlKey);
            }
        }
GChannel
Channel BioImager.ImageView.GChannel get
A property that returns the G channel of the image. *‍/.
Definition at line 598 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.Channels[SelectedImage.rgbChannels[1]];
            }
        }
HardwareAcceleration
bool BioImager.ImageView.HardwareAcceleration get set
Whether or not Hardware Acceleration should be used for rendering.
Definition at line 795 of file ImageView.cs.
        {
            get
            {
                if (Images.Count > 0)
                    if (Images[0].isPyramidal)
                        return false;
                return hardwareAcceleration;
            }
            set
            {
                hardwareAcceleration = value;
                if (value)
                {
                    GoToImage(0);
                    cBar.Value = 0;
                    rgbBoxsPanel.SendToBack();
                    pictureBox.BringToFront();
                    cBar.BringToFront();
                    cLabel.BringToFront();
                    dxPanel.Visible = true;
                    dxPanel.BringToFront();
                }
                else
                {
                    GoToImage(0);
                    rgbBoxsPanel.SendToBack();
                    cBar.BringToFront();
                    cLabel.BringToFront();
                    dxPanel.Visible = false;
                    pictureBox.BringToFront();
                    overlayPictureBox.BringToFront();
                }
            }
        }
Referenced by BioImager.ImageView.DrawView(), BioImager.ImageView.GoToImage(), BioImager.ImageView.ImageView(), BioImager.ImageView.RenderFrame(), BioImager.Tools.ToolDown(), BioImager.Tools.ToolUp(), BioImager.ImageView.ToScreenH(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenScaleH(), BioImager.ImageView.ToScreenScaleW(), BioImager.ImageView.ToScreenSpace(), BioImager.ImageView.ToScreenW(), BioImager.ImageView.ToViewSpace(), BioImager.ImageView.UpdateImages(), BioImager.ImageView.UpdateOverlay(), and BioImager.ImageView.UpdateView().
LabelResolution
int? BioImager.ImageView.LabelResolution get
Definition at line 621 of file ImageView.cs.
{ get { return SelectedImage.LabelResolution; } }
Layers
List<Layer> BioImager.ImageView.Layers get set
Definition at line 146 of file ImageView.cs.
        {
            get { return layers; }
            set { layers = value; }
        }
Level
int BioImager.ImageView.Level get
Current level when viewing whole-slide and pyramidal images.
Definition at line 757 of file ImageView.cs.
        {
            get
            {
                int l = 0;
                if (!openSlide)
                    l = SelectedImage.Level;
                else
                    l = OpenSlideGTK.TileUtil.GetLevel(_openSlideBase.Schema.Resolutions, Resolution);
                return l;
            }
        }
Referenced by BioImager.ImageView.AddImage(), BioImager.ImageView.DrawView(), BioImager.ImageView.ImageView(), and BioImager.TabsView.ResizeView().
MacroResolution
int? BioImager.ImageView.MacroResolution get
Definition at line 620 of file ImageView.cs.
{ get { return SelectedImage.MacroResolution; } }
Mode
ViewMode BioImager.ImageView.Mode get set
Setting the view mode of the application. *‍/.
Definition at line 496 of file ImageView.cs.
        {
            get
            {
                return viewMode;
            }
            set
            {
                viewMode = value;
                //If view mode is changed we update.
                update = true;
                UpdateImages();
                App.tabsView.UpdateViewMode(viewMode);
                UpdateView();
                UpdateOverlay();
                if (viewMode == ViewMode.RGBImage)
                {
                    cBar.Value = 0;
                    rgbBoxsPanel.BringToFront();
                    cBar.SendToBack();
                    cLabel.SendToBack();
                    if (HardwareAcceleration)
                    {
                        dxPanel.Visible = HardwareAcceleration;
                        dxPanel.BringToFront();
                    }
                    else
                    {
                        pictureBox.BringToFront();
                        overlayPictureBox.BringToFront();
                    }
                }
                else
                if (viewMode == ViewMode.Filtered)
                {
                    rgbBoxsPanel.SendToBack();
                    cBar.BringToFront();
                    cLabel.BringToFront();
                    if (HardwareAcceleration)
                    {
                        dxPanel.Visible = HardwareAcceleration;
                        dxPanel.BringToFront();
                    }
                    else
                    {
                        pictureBox.BringToFront();
                        overlayPictureBox.BringToFront();
                    }
                }
                else
                if (viewMode == ViewMode.Raw)
                {
                    rgbBoxsPanel.SendToBack();
                    cBar.BringToFront();
                    cLabel.BringToFront();
                    if (HardwareAcceleration)
                    {
                        dxPanel.Visible = HardwareAcceleration;
                        dxPanel.BringToFront();
                    }
                    else
                    {
                        pictureBox.BringToFront();
                        overlayPictureBox.BringToFront();
                    }
                }
                else
                {
                    cBar.Value = 0;
                    rgbBoxsPanel.BringToFront();
                    cBar.SendToBack();
                    cLabel.SendToBack();
                    if (HardwareAcceleration)
                    {
                        dxPanel.Visible = HardwareAcceleration;
                        dxPanel.BringToFront();
                    }
                    else
                    {
                        pictureBox.BringToFront();
                        overlayPictureBox.BringToFront();
                    }
                }
            }
        }
Referenced by BioImager.ImageView.GetRange(), BioImager.ImageView.ImageView(), BioImager.ImageView.UpdateImages(), and BioImager.ImageView.UpdateStatus().
MouseDownInt
PointD BioImager.ImageView.MouseDownInt get set
Definition at line 3274 of file ImageView.cs.
        {
            get { return mouseDownInt; }
            set { mouseDownInt = value; }
        }
MouseMoveInt
PointD BioImager.ImageView.MouseMoveInt get set
Definition at line 3279 of file ImageView.cs.
        {
            get { return mouseMoveInt; }
            set { mouseMoveInt = value; }
        }
OpenSlide
bool BioImager.ImageView.OpenSlide get
Definition at line 616 of file ImageView.cs.
        {
            get { return openSlide; }
        }
Origin
PointD BioImager.ImageView.Origin get set
A property of the class PointD. *‍/.
Definition at line 643 of file ImageView.cs.
        {
            get { return origin; }
            set
            {
                origin = value;
                update = true;
            }
        }
Referenced by BioImager.ImageView.DrawView(), BioImager.ImageView.GoToImage(), BioImager.ImageView.ImageView_KeyDown(), BioImager.ImageView.RenderFrame(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenSpace(), and BioImager.ImageView.ToViewSpace().
Path
string BioImager.ImageView.Path get
A property that returns the filepath. *‍/.
Definition at line 582 of file ImageView.cs.
        {
            get
            {
                return filepath;
            }
        }
PxHmicron
double BioImager.ImageView.PxHmicron get set
Only used when opening stacks.
Definition at line 476 of file ImageView.cs.
        {
            get
            {
                return pxHmicron;
            }
            set
            {
                pxHmicron = value;
            }
        }
Referenced by BioImager.ImageView.ToScreenH(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenScaleH(), BioImager.ImageView.ToViewH(), and BioImager.ImageView.ToViewSizeH().
PxWmicron
double BioImager.ImageView.PxWmicron get set
Only used when opening stacks.
Definition at line 462 of file ImageView.cs.
        {
            get
            {
                return pxWmicron;
            }
            set
            {
                pxWmicron = value;
            }
        }
Referenced by BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenScaleW(), BioImager.ImageView.ToScreenW(), and BioImager.ImageView.ToViewW().
PyramidalOrigin
PointD BioImager.ImageView.PyramidalOrigin get set
Setting the value of the pyramidalOrigin variable. *‍/.
Definition at line 653 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.PyramidalOrigin;
            }
            set
            {
                if (SelectedImage.Resolutions[Level].SizeX > value.X || SelectedImage.Resolutions[Level].SizeY > value.Y)
                {
                    SelectedImage.PyramidalOrigin = value;
                    UpdateImages();
                    UpdateView();
                }
            }
        }
Referenced by BioImager.ImageView.DrawView(), BioImager.ImageView.GoToImage(), BioImager.ImageView.ImageToViewSpace(), BioImager.BioImage.SaveOMESeries(), BioImager.ImageView.ToScreenRectF(), and BioImager.ImageView.UpdateImages().
PyramidalOriginTransformed
PointD BioImager.ImageView.PyramidalOriginTransformed get set
Definition at line 3265 of file ImageView.cs.
        {
            get { return new PointD(PyramidalOrigin.X * Resolution, PyramidalOrigin.Y * Resolution); }
            set { PyramidalOrigin = new PointD(value.X / Resolution, value.Y / Resolution); }
        }
RChannel
Channel BioImager.ImageView.RChannel get
A property that returns the R channel of the selected image. *‍/.
Definition at line 590 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.Channels[SelectedImage.rgbChannels[0]];
            }
        }
Resolution
double BioImager.ImageView.Resolution get set
A property of the class ImageViewer. It is a getter and setter for the resolution of the image.
Definition at line 670 of file ImageView.cs.
        {
            get
            {
                return SelectedImage.Resolution;
            }
            set
            {
                double dp = Resolution / value;
                SelectedImage.PyramidalOrigin = new PointD((dp * PyramidalOrigin.X), (dp * PyramidalOrigin.Y));
                SelectedImage.Resolution = value;
                if (SelectedImage.Type == BioImage.ImageType.well)
                    SelectedImage.Level = (int)value;
                UpdateImage();
                UpdateView();
                UpdateScrollBars();
            }
        }
Referenced by BioImager.ImageView.DrawView(), BioImager.ImageView.ToViewSizeH(), BioImager.ImageView.ToViewSpace(), and BioImager.ImageView.UpdateStatus().
Scale
new AForge.SizeF BioImager.ImageView.Scale get set
Scale when opening image stacks.
Definition at line 772 of file ImageView.cs.
        {
            get
            {
                return scale;
            }
            set
            {
                scale = value;
                update = true;
                UpdateView();
                if (SelectedImage != null)
                    if (SelectedImage.isPyramidal)
                    {
                        Tools.selectBoxSize = (float)(ROI.selectBoxSize * Resolution);
                    }
                    else
                        Tools.selectBoxSize = ROI.selectBoxSize;
            }
        }
Referenced by BioImager.ImageView.DrawView(), BioImager.ImageView.GetScale(), BioImager.ImageView.GoToImage(), BioImager.ImageView.ImageView_KeyDown(), BioImager.ImageView.RenderFrame(), BioImager.ImageView.ToScreenRectF(), BioImager.ImageView.ToScreenScaleH(), BioImager.ImageView.ToScreenScaleW(), and BioImager.ImageView.ToViewSpace().
SelectedBuffer
Bitmap BioImager.ImageView.SelectedBuffer static get
Definition at line 181 of file ImageView.cs.
        {
            get
            {
                int ind = SelectedImage.Coords[SelectedImage.Coordinate.Z, SelectedImage.Coordinate.C, SelectedImage.Coordinate.T];
                return SelectedImage.Buffers[ind];
            }
        }
SelectedImage
BioImage BioImager.ImageView.SelectedImage static get
Definition at line 166 of file ImageView.cs.
        {
            get
            {
                if (App.viewer != null)
                {
                    if (App.viewer.Images.Count > 0)
                        return App.viewer.Images[selectedIndex];
                    else
                        return null;
                }
                else
                    return null;
            }
        }
SelectedIndex
int BioImager.ImageView.SelectedIndex get set
A property that is used to set the selected index of the image. *‍/.
Definition at line 215 of file ImageView.cs.
        {
            get
            {
                return selIndex;
            }
            set
            {
                if (value >= 0 && Images.Count > 0)
                {
                    selIndex = value;
                    selectedIndex = selIndex;
                    InitGUI();
                }
            }
        }
Referenced by BioImager.ImageView.AddImage(), BioImager.ImageView.DrawView(), BioImager.ImageJ.RunOnImage(), and BioImager.ImageView.UpdateImages().
ShowControls
bool BioImager.ImageView.ShowControls get set
Setting the visibility of the trackBarPanel. *‍/.
Definition at line 366 of file ImageView.cs.
        {
            get { return trackBarPanel.Visible; }
            set
            {
                showControls = value;
                if (!value)
                {
                    trackBarPanel.Hide();
                    if (ShowStatus)
                    {
                        pictureBox.Top = 25;
                        overlayPictureBox.Top = 25;
                        dxPanel.Top = 25;
                        pictureBox.Height += 75;
                        overlayPictureBox.Height += 75;
                        dxPanel.Height += 75;
                    }
                    else
                    {
                        pictureBox.Top = 0;
                        overlayPictureBox.Top = 0;
                        dxPanel.Top = 0;
                        pictureBox.Height += 75;
                        overlayPictureBox.Height += 75;
                        dxPanel.Height += 75;
                    }
                    hideControlsToolStripMenuItem1.Text = "Show Controls";
                }
                else
                {
                    trackBarPanel.Show();
                    if (ShowStatus)
                    {
                        pictureBox.Top = 25;
                        overlayPictureBox.Top = 25;
                        dxPanel.Top = 25;
                        pictureBox.Height -= 75;
                        overlayPictureBox.Height -= 75;
                        dxPanel.Height -= 75;
                    }
                    else
                    {
                        pictureBox.Top = 0;
                        overlayPictureBox.Top = 0;
                        dxPanel.Top = 0;
                        pictureBox.Height += 75;
                        overlayPictureBox.Height += 75;
                        dxPanel.Height += 75;
                    }
                    //panel.Anchor = AnchorStyles.Top | AnchorStyles.Right | AnchorStyles.Bottom | AnchorStyles.Left;
                    hideControlsToolStripMenuItem1.Text = "Hide Controls";
                }
                UpdateView();
            }
        }
ShowOverview
bool BioImager.ImageView.ShowOverview get set
Definition at line 362 of file ImageView.cs.
{ get; set; }
ShowStage
bool BioImager.ImageView.ShowStage get set
Definition at line 241 of file ImageView.cs.
{ get; set; }
ShowStatus
bool BioImager.ImageView.ShowStatus get set
Setting the value of the property ShowStatus. *‍/.
Definition at line 426 of file ImageView.cs.
        {
            get { return showStatus; }
            set
            {
                showStatus = true;
                if (!value)
                {
                    statusPanel.Hide();
                    //panel.Top = 0;
                    pictureBox.Top = 0;
                    overlayPictureBox.Top = 0;
                    dxPanel.Top = 0;
                    //panel.Height += 25;
                    pictureBox.Height += 25;
                    overlayPictureBox.Height += 25;
                    dxPanel.Height += 25;
                    showControlsToolStripMenuItem.Visible = true;
                    hideControlsToolStripMenuItem.Text = "Show Status";
                }
                else
                {
                    statusPanel.Show();
                    statusPanel.Visible = value;
                    pictureBox.Top = 25;
                    overlayPictureBox.Top = 25;
                    dxPanel.Top = 25;
                    showControlsToolStripMenuItem.Visible = false;
                    hideControlsToolStripMenuItem.Text = "Hide Status";
                }
            }
        }
TimeFps
int BioImager.ImageView.TimeFps get set
Setting the interval of the timer to the value of the timefps variable. *‍/.
Definition at line 877 of file ImageView.cs.
        {
            get
            {
                return timefps;
            }
            set
            {
                timefps = value;
                float f = value;
                timelineTimer.Interval = (int)Math.Floor(1000 / f);
            }
        }
Referenced by BioImager.ImageView.ImageView().
tools
Tools BioImager.ImageView.tools get
Definition at line 231 of file ImageView.cs.
{ get { return App.tools; } }
ViewContextMenu
ContextMenuStrip BioImager.ImageView.ViewContextMenu get
A property that returns a ContextMenuStrip object. *‍/.
Definition at line 831 of file ImageView.cs.
        {
            get
            {
                return contextMenuStrip;
            }
        }
Referenced by BioImager.App.GetContextItems(), and BioImager.App.GetContextMenuItemFromPath().
ViewHeight
int BioImager.ImageView.ViewHeight get
Definition at line 632 of file ImageView.cs.
        {
            get
            {
                if (HardwareAcceleration)
                    return dxPanel.Height;
                else
                    return pictureBox.Height;
            }
        }
ViewWidth
int BioImager.ImageView.ViewWidth get
Definition at line 622 of file ImageView.cs.
        {
            get
            {
                if (HardwareAcceleration)
                    return dxPanel.Width;
                else
                    return pictureBox.Width;
            }
        }
ZFps
int BioImager.ImageView.ZFps get set
Setting the interval of the timer to the value of the fps. *‍/.
Definition at line 862 of file ImageView.cs.
        {
            get
            {
                return zfps;
            }
            set
            {
                zfps = value;
                float f = value;
                zTimer.Interval = (int)Math.Floor(1000 / f);
            }
        }
Referenced by BioImager.ImageView.ImageView().
The documentation for this class was generated from the following files:
F:/repos/BioImager/BioImager/Source/ImageView.cs
F:/repos/BioImager/BioImager/Source/ImageView.designer.cs