BioImager: microscope.testsuite.devices.TestCamera Class Reference
microscope.testsuite.devices.TestCamera Class Reference
Public Member Functions
None __init__ (self, **kwargs)
Public Member Functions inherited from microscope.simulators.SimulatedCamera
def __init__ (self, **kwargs)
def abort (self)
def set_exposure_time (self, value)
def get_exposure_time (self)
def get_cycle_time (self)
def soft_trigger (self)
Public Member Functions inherited from microscope._utils.OnlyTriggersOnceOnSoftwareMixin
microscope.TriggerType trigger_type (self)
microscope.TriggerMode trigger_mode (self)
None set_trigger (self, microscope.TriggerType ttype, microscope.TriggerMode tmode)
Public Member Functions inherited from microscope.abc.TriggerTargetMixin
microscope.TriggerMode trigger_mode (self)
microscope.TriggerType trigger_type (self)
None set_trigger (self, microscope.TriggerType ttype, microscope.TriggerMode tmode)
None trigger (self)
Public Member Functions inherited from microscope.abc.Camera
None __init__ (self, **kwargs)
def set_readout_mode (self, description)
def get_transform (self)
def set_transform (self, transform)
None set_exposure_time (self, float value)
float get_exposure_time (self)
float get_cycle_time (self)
typing.Tuple[int, int] get_sensor_shape (self)
microscope.Binning get_binning (self)
None set_binning (self, microscope.Binning binning)
microscope.ROI get_roi (self)
None set_roi (self, microscope.ROI roi)
Public Member Functions inherited from microscope.abc.DataDevice
None __init__ (self, int buffer_length=0, **kwargs)
def __del__ (self)
None abort (self)
None enable (self)
None disable (self)
None set_client (self, new_client)
None update_settings (self, settings, bool init=False)
None receiveClient (self, str client_uri)
def grab_next_data (self, bool soft_trigger=True)
None receiveData (self, data, timestamp)
Public Member Functions inherited from microscope.abc.Device
None __init__ (self)
None __del__ (self)
bool get_is_enabled (self)
None disable (self)
None enable (self)
None initialize (self)
None shutdown (self)
None add_setting (self, name, dtype, get_func, set_func, values, typing.Optional[typing.Callable[[], bool]] readonly=None)
def get_setting (self, str name)
def get_all_settings (self)
None set_setting (self, str name, value)
def describe_setting (self, str name)
def describe_settings (self)
def update_settings (self, incoming, bool init=False)
Additional Inherited Members
Public Attributes inherited from microscope.abc.DataDevice
enabled
Public Attributes inherited from microscope.abc.Device
enabled
Static Public Attributes inherited from microscope.abc.Camera
list ALLOWED_TRANSFORMS = [p for p in itertools.product(*3 * [[False, True]])]
Static Public Attributes inherited from microscope.abc.DataDevice
set_setting = keep_acquiring(Device.set_setting)
Detailed Description
Definition at line 49 of file devices.py.
Constructor & Destructor Documentation
__init__()
None microscope.testsuite.devices.TestCamera.__init__ (self, ** buffer_length)
Derived.__init__ must call this at some point.
Reimplemented from microscope.simulators.SimulatedCamera.
Definition at line 52 of file devices.py.
    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        # Enum-setting tests
        self._intEnum = CamEnum.A
        self.add_setting(
            "intEnum",
            "enum",
            lambda: self._intEnum,
            lambda val: setattr(self, "_intEnum", val),
            CamEnum,
        )
        self._dictEnum = 0
        self.add_setting(
            "dictEnum",
            "enum",
            lambda: self._dictEnum,
            lambda val: setattr(self, "_dictEnum", val),
            {0: "A", 8: "B", 13: "C", 22: "D"},
        )
        self._listEnum = 0
        self.add_setting(
            "listEnum",
            "enum",
            lambda: self._listEnum,
            lambda val: setattr(self, "_listEnum", val),
            ["A", "B", "C", "D"],
        )
        self._tupleEnum = 0
        self.add_setting(
            "tupleEnum",
            "enum",
            lambda: self._tupleEnum,
            lambda val: setattr(self, "_tupleEnum", val),
            ("A", "B", "C", "D"),
        )
References microscope.testsuite.devices.TestCamera.__init__(), microscope.testsuite.devices.TestCamera._dictEnum, microscope.testsuite.devices.TestCamera._intEnum, microscope.testsuite.devices.TestCamera._listEnum, microscope.testsuite.devices.TestCamera._tupleEnum, and microscope.abc.Device.add_setting().
Referenced by microscope.testsuite.devices.TestCamera.__init__().
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/PythonMicroscope/microscope/testsuite/devices.py