BioImager: BioImager.ROI Class Reference
BioImager.ROI Class Reference
Classes
class Mask
Represents a Mask layer.
Public Types
enum Type
Public Member Functions
ROI Copy ()
ROI Copy (ZCT cord)
RectangleD GetSelectBound (double scaleX, double scaleY)
RectangleD[] GetSelectBoxes ()
RectangleD[] GetSelectBoxes (double s)
void UpdatePoint (PointD p, int i)
PointD GetPoint (int i)
PointD[] GetPoints ()
PointF[] GetPointsF ()
void AddPoint (PointD p)
void AddPoints (PointD[] p)
void AddPoints (float[] xp, float[] yp)
void AddPoints (int[] xp, int[] yp)
void RemovePoints (int[] indexs)
int GetPointCount ()
PointD[] stringToPoints (string s)
string PointsToString (BioImage b)
void UpdateBoundingBox ()
override string ToString ()
Static Public Member Functions
static ROI CreatePoint (ZCT coord, double x, double y)
static ROI CreatePoint (int s, int z, int c, int t, double x, double y)
static ROI CreateLine (ZCT coord, PointD x1, PointD x2)
static ROI CreateRectangle (ZCT coord, double x, double y, double w, double h)
static ROI CreateEllipse (ZCT coord, double x, double y, double w, double h)
static ROI CreatePolygon (ZCT coord, PointD[] pts)
static ROI CreateFreeform (ZCT coord, PointD[] pts)
static ROI CreateMask (ZCT coord, float[] mask, int width, int height, PointD loc, double physicalX, double physicalY)
static ROI CreateMask (ZCT coord, byte[] mask, int width, int height, PointD loc, double physicalX, double physicalY)
Public Attributes
Type type
List< int > selectedPoints = new List<int>()
RectangleD BoundingBox
Font font = System.Drawing.SystemFonts.DefaultFont
ZCT coord
System.Drawing.Color strokeColor
System.Drawing.Color fillColor
bool isFilled = false
string id = ""
string roiID = ""
string roiName = ""
int serie = 0
string properties
double strokeWidth = 1
float fontSize = 8
string family = ""
int shapeIndex = 0
bool closed = false
bool selected = false
Static Public Attributes
static float selectBoxSize = 8f
Properties
PointD Point [get, set]
RectangleD Rect [get, set]
double X [get, set]
double Y [get, set]
double W [get, set]
double H [get, set]
List< PointD > PointsD [get]
PointD[] PointsImage [get]
string Text [get, set]
System.Drawing.Size TextSize [get]
Mask roiMask [get, set]
Detailed Description
Definition at line 292 of file Bio.cs.
Member Enumeration Documentation
Type
enum BioImager.ROI.Type
Definition at line 294 of file Bio.cs.
        {
            Rectangle,
            Point,
            Line,
            Polygon,
            Polyline,
            Freeform,
            Ellipse,
            Label,
            Mask
        }
Constructor & Destructor Documentation
ROI()
BioImager.ROI.ROI ()
Definition at line 711 of file Bio.cs.
        {
            coord = new ZCT(0, 0, 0);
            strokeColor = System.Drawing.Color.Yellow;
            font = SystemFonts.DefaultFont;
            BoundingBox = new RectangleD(0, 0, 1, 1);
        }
Member Function Documentation
AddPoint()
void BioImager.ROI.AddPoint (PointD p)
This function adds a point to the list of points that make up the polygon
Parameters
PointD
Definition at line 934 of file Bio.cs.
        {
            Points.Add(p);
            UpdateBoundingBox();
        }
References BioImager.ROI.UpdateBoundingBox().
Referenced by BioImager.ROI.CreateLine(), BioImager.ROI.CreatePoint(), BioImager.BioImage.OpenOME(), BioImager.BioImage.OpenOMEROIs(), BioImager.Tools.ToolDown(), and BioImager.Tools.ToolUp().
AddPoints() [1/3]
void BioImager.ROI.AddPoints (float[] xp, float[] yp)
‍Adds a range of float points to the Points collection and updates the bounding box
Parameters
p The points to add to the polygon
Definition at line 950 of file Bio.cs.
        {
            for (int i = 0; i < xp.Length; i++)
            {
                Points.Add(new PointD(xp[i], yp[i]));
            }
            UpdateBoundingBox();
        }
References BioImager.ROI.UpdateBoundingBox().
AddPoints() [2/3]
void BioImager.ROI.AddPoints (int[] xp, int[] yp)
‍Adds a range of float points to the Points collection and updates the bounding box
Parameters
p The points to add to the polygon
Definition at line 961 of file Bio.cs.
        {
            for (int i = 0; i < xp.Length; i++)
            {
                Points.Add(new PointD(xp[i], yp[i]));
            }
            UpdateBoundingBox();
        }
References BioImager.ROI.UpdateBoundingBox().
AddPoints() [3/3]
void BioImager.ROI.AddPoints (PointD[] p)
‍Adds a range of points to the Points collection and updates the bounding box
Parameters
p The points to add to the polygon
Definition at line 942 of file Bio.cs.
        {
            Points.AddRange(p);
            UpdateBoundingBox();
        }
References BioImager.ROI.UpdateBoundingBox().
Referenced by BioImager.ROI.CreateFreeform(), BioImager.ROI.CreatePolygon(), BioImager.BioImage.OpenOME(), BioImager.BioImage.OpenOMEROIs(), and BioImager.BioImage.StringToROI().
Copy() [1/2]
ROI BioImager.ROI.Copy ()
Copy() is a function that copies the values of the ROI object to a new ROI object
Returns
A copy of the ROI object.
Definition at line 463 of file Bio.cs.
        {
            ROI copy = new ROI();
            copy.id = id;
            copy.roiID = roiID;
            copy.roiName = roiName;
            copy.text = text;
            copy.strokeWidth = strokeWidth;
            copy.strokeColor = strokeColor;
            copy.fillColor = fillColor;
            copy.Points = Points;
            copy.selected = selected;
            copy.shapeIndex = shapeIndex;
            copy.closed = closed;
            copy.font = font;
            copy.selectBoxs = selectBoxs;
            copy.BoundingBox = BoundingBox;
            copy.isFilled = isFilled;
            copy.coord = coord;
            copy.selectedPoints = selectedPoints;
            return copy;
        }
Copy() [2/2]
ROI BioImager.ROI.Copy (ZCT cord)
Copy() is a function that copies the ROI object and returns a new ROI object
Parameters
ZCT A class that contains the coordinates of the image.
Returns
A copy of the ROI object.
Definition at line 491 of file Bio.cs.
        {
            ROI copy = new ROI();
            copy.type = type;
            copy.id = id;
            copy.roiID = roiID;
            copy.roiName = roiName;
            copy.text = text;
            copy.strokeWidth = strokeWidth;
            copy.strokeColor = strokeColor;
            copy.fillColor = fillColor;
            copy.Points.AddRange(Points);
            copy.selected = selected;
            copy.shapeIndex = shapeIndex;
            copy.closed = closed;
            copy.font = font;
            copy.selectBoxs.AddRange(selectBoxs);
            copy.BoundingBox = BoundingBox;
            copy.isFilled = isFilled;
            copy.coord = cord;
            copy.selectedPoints = selectedPoints;
            return copy;
        }
CreateEllipse()
static ROI BioImager.ROI.CreateEllipse (ZCT coord, double x, double y, double w, double h) static
Create an ellipse ROI at the specified ZCT coordinate with the specified dimensions
Parameters
ZCT The ZCT coordinates of the image you want to create the ROI on.
x x-coordinate of the top-left corner of the rectangle
y The y-coordinate of the upper-left corner of the rectangle to create.
w width
h height
Returns
A new ROI object.
Definition at line 833 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.type = Type.Ellipse;
            an.Rect = new RectangleD(x, y, w, h);
            Recorder.AddLine("ROI.CreateEllipse(new ZCT(" + coord.Z + "," + coord.C + "," + coord.T + "), new RectangleD(" + x + "," + y + "," + w + "," + h + ");");
            return an;
        }
Referenced by BioImager.ImageJ.RoiDecoder.getRoi().
CreateFreeform()
static ROI BioImager.ROI.CreateFreeform (ZCT coord, PointD[] pts) static
‍Create a new ROI object of type Freeform, with the specified ZCT coordinates and points
Parameters
ZCT A class that contains the Z, C, and T coordinates of the ROI.
pts an array of PointD objects, which are just a pair of doubles (x,y)
Returns
A new ROI object.
Definition at line 863 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.type = Type.Freeform;
            an.AddPoints(pts);
            an.closed = true;
            return an;
        }
References BioImager.ROI.AddPoints().
Referenced by BioImager.Tools.ToolUp().
CreateLine()
static ROI BioImager.ROI.CreateLine (ZCT coord, PointD x1, PointD x2) static
Create a line ROI with the specified coordinates
Parameters
ZCT Z is the Z-axis, C is the color channel, and T is the time frame.
PointD A point in the image.
PointD A point in the image.
Returns
A new ROI object.
Definition at line 796 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.type = Type.Line;
            an.AddPoint(x1);
            an.AddPoint(x2);
            Recorder.AddLine("ROI.CreateLine(new ZCT(" + coord.Z + "," + coord.C + "," + coord.T + "), new PointD(" + x1.X + "," + x1.Y + "), new PointD(" + x2.X + "," + x2.Y + "));");
            return an;
        }
References BioImager.ROI.AddPoint().
Referenced by BioImager.ImageJ.RoiDecoder.getRoi().
CreateMask() [1/2]
static ROI BioImager.ROI.CreateMask (ZCT coord, byte[] mask, int width, int height, PointD loc, double physicalX, double physicalY) static
Definition at line 881 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.type = Type.Mask;
            an.roiMask = new Mask(mask, width, height, physicalX, physicalY);
            an.AddPoint(loc);
            return an;
        }
CreateMask() [2/2]
static ROI BioImager.ROI.CreateMask (ZCT coord, float[] mask, int width, int height, PointD loc, double physicalX, double physicalY) static
Definition at line 872 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.type = Type.Mask;
            an.roiMask = new Mask(mask, width, height, physicalX, physicalY);
            an.AddPoint(loc);
            return an;
        }
CreatePoint() [1/2]
static ROI BioImager.ROI.CreatePoint (int s, int z, int c, int t, double x, double y) static
Create a point ROI at the specified ZCT coordinates and x,y coordinates
Parameters
s series
z the z-slice of the image
c channel
t timepoint
x x coordinate of the point
y y-coordinate of the point
Returns
A point ROI
Definition at line 785 of file Bio.cs.
        {
            return CreatePoint(new ZCT(z, c, t), x, y);
        }
References BioImager.ROI.CreatePoint().
CreatePoint() [2/2]
static ROI BioImager.ROI.CreatePoint (ZCT coord, double x, double y) static
Create a new ROI object, add a point to it, and return it
Parameters
ZCT a class that contains the Z, C, and T coordinates of the image.
x x coordinate of the point
y The y coordinate of the point
Returns
A new ROI object
Definition at line 766 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.AddPoint(new PointD(x, y));
            an.type = Type.Point;
            Recorder.AddLine("ROI.CreatePoint(new ZCT(" + coord.Z + "," + coord.C + "," + coord.T + "), " + x + "," + y + ");");
            return an;
        }
References BioImager.ROI.AddPoint().
Referenced by BioImager.ROI.CreatePoint().
CreatePolygon()
static ROI BioImager.ROI.CreatePolygon (ZCT coord, PointD[] pts) static
‍Create a new ROI object of type Polygon, with the given coordinate system and points
Parameters
ZCT The ZCT coordinate of the ROI.
pts an array of PointD objects, which are just a pair of doubles (x,y)
Returns
A ROI object
Definition at line 848 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.type = Type.Polygon;
            an.AddPoints(pts);
            an.closed = true;
            return an;
        }
References BioImager.ROI.AddPoints().
CreateRectangle()
static ROI BioImager.ROI.CreateRectangle (ZCT coord, double x, double y, double w, double h) static
Create a new ROI object with a rectangle shape, and add a line to the recorder
Parameters
ZCT The ZCT coordinates of the image you want to create the ROI on.
x x coordinate of the top left corner of the rectangle
y y-coordinate of the top-left corner of the rectangle
w width
h height
Returns
A new ROI object.
Definition at line 815 of file Bio.cs.
        {
            ROI an = new ROI();
            an.coord = coord;
            an.type = Type.Rectangle;
            an.Rect = new RectangleD(x, y, w, h);
            Recorder.AddLine("ROI.CreateRectangle(new ZCT(" + coord.Z + "," + coord.C + "," + coord.T + "), new RectangleD(" + x + "," + y + "," + w + "," + h + ");");
            return an;
        }
Referenced by BioImager.ImageJ.RoiDecoder.getRoi().
GetPoint()
PointD BioImager.ROI.GetPoint (int i)
This function returns the point at the specified index
Parameters
i The index of the point to get.
Returns
The point at index i in the Points array.
Definition at line 907 of file Bio.cs.
        {
            return Points[i];
        }
Referenced by BioImager.ImageView.RenderFrame(), and BioImager.BioImage.SaveOMESeries().
GetPointCount()
int BioImager.ROI.GetPointCount ()
This function returns the number of points in the polygon
Returns
The number of points in the list.
Definition at line 992 of file Bio.cs.
        {
            return Points.Count;
        }
Referenced by BioImager.ImageView.RenderFrame(), BioImager.Tools.ToolDown(), and BioImager.Tools.ToolUp().
GetPoints()
PointD[] BioImager.ROI.GetPoints ()
It returns an array of PointD objects
Returns
An array of PointD objects.
Definition at line 914 of file Bio.cs.
        {
            return Points.ToArray();
        }
Referenced by BioImager.BioImage.ROIToString().
GetPointsF()
PointF[] BioImager.ROI.GetPointsF ()
It converts a list of points to an array of points
Returns
A PointF array.
Definition at line 921 of file Bio.cs.
        {
            PointF[] pfs = new PointF[Points.Count];
            for (int i = 0; i < Points.Count; i++)
            {
                pfs[i].X = (float)Points[i].X;
                pfs[i].Y = (float)Points[i].Y;
            }
            return pfs;
        }
GetSelectBound()
RectangleD BioImager.ROI.GetSelectBound (double scaleX, double scaleY)
‍This function returns a rectangle that is the bounding box of the object, but with a
border of half the scale
Parameters
scale the scale of the image
Returns
A rectangle with the following properties:
Definition at line 724 of file Bio.cs.
        {
            double fx = scaleX / 2;
            double fy = scaleY / 2;
            return new RectangleD(BoundingBox.X - fx, BoundingBox.Y - fy, BoundingBox.W + scaleX, BoundingBox.H + scaleY);
        }
Referenced by BioImager.Tools.ToolUp().
GetSelectBoxes() [1/2]
RectangleD[] BioImager.ROI.GetSelectBoxes ()
It creates a list of rectangles, each rectangle is a square with a side length of ROI.selectBoxSize, and the center of the square is the point in the list of points
Returns
A list of RectangleF objects.
Definition at line 734 of file Bio.cs.
        {
            selectBoxs.Clear();
            for (int i = 0; i < Points.Count; i++)
            {
                selectBoxs.Add(new RectangleD((Points[i].X), (Points[i].Y), ROI.selectBoxSize, ROI.selectBoxSize));
            }
            return selectBoxs.ToArray();
        }
Referenced by BioImager.ImageView.RenderFrame(), and BioImager.Tools.ToolUp().
GetSelectBoxes() [2/2]
RectangleD[] BioImager.ROI.GetSelectBoxes (double s)
It returns an array of RectangleF objects that are used to draw the selection boxes around the points of the polygon
Parameters
s the size of the select box
Returns
A list of RectangleF objects.
Definition at line 749 of file Bio.cs.
        {
            double f = s / 2;
            selectBoxs.Clear();
            for (int i = 0; i < Points.Count; i++)
            {
                selectBoxs.Add(new RectangleD((float)(Points[i].X - f), (float)(Points[i].Y - f), (float)s, (float)s));
            }
            return selectBoxs.ToArray();
        }
PointsToString()
string BioImager.ROI.PointsToString (BioImage b)
This function takes a BioImage object and returns a string of the points in the image space
Parameters
BioImage The image that the ROI is on
Returns
The points of the polygon in the image space.
Definition at line 1023 of file Bio.cs.
        {
            string pts = "";
            PointD[] ps = b.ToImageSpace(Points);
            for (int j = 0; j < ps.Length; j++)
            {
                if (j == ps.Length - 1)
                    pts += ps[j].X.ToString() + "," + ps[j].Y.ToString();
                else
                    pts += ps[j].X.ToString() + "," + ps[j].Y.ToString() + " ";
            }
            return pts;
        }
References BioImager.BioImage.ToImageSpace().
Referenced by BioImager.BioImage.SaveOMESeries().
RemovePoints()
void BioImager.ROI.RemovePoints (int[] indexs)
It removes points from a list of points based on an array of indexes
Parameters
indexs an array of integers that represent the indexes of the points to be removed
Definition at line 972 of file Bio.cs.
        {
            List<PointD> inds = new List<PointD>();
            for (int i = 0; i < Points.Count; i++)
            {
                bool found = false;
                for (int ind = 0; ind < indexs.Length; ind++)
                {
                    if (indexs[ind] == i)
                        found = true;
                }
                if (!found)
                    inds.Add(Points[i]);
            }
            Points = inds;
            UpdateBoundingBox();
        }
References BioImager.ROI.UpdateBoundingBox().
Referenced by BioImager.Tools.ToolDown().
stringToPoints()
PointD[] BioImager.ROI.stringToPoints (string s)
It takes a string of points and returns an array of PointD objects
Parameters
s The string to convert to points.
Returns
A list of points.
Definition at line 1001 of file Bio.cs.
        {
            List<PointD> pts = new List<PointD>();
            string[] ints = s.Split(' ');
            for (int i = 0; i < ints.Length; i++)
            {
                string[] sints;
                if (s.Contains("\t"))
                    sints = ints[i].Split('\t');
                else
                    sints = ints[i].Split(',');
                double x = double.Parse(sints[0]);
                double y = double.Parse(sints[1]);
                pts.Add(new PointD(x, y));
            }
            return pts.ToArray();
        }
Referenced by BioImager.BioImage.OpenOME(), BioImager.BioImage.OpenOMEROIs(), and BioImager.BioImage.StringToROI().
ToString()
override string BioImager.ROI.ToString ()
It returns a string that contains the type of the object, the text, the width and height, and the coordinates of the object
Returns
The type of the object, the text, the width, the height, the point, and the coordinates.
Definition at line 1081 of file Bio.cs.
        {
            return type.ToString() + ", " + Text + " (" + W + ", " + H + "); " + " (" + Point.X + ", " + Point.Y + ") " + coord.ToString();
        }
UpdateBoundingBox()
void BioImager.ROI.UpdateBoundingBox ()
It takes the minimum and maximum X and Y values of the points in the shape and uses them to create a bounding box
Definition at line 1038 of file Bio.cs.
        {
            if (type == Type.Label)
            {
                if (text != "")
                {
                    System.Drawing.Size s = TextSize;
                    BoundingBox = new RectangleD(Points[0].X, Points[0].Y, s.Width, s.Height);
                }
            }
            else
            {
                PointD min = new PointD(double.MaxValue, double.MaxValue);
                PointD max = new PointD(double.MinValue, double.MinValue);
                foreach (PointD p in Points)
                {
                    if (min.X > p.X)
                        min.X = p.X;
                    if (min.Y > p.Y)
                        min.Y = p.Y;
                    if (max.X < p.X)
                        max.X = p.X;
                    if (max.Y < p.Y)
                        max.Y = p.Y;
                }
                RectangleD r = new RectangleD();
                r.X = min.X;
                r.Y = min.Y;
                r.W = max.X - min.X;
                r.H = max.Y - min.Y;
                if (r.W == 0)
                    r.W = 1;
                if (r.H == 0)
                    r.H = 1;
                BoundingBox = r;
            }
        }
Referenced by BioImager.ROI.AddPoint(), BioImager.ROI.AddPoints(), BioImager.ROI.RemovePoints(), and BioImager.ROI.UpdatePoint().
UpdatePoint()
void BioImager.ROI.UpdatePoint (PointD p, int i)
This function updates the point at the specified index
Parameters
PointD A class that contains an X and Y coordinate.
i The index of the point to update
Definition at line 894 of file Bio.cs.
        {
            if (i < Points.Count)
            {
                Points[i] = p;
            }
            UpdateBoundingBox();
        }
References BioImager.ROI.UpdateBoundingBox().
Referenced by BioImager.Tools.ToolUp().
Member Data Documentation
BoundingBox
RectangleD BioImager.ROI.BoundingBox
Definition at line 435 of file Bio.cs.
closed
bool BioImager.ROI.closed = false
Definition at line 451 of file Bio.cs.
coord
ZCT BioImager.ROI.coord
Definition at line 437 of file Bio.cs.
family
string BioImager.ROI.family = ""
Definition at line 449 of file Bio.cs.
fillColor
System.Drawing.Color BioImager.ROI.fillColor
Definition at line 439 of file Bio.cs.
font
Font BioImager.ROI.font = System.Drawing.SystemFonts.DefaultFont
Definition at line 436 of file Bio.cs.
fontSize
float BioImager.ROI.fontSize = 8
Definition at line 448 of file Bio.cs.
id
string BioImager.ROI.id = ""
Definition at line 441 of file Bio.cs.
isFilled
bool BioImager.ROI.isFilled = false
Definition at line 440 of file Bio.cs.
properties
string BioImager.ROI.properties
Definition at line 446 of file Bio.cs.
roiID
string BioImager.ROI.roiID = ""
Definition at line 442 of file Bio.cs.
roiName
string BioImager.ROI.roiName = ""
Definition at line 443 of file Bio.cs.
selectBoxSize
float BioImager.ROI.selectBoxSize = 8f static
Definition at line 424 of file Bio.cs.
selected
bool BioImager.ROI.selected = false
Definition at line 452 of file Bio.cs.
selectedPoints
List<int> BioImager.ROI.selectedPoints = new List<int>()
Definition at line 434 of file Bio.cs.
serie
int BioImager.ROI.serie = 0
Definition at line 444 of file Bio.cs.
shapeIndex
int BioImager.ROI.shapeIndex = 0
Definition at line 450 of file Bio.cs.
strokeColor
System.Drawing.Color BioImager.ROI.strokeColor
Definition at line 438 of file Bio.cs.
strokeWidth
double BioImager.ROI.strokeWidth = 1
Definition at line 447 of file Bio.cs.
type
Type BioImager.ROI.type
Definition at line 423 of file Bio.cs.
Referenced by microscope.stages.linkam._CommsInfo.view_of_info().
Property Documentation
H
double BioImager.ROI.H get set
Definition at line 408 of file Bio.cs.
        {
            get
            {
                if (type == Type.Point)
                    return strokeWidth;
                else
                    return BoundingBox.H;
            }
            set
            {
                Rect = new RectangleD(X, Y, W, value);
                Recorder.AddLine("App.AddROI(" + BioImage.ROIToString(this) + ");");
            }
        }
Point
PointD BioImager.ROI.Point get set
Definition at line 307 of file Bio.cs.
        {
            get
            {
                if (Points.Count == 0)
                    return new PointD(0, 0);
                if (type == Type.Line || type == Type.Ellipse || type == Type.Label || type == Type.Freeform)
                    return new PointD(BoundingBox.X, BoundingBox.Y);
                return Points[0];
            }
            set
            {
                if (Points.Count == 0)
                {
                    AddPoint(value);
                }
                else
                    UpdatePoint(value, 0);
                UpdateBoundingBox();
            }
        }
PointsD
List<PointD> BioImager.ROI.PointsD get
Definition at line 426 of file Bio.cs.
        {
            get
            {
                return Points;
            }
        }
PointsImage
PointD [] BioImager.ROI.PointsImage get
Definition at line 453 of file Bio.cs.
        {
            get
            {
                return ImageView.SelectedImage.ToImageSpace(PointsD);
            }
        }
Rect
RectangleD BioImager.ROI.Rect get set
Definition at line 329 of file Bio.cs.
        {
            get
            {
                if (Points.Count == 0)
                    return new RectangleD(0, 0, 0, 0);
                if (type == Type.Line || type == Type.Polyline || type == Type.Polygon || type == Type.Freeform || type == Type.Label)
                    return BoundingBox;
                if (type == Type.Rectangle || type == Type.Ellipse)
                    return new RectangleD(Points[0].X, Points[0].Y, Points[1].X - Points[0].X, Points[2].Y - Points[0].Y);
                else
                    return new RectangleD(Points[0].X, Points[0].Y, 1, 1);
            }
            set
            {
                if (type == Type.Line || type == Type.Polyline || type == Type.Polygon || type == Type.Freeform)
                {
                    BoundingBox = value;
                }
                else
                if (Points.Count < 4 && (type == Type.Rectangle || type == Type.Ellipse))
                {
                    AddPoint(new PointD(value.X, value.Y));
                    AddPoint(new PointD(value.X + value.W, value.Y));
                    AddPoint(new PointD(value.X, value.Y + value.H));
                    AddPoint(new PointD(value.X + value.W, value.Y + value.H));
                }
                else
                if (type == Type.Rectangle || type == Type.Ellipse)
                {
                    Points[0] = new PointD(value.X, value.Y);
                    Points[1] = new PointD(value.X + value.W, value.Y);
                    Points[2] = new PointD(value.X, value.Y + value.H);
                    Points[3] = new PointD(value.X + value.W, value.Y + value.H);
                }
                UpdateBoundingBox();
            }
        }
roiMask
Mask BioImager.ROI.roiMask get set
Definition at line 537 of file Bio.cs.
{ get; set; }
Text
string BioImager.ROI.Text get set
Definition at line 515 of file Bio.cs.
        {
            get
            {
                return text;
            }
            set
            {
                text = value;
                if (type == Type.Label)
                {
                    UpdateBoundingBox();
                }
            }
        }
TextSize
System.Drawing.Size BioImager.ROI.TextSize get
Definition at line 530 of file Bio.cs.
        {
            get
            {
                return System.Windows.Forms.TextRenderer.MeasureText(text, font);
            }
        }
W
double BioImager.ROI.W get set
Definition at line 393 of file Bio.cs.
        {
            get
            {
                if (type == Type.Point)
                    return strokeWidth;
                else
                    return BoundingBox.W;
            }
            set
            {
                Rect = new RectangleD(X, Y, value, H);
                Recorder.AddLine("App.AddROI(" + BioImage.ROIToString(this) + ");");
            }
        }
X
double BioImager.ROI.X get set
Definition at line 368 of file Bio.cs.
        {
            get
            {
                return Point.X;
            }
            set
            {
                Rect = new RectangleD(value, Y, W, H);
                Recorder.AddLine("App.AddROI(" + BioImage.ROIToString(this) + ");");
            }
        }
Y
double BioImager.ROI.Y get set
Definition at line 381 of file Bio.cs.
        {
            get
            {
                return Point.Y;
            }
            set
            {
                Rect = new RectangleD(X, value, W, H);
                Recorder.AddLine("App.AddROI(" + BioImage.ROIToString(this) + ");");
            }
        }
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/Source/Bio.cs