BioImager: microscope.cameras.pvcam.PVStringParam Class Reference
microscope.cameras.pvcam.PVStringParam Class Reference
Public Member Functions
def set_value (self, new_value)
def current (self)
def values (self)
Public Member Functions inherited from microscope.cameras.pvcam.PVParam
def __init__ (self, camera, param_id)
def set_value (self, new_value)
def access (self)
def available (self)
def count (self)
def values (self)
def current (self)
Additional Inherited Members
Static Public Member Functions inherited from microscope.cameras.pvcam.PVParam
def factory (camera, param_id)
Public Attributes inherited from microscope.cameras.pvcam.PVParam
cam
param_id
name
dtype
Detailed Description
PVParam subclass for strings
Definition at line 1383 of file pvcam.py.
Member Function Documentation
current()
def microscope.cameras.pvcam.PVStringParam.current (self)
Return the current (or cached) string parameter value.
Reimplemented from microscope.cameras.pvcam.PVParam.
Definition at line 1393 of file pvcam.py.
    def current(self):
        """Return the current (or cached) string parameter value."""
        return self._query().decode()
References microscope.cameras.pvcam.PVParam._query().
set_value()
def microscope.cameras.pvcam.PVStringParam.set_value (self, new_value)
Set a string parameter value
Reimplemented from microscope.cameras.pvcam.PVParam.
Definition at line 1386 of file pvcam.py.
    def set_value(self, new_value):
        """Set a string parameter value"""
        if hasattr(new_value, "encode"):
            new_value = new_value.encode()
        super().set_value(new_value)
References microscope.cameras.pvcam.PVStringParam.set_value().
Referenced by microscope.stages.linkam._LinkamMDSMixin.move_to(), microscope.stages.linkam.LinkamCMS.refill_chamber(), microscope.stages.linkam.LinkamCMS.refill_dewar(), microscope.stages.linkam.LinkamCMS.set_condensor(), microscope.stages.linkam.LinkamCMS.set_light(), and microscope.cameras.pvcam.PVStringParam.set_value().
values()
def microscope.cameras.pvcam.PVStringParam.values (self)
Get allowable string length.
Reimplemented from microscope.cameras.pvcam.PVParam.
Definition at line 1398 of file pvcam.py.
    def values(self):
        """Get allowable string length."""
        values = _length_map[self.param_id] or 0
        return values
References microscope.cameras.pvcam.PVParam.param_id.
Referenced by microscope.cameras.pvcam.PVEnumParam.set_value().
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/PythonMicroscope/microscope/cameras/pvcam.py