BioImager: BioImager.Focus Class Reference
BioImager.Focus Class Reference
Public Member Functions
void SetFocus (double f)
double GetFocus ()
double GetFocus (bool update)
PointD GetSWLimit ()
void SetSWLimit (double xd, double yd)
Static Public Attributes
static double upperLimit
static double lowerLimit
Detailed Description
Definition at line 243 of file Microscope.cs.
Constructor & Destructor Documentation
Focus()
BioImager.Focus.Focus ()
Definition at line 248 of file Microscope.cs.
        {
        }
Member Function Documentation
GetFocus() [1/2]
double BioImager.Focus.GetFocus ()
This function returns the z-axis position
Returns
The z-axis position of the microscope.
Definition at line 291 of file Microscope.cs.
        {
            return GetFocus(false);
        }
References BioImager.Focus.GetFocus().
Referenced by BioImager.Focus.GetFocus().
GetFocus() [2/2]
double BioImager.Focus.GetFocus (bool update)
If the microscope is a Prior, get the Z position from the SDK. If it's a MTB, get the Z position from the MTB SDK. If it's a PMicroscope, get the Z position from the PMicroscope SDK. If it's a custom microscope, get the Z position from the custom SDK
Parameters
update boolean, if true, the focus is updated from the microscope
Returns
The z position of the microscope.
Definition at line 303 of file Microscope.cs.
        {
            if (Properties.Settings.Default.PMicroscope)
            {
                Point3D p;
                Microscope.pMicroscope.GetPosition3D(out p, update);
                return p.Z;
            }
            else if(Properties.Settings.Default.PycroManager)
            {
                Point3D p;
                PycroManager.GetPosition3D(out p, update);
                return p.Z;
            }
            if (Properties.Settings.Default.LibPath.Contains("MTB"))
            {
                BioImager.MicroscopeConsole.Command com = BioImager.MicroscopeConsole.RunCommand
                    (new BioImager.MicroscopeConsole.Command(BioImager.MicroscopeConsole.Command.Type.GetFocus, null));
                return com.doubles[0];
            }
            if (Properties.Settings.Default.LibPath.Contains("Prio"))
            {
                return Microscope.sdk.GetZ();
            }
            if(Automation.Properties.ContainsKey("GetFocus"))
            {
                return (double)Automation.GetProperty("GetFocus");
            }
            return z;
        }
References BioImager.Automation.GetProperty().
GetSWLimit()
PointD BioImager.Focus.GetSWLimit ()
It gets the lower and upper limits of the focus axis
Returns
The return value is a PointD object.
Definition at line 337 of file Microscope.cs.
        {
            if (Properties.Settings.Default.LibPath.Contains("MTB"))
            {
                BioImager.MicroscopeConsole.Command com = BioImager.MicroscopeConsole.RunCommand(
                    new BioImager.MicroscopeConsole.Command(BioImager.MicroscopeConsole.Command.Type.GetStageSWLimit, null));
                upperLimit = com.doubles[0];
                lowerLimit = com.doubles[1];
                return new PointD(upperLimit,lowerLimit);
            }
            return new PointD(lowerLimit, upperLimit);
        }
SetFocus()
void BioImager.Focus.SetFocus (double f)
Sets the z-axis based on microscope configuration.
Parameters
f the focus value
Definition at line 256 of file Microscope.cs.
        {
            if (Recorder.recordMicroscope)
                Recorder.AddLine("Microscope.Focus.SetFocus(" + f + ");");
            if (Properties.Settings.Default.PMicroscope)
            {
                PointD p = Microscope.Stage.GetPosition(true);
                Microscope.pMicroscope.SetPosition(new Point3D(p.X,p.Y,f));
            }
            else
            if (Properties.Settings.Default.PycroManager)
            {
                PointD p = Microscope.Stage.GetPosition(true);
                PycroManager.SetPosition(new Point3D(p.X, p.Y, f));
            }
            else
            if (Properties.Settings.Default.LibPath.Contains("MTB"))
            {
                BioImager.MicroscopeConsole.RunCommand(
                    new BioImager.MicroscopeConsole.Command(BioImager.MicroscopeConsole.Command.Type.SetFocus,new double[] { f}));
                z = f;
            }
            else if (Properties.Settings.Default.LibPath.Contains("Prio"))
            {
                Microscope.sdk.SetZ(f);
            }
            if (Automation.Properties.ContainsKey("SetFocus"))
            {
                Automation.SetProperty("SetFocus", f.ToString());
            }
        }
References BioImager.Automation.SetProperty().
SetSWLimit()
void BioImager.Focus.SetSWLimit (double xd, double yd)
The function takes two double values, xd and yd, and sets the upper and lower limits of the focus axis
Parameters
xd the upper limit of the focus
yd the lower limit of the focus
Definition at line 355 of file Microscope.cs.
        {
            if (Properties.Settings.Default.LibPath.Contains("MTB"))
            {
                BioImager.MicroscopeConsole.RunCommand(
                   new BioImager.MicroscopeConsole.Command(BioImager.MicroscopeConsole.Command.Type.SetFocusSWLimit,
                   new double[] { xd, yd }));
            }
            upperLimit = xd;
            lowerLimit = yd;
            if (Recorder.recordMicroscope)
                Recorder.AddLine("Microscope.Focus.SetSWLimit(" + xd + "," + yd + ");");
        }
Member Data Documentation
lowerLimit
double BioImager.Focus.lowerLimit static
Definition at line 246 of file Microscope.cs.
upperLimit
double BioImager.Focus.upperLimit static
Definition at line 245 of file Microscope.cs.
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/Source/Microscope.cs