BioImager: BioImager.App Class Reference
BioImager.App Class Reference
Static Public Member Functions
static void Initialize ()
Initialize() is a function that initializes the BioImager UI.
static void Hide ()
Hide() hides all the tools.
static List< ToolStripMenuItem > GetMenuItems ()
static List< ToolStripMenuItem > GetContextItems ()
static ToolStripItem GetMenuItemFromPath (string s, Function f)
static ToolStripItem GetContextMenuItemFromPath (string s, Function f)
static ToolStripItem GetMenuItemFromPath (string s)
static ToolStripItem GetContextMenuItemFromPath (string s)
static void AddMenu (string menu, Function f)
static void AddContextMenu (string menu, Function f)
static void AddMenu (string menu)
static void AddContextMenu (string menu)
static void AddROI (string an)
Static Public Attributes
static ROIManager manager = null
static ChannelsTool channelsTool = null
static TabsView tabsView = null
static NodeView nodeView = null
static Scripting runner = null
static Recorder recorder = null
static Imager imager = null
static Tools tools = null
static StackTools stackTools = null
static ImageView viewer = null
static StageTool stage = null
static Series seriesTool = null
static Recordings recordings = null
static Automation automation = null
static MicroscopeSetup setup = null
static CellImager cellImager = null
static SlideImager slideImager = null
static BioConsole console = null
static Light lightTool = null
static Library lib = null
static List< string > recent = new List<string>()
Properties
static BioImage Image [get]
static List< Channel > Channels [get]
static List< ROI > Annotations [get]
Detailed Description
Definition at line 12 of file App.cs.
Member Function Documentation
AddContextMenu() [1/2]
static void BioImager.App.AddContextMenu (string menu) static
It takes a string and a function and adds a context menu item to the context menu
Parameters
menu The path to the menu item.
Function The function that will be called when the menu item is clicked.
Definition at line 393 of file App.cs.
        {
            GetContextMenuItemFromPath(menu);
        }
References BioImager.App.GetContextMenuItemFromPath().
AddContextMenu() [2/2]
static void BioImager.App.AddContextMenu (string menu, Function f) static
It takes a string and a function and adds a context menu item to the context menu
Parameters
menu The path to the menu item.
Function The function that will be called when the menu item is clicked.
Definition at line 375 of file App.cs.
        {
            GetContextMenuItemFromPath(menu, f);
        }
References BioImager.App.GetContextMenuItemFromPath().
Referenced by BioImager.Function.Initialize().
AddMenu() [1/2]
static void BioImager.App.AddMenu (string menu) static
It takes a string and a function and adds the function to the menu item specified by the string
Parameters
menu The menu path to add the menu item to.
Function The function that will be called when the menu item is clicked.
Definition at line 385 of file App.cs.
        {
            GetMenuItemFromPath(menu);
        }
References BioImager.App.GetMenuItemFromPath().
AddMenu() [2/2]
static void BioImager.App.AddMenu (string menu, Function f) static
It takes a string and a function and adds the function to the menu item specified by the string
Parameters
menu The menu path to add the menu item to.
Function The function that will be called when the menu item is clicked.
Definition at line 367 of file App.cs.
        {
            GetMenuItemFromPath(menu, f);
        }
References BioImager.App.GetMenuItemFromPath().
Referenced by BioImager.Function.Initialize().
AddROI()
static void BioImager.App.AddROI (string an) static
It takes a string, converts it to a ROI, and adds it to the list of ROIs
Parameters
an the string representation of the ROI
Definition at line 433 of file App.cs.
        {
            Annotations.Add(BioImage.StringToROI(an));
            Recorder.AddLine("App.AddROI(" + '"' + an + "'" + ");");
        }
References BioImager.BioImage.StringToROI().
GetContextItems()
static List< ToolStripMenuItem > BioImager.App.GetContextItems () static
It takes the context menu of the viewer and returns a list of all the items in the menu
Returns
A list of ToolStripMenuItems
Definition at line 136 of file App.cs.
        {
            List<ToolStripMenuItem> allItems = new List<ToolStripMenuItem>();
            foreach (ToolStripMenuItem toolItem in viewer.ViewContextMenu.Items)
            {
                allItems.Add(toolItem);
                allItems.AddRange(GetItems(toolItem));
            }
            return allItems;
        }
References BioImager.ImageView.ViewContextMenu.
Referenced by BioImager.App.GetContextMenuItemFromPath().
GetContextMenuItemFromPath() [1/2]
static ToolStripItem BioImager.App.GetContextMenuItemFromPath (string s) static
It takes a string and a function, and adds the function to the context menu at the location specified by the string
Parameters
s The path to the item.
Function
Returns
A ToolStripItem
Definition at line 315 of file App.cs.
        {
            if (s == "" || s == null)
                return null;
            string[] sts = s.Split('/');
        start:
            List<ToolStripMenuItem> allItems = GetContextItems();
            //Find path or create it.
            bool found = false;
            ToolStripMenuItem item = null;
            for (int t = 0; t < sts.Length; t++)
            {
                found = false;
                for (int i = 0; i < allItems.Count; i++)
                {
                    if (allItems[i].Text == sts[t])
                    {
                        item = allItems[i];
                        found = true;
                        if (t == sts.Length - 1)
                            return allItems[i];
                    }
                }
                if (!found)
                {
                    if (t == 0)
                    {
                        viewer.ViewContextMenu.Items.Add(sts[t]);
                        goto start;
                    }
                    else if (t > 0 && t < sts.Length)
                    {
                        ToolStripMenuItem itm = new ToolStripMenuItem();
                        itm.Name = Path.GetFileName(s);
                        item.DropDownItems.Add(Path.GetFileName(s), null, ItemClicked);
                        return item;
                    }
                    else
                    {
                        item.DropDownItems.Add(sts[t]);
                    }
                }
            }
            return item;
        }
References BioImager.App.GetContextItems(), and BioImager.ImageView.ViewContextMenu.
GetContextMenuItemFromPath() [2/2]
static ToolStripItem BioImager.App.GetContextMenuItemFromPath (string s, Function f) static
It takes a string and a function, and adds the function to the context menu at the location specified by the string
Parameters
s The path to the item.
Function
Returns
A ToolStripItem
Definition at line 207 of file App.cs.
        {
            if (s == "" || s == null)
                return null;
            string[] sts = s.Split('/');
        start:
            List<ToolStripMenuItem> allItems = GetContextItems();
            //Find path or create it.
            bool found = false;
            ToolStripMenuItem item = null;
            for (int t = 0; t < sts.Length; t++)
            {
                found = false;
                for (int i = 0; i < allItems.Count; i++)
                {
                    if (allItems[i].Text == sts[t])
                    {
                        item = allItems[i];
                        found = true;
                        if (t == sts.Length - 1)
                            return allItems[i];
                    }
                }
                if (!found)
                {
                    if (t == 0)
                    {
                        viewer.ViewContextMenu.Items.Add(sts[t]);
                        goto start;
                    }
                    else if (t > 0 && t < sts.Length)
                    {
                        ToolStripMenuItem itm = new ToolStripMenuItem();
                        itm.Tag = f;
                        itm.Name = f.Name;
                        item.DropDownItems.Add(f.Name, null, ItemClicked);
                        return item;
                    }
                    else
                    {
                        item.DropDownItems.Add(sts[t]);
                    }
                }
            }
            return item;
        }
References BioImager.App.GetContextItems(), and BioImager.ImageView.ViewContextMenu.
Referenced by BioImager.App.AddContextMenu().
GetMenuItemFromPath() [1/2]
static ToolStripItem BioImager.App.GetMenuItemFromPath (string s) static
It takes a string and a function, and adds the function to the menu item specified by the string
Parameters
s The path to the menu item.
Function
Returns
A ToolStripItem
Definition at line 262 of file App.cs.
        {
            if (s == "" || s == null)
                return null;
            string[] sts = s.Split('/');
        start:
            List<ToolStripMenuItem> allItems = GetMenuItems();
            //Find path or create it.
            bool found = false;
            ToolStripMenuItem item = null;
            for (int t = 0; t < sts.Length; t++)
            {
                found = false;
                for (int i = 0; i < allItems.Count; i++)
                {
                    if (allItems[i].Text == sts[t])
                    {
                        item = allItems[i];
                        found = true;
                        if (t == sts.Length - 1)
                            return allItems[i];
                    }
                }
                if (!found)
                {
                    if (t == 0)
                    {
                        tabsView.MainMenuStrip.Items.Add(sts[t]);
                        goto start;
                    }
                    else if (t > 0 && t < sts.Length)
                    {
                        ToolStripMenuItem itm = new ToolStripMenuItem();
                        itm.Text = Path.GetFileName(s);
                        item.DropDownItems.Add(Path.GetFileName(s), null, ItemClicked);
                        return item;
                    }
                    else
                    {
                        item.DropDownItems.Add(sts[t]);
                    }
                }
            }
            return item;
        }
References BioImager.App.GetMenuItems().
GetMenuItemFromPath() [2/2]
static ToolStripItem BioImager.App.GetMenuItemFromPath (string s, Function f) static
It takes a string and a function, and adds the function to the menu item specified by the string
Parameters
s The path to the menu item.
Function
Returns
A ToolStripItem
Definition at line 153 of file App.cs.
        {
            if (s == "" || s == null)
                return null;
            string[] sts = s.Split('/');
        start:
            List<ToolStripMenuItem> allItems = GetMenuItems();
            //Find path or create it.
            bool found = false;
            ToolStripMenuItem item = null;
            for (int t = 0; t < sts.Length; t++)
            {
                found = false;
                for (int i = 0; i < allItems.Count; i++)
                {
                    if (allItems[i].Text == sts[t])
                    {
                        item = allItems[i];
                        found = true;
                        if (t == sts.Length - 1)
                            return allItems[i];
                    }
                }
                if (!found)
                {
                    if(t == 0)
                    {
                        tabsView.MainMenuStrip.Items.Add(sts[t]);
                        goto start;
                    }
                    else if(t > 0 && t < sts.Length)
                    {
                        ToolStripMenuItem itm = new ToolStripMenuItem();
                        itm.Tag = f;
                        itm.Name = f.Name;
                        item.DropDownItems.Add(f.Name, null, ItemClicked);
                        return item;
                    }
                    else
                    {
                        item.DropDownItems.Add(sts[t]);
                    }
                }
            }
            return item;
        }
References BioImager.App.GetMenuItems().
Referenced by BioImager.App.AddMenu().
GetMenuItems()
static List< ToolStripMenuItem > BioImager.App.GetMenuItems () static
It takes a menu strip and returns a list of all the menu items in the menu strip
Returns
A list of ToolStripMenuItems
Definition at line 123 of file App.cs.
        {
            List<ToolStripMenuItem> allItems = new List<ToolStripMenuItem>();
            foreach (ToolStripMenuItem toolItem in tabsView.MainMenuStrip.Items)
            {
                allItems.Add(toolItem);
                allItems.AddRange(GetItems(toolItem));
            }
            return allItems;
        }
Referenced by BioImager.App.GetMenuItemFromPath().
Hide()
static void BioImager.App.Hide () static
Hide() hides all the tools.
Definition at line 90 of file App.cs.
        {
            tools.Hide();
            stackTools.Hide();
            manager.Hide();
            runner.Hide();
            recorder.Hide();
            seriesTool.Hide();
            recordings.Hide();
            console.Hide();
        }
Initialize()
static void BioImager.App.Initialize () static
Initialize() is a function that initializes the BioImager UI.
Definition at line 56 of file App.cs.
        {
            BioImage.Initialize();
            do
            {
                Thread.Sleep(100);
            } while (!BioImage.Initialized);
            imager = new Imager();
            Microscope.Initialize();
            ImageJ.Initialize();
            setup = new MicroscopeSetup();
            stage = new StageTool();
            cellImager = new CellImager();
            stackTools = new StackTools();
            tools = new Tools();
            manager = new ROIManager();
            runner = new Scripting();
            recorder = new Recorder();
            seriesTool = new Series();
            recordings = new Recordings();
            automation = new Automation();
            slideImager = new SlideImager();
            if (!Properties.Settings.Default.PycroManager && !Properties.Settings.Default.PMicroscope)
            {
                lightTool = new Light();
            }
            lib = new Library();
            console = new BioConsole();
            imager.Show();
            //ImageJ.Initialize(Properties.Settings.Default.ImageJPath);
        }
References BioImager.BioImage.Initialize(), and BioImager.ImageJ.Initialize().
Member Data Documentation
automation
Automation BioImager.App.automation = null static
Definition at line 27 of file App.cs.
cellImager
CellImager BioImager.App.cellImager = null static
Definition at line 29 of file App.cs.
channelsTool
ChannelsTool BioImager.App.channelsTool = null static
Definition at line 15 of file App.cs.
console
BioConsole BioImager.App.console = null static
Definition at line 31 of file App.cs.
imager
Imager BioImager.App.imager = null static
Definition at line 20 of file App.cs.
lib
Library BioImager.App.lib = null static
Definition at line 33 of file App.cs.
lightTool
Light BioImager.App.lightTool = null static
Definition at line 32 of file App.cs.
manager
ROIManager BioImager.App.manager = null static
Definition at line 14 of file App.cs.
nodeView
NodeView BioImager.App.nodeView = null static
Definition at line 17 of file App.cs.
recent
List<string> BioImager.App.recent = new List<string>() static
Definition at line 34 of file App.cs.
recorder
Recorder BioImager.App.recorder = null static
Definition at line 19 of file App.cs.
recordings
Recordings BioImager.App.recordings = null static
Definition at line 26 of file App.cs.
runner
Scripting BioImager.App.runner = null static
Definition at line 18 of file App.cs.
seriesTool
Series BioImager.App.seriesTool = null static
Definition at line 25 of file App.cs.
setup
MicroscopeSetup BioImager.App.setup = null static
Definition at line 28 of file App.cs.
slideImager
SlideImager BioImager.App.slideImager = null static
Definition at line 30 of file App.cs.
stackTools
StackTools BioImager.App.stackTools = null static
Definition at line 22 of file App.cs.
stage
StageTool BioImager.App.stage = null static
Definition at line 24 of file App.cs.
tabsView
TabsView BioImager.App.tabsView = null static
Definition at line 16 of file App.cs.
tools
Tools BioImager.App.tools = null static
Definition at line 21 of file App.cs.
viewer
ImageView BioImager.App.viewer = null static
Definition at line 23 of file App.cs.
Property Documentation
Annotations
List<ROI> BioImager.App.Annotations static get
Definition at line 51 of file App.cs.
        {
            get { return Image.Annotations; }
        }
Channels
List<Channel> BioImager.App.Channels static get
Definition at line 46 of file App.cs.
        {
            get { return Image.Channels; }
        }
Image
BioImage BioImager.App.Image static get
Definition at line 37 of file App.cs.
        {
            get
            {
                if (ImageView.SelectedImage == null)
                    return tabsView.Image;
                return ImageView.SelectedImage;
            }
        }
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/Source/App.cs