var hierarchy =
[
    [ "Gtk.Dialog", null, [
      [ "BioGTK.ApplyFilter", "class_bio_g_t_k_1_1_apply_filter.html", null ],
      [ "BioGTK.ColorTool", "class_bio_g_t_k_1_1_color_tool.html", null ],
      [ "BioGTK.ComboPicker", "class_bio_g_t_k_1_1_combo_picker.html", null ],
      [ "BioGTK.NumberPicker", "class_bio_g_t_k_1_1_number_picker.html", null ],
      [ "BioGTK.Progress", "class_bio_g_t_k_1_1_progress.html", null ],
      [ "BioGTK.Resolutions", "class_bio_g_t_k_1_1_resolutions.html", null ],
      [ "BioGTK.TextInput", "class_bio_g_t_k_1_1_text_input.html", null ],
      [ "BioGTK.Tolerance", "class_bio_g_t_k_1_1_tolerance.html", null ],
      [ "BioGTK.Updater", "class_bio_g_t_k_1_1_updater.html", null ]
    ] ],
    [ "BioGTK.Focus", "class_bio_g_t_k_1_1_focus.html", null ],
    [ "BioGTK.Function", "class_bio_g_t_k_1_1_function.html", null ],
    [ "BioGTK.QuPath.GeoJsonFeature", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_feature.html", null ],
    [ "BioGTK.QuPath.GeoJsonFeatureCollection", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_feature_collection.html", null ],
    [ "BioGTK.QuPath.GeoJsonGeometry", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_geometry.html", null ],
    [ "BioGTK.QuPath.GeoJsonLineString", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_line_string.html", null ],
    [ "BioGTK.QuPath.GeoJsonGeometry.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_geometry_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonLineString.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_line_string_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonPoint.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_point_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonPolygon.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_polygon_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonPoint", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_point.html", null ],
    [ "BioGTK.QuPath.GeoJsonPolygon", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_polygon.html", null ],
    [ "BioGTK.Updater.GitHubFile", "class_bio_g_t_k_1_1_updater_1_1_git_hub_file.html", null ],
    [ "BioGTK.Plugin.IPlugin", "interface_bio_g_t_k_1_1_plugin_1_1_i_plugin.html", null ],
    [ "BioGTK.Updater.GitHubFile.Links", "class_bio_g_t_k_1_1_updater_1_1_git_hub_file_1_1_links.html", null ],
    [ "BioGTK.ML.ML.Model", "class_bio_g_t_k_1_1_m_l_1_1_m_l_1_1_model.html", null ],
    [ "BioGTK.Objectives.Objective", "class_bio_g_t_k_1_1_objectives_1_1_objective.html", null ],
    [ "BioGTK.Objectives", "class_bio_g_t_k_1_1_objectives.html", null ],
    [ "BioGTK.Plugin", "class_bio_g_t_k_1_1_plugin.html", null ],
    [ "BioGTK.QuPath.Properties", "class_bio_g_t_k_1_1_qu_path_1_1_properties.html", null ],
    [ "BioGTK.QuPath", "class_bio_g_t_k_1_1_qu_path.html", null ],
    [ "BioGTK.RLShutter", "class_bio_g_t_k_1_1_r_l_shutter.html", null ],
    [ "BioGTK.Scripting.Script", "class_bio_g_t_k_1_1_scripting_1_1_script.html", null ],
    [ "BioGTK.Stage", "class_bio_g_t_k_1_1_stage.html", null ],
    [ "BioGTK.Scripting.State", "class_bio_g_t_k_1_1_scripting_1_1_state.html", null ],
    [ "BioGTK.TLShutter", "class_bio_g_t_k_1_1_t_l_shutter.html", null ],
    [ "BioGTK.Tools.Tool", "class_bio_g_t_k_1_1_tools_1_1_tool.html", null ],
    [ "Gtk.Window", null, [
      [ "BioGTK.About", "class_bio_g_t_k_1_1_about.html", null ],
      [ "BioGTK.BioConsole", "class_bio_g_t_k_1_1_bio_console.html", null ],
      [ "BioGTK.ChannelsTool", "class_bio_g_t_k_1_1_channels_tool.html", null ],
      [ "BioGTK.FiltersView", "class_bio_g_t_k_1_1_filters_view.html", null ],
      [ "BioGTK.Functions", "class_bio_g_t_k_1_1_functions.html", null ],
      [ "BioGTK.HistogramControl", "class_bio_g_t_k_1_1_histogram_control.html", null ],
      [ "BioGTK.ImageView", "class_bio_g_t_k_1_1_image_view.html", null ],
      [ "BioGTK.NodeView", "class_bio_g_t_k_1_1_node_view.html", null ],
      [ "BioGTK.PlateTool", "class_bio_g_t_k_1_1_plate_tool.html", null ],
      [ "BioGTK.Play", "class_bio_g_t_k_1_1_play.html", null ],
      [ "BioGTK.Plot", "class_bio_g_t_k_1_1_plot.html", null ],
      [ "BioGTK.Recorder", "class_bio_g_t_k_1_1_recorder.html", null ],
      [ "BioGTK.Scripting", "class_bio_g_t_k_1_1_scripting.html", null ],
      [ "BioGTK.Search", "class_bio_g_t_k_1_1_search.html", null ],
      [ "BioGTK.SetTool", "class_bio_g_t_k_1_1_set_tool.html", null ],
      [ "BioGTK.StackTools", "class_bio_g_t_k_1_1_stack_tools.html", null ],
      [ "BioGTK.TabsView", "class_bio_g_t_k_1_1_tabs_view.html", null ],
      [ "BioGTK.Tools", "class_bio_g_t_k_1_1_tools.html", null ]
    ] ],
    [ "Window", null, [
      [ "Bio.MagicSelect", "class_bio_1_1_magic_select.html", null ],
      [ "Bio.ROIManager", "class_bio_1_1_r_o_i_manager.html", null ]
    ] ]
];