var hierarchy =
[
    [ "Bio.Graphics.AbstractFloodFiller", "class_bio_1_1_graphics_1_1_abstract_flood_filler.html", [
      [ "Bio.Graphics.QueueLinearFloodFiller", "class_bio_1_1_graphics_1_1_queue_linear_flood_filler.html", null ]
    ] ],
    [ "Bio.Automation.Action", "class_bio_1_1_automation_1_1_action.html", null ],
    [ "Bio.App", "class_bio_1_1_app.html", null ],
    [ "Bio.Automation", "class_bio_1_1_automation.html", null ],
    [ "Bio.Channel.ChannelInfo", "struct_bio_1_1_channel_1_1_channel_info.html", null ],
    [ "Bio.Graphics.Configuration", "class_bio_1_1_graphics_1_1_configuration.html", null ],
    [ "Bio.Graphics.DBitmap", "class_bio_1_1_graphics_1_1_d_bitmap.html", null ],
    [ "Bio.Filt", "class_bio_1_1_filt.html", null ],
    [ "Bio.Graphics.FloodFillRange", "struct_bio_1_1_graphics_1_1_flood_fill_range.html", null ],
    [ "Bio.Graphics.FloodFillRangeQueue", "class_bio_1_1_graphics_1_1_flood_fill_range_queue.html", null ],
    [ "Bio.Focus", "class_bio_1_1_focus.html", null ],
    [ "Form", null, [
      [ "Bio.About", "class_bio_1_1_about.html", null ],
      [ "Bio.ApplyFilter", "class_bio_1_1_apply_filter.html", null ],
      [ "Bio.BioConsole", "class_bio_1_1_bio_console.html", null ],
      [ "Bio.ChannelsTool", "class_bio_1_1_channels_tool.html", null ],
      [ "Bio.ColorTool", "class_bio_1_1_color_tool.html", null ],
      [ "Bio.Filter", "class_bio_1_1_filter.html", null ],
      [ "Bio.FunctionForm", "class_bio_1_1_function_form.html", null ],
      [ "Bio.Graphics.FloodTool", "class_bio_1_1_graphics_1_1_flood_tool.html", null ],
      [ "Bio.Graphics.PenTool", "class_bio_1_1_graphics_1_1_pen_tool.html", null ],
      [ "Bio.ImageWindow", "class_bio_1_1_image_window.html", null ],
      [ "Bio.ImagesToStack", "class_bio_1_1_images_to_stack.html", null ],
      [ "Bio.Library", "class_bio_1_1_library.html", null ],
      [ "Bio.MagicSelect", "class_bio_1_1_magic_select.html", null ],
      [ "Bio.NodeView", "class_bio_1_1_node_view.html", null ],
      [ "Bio.OpenInTab", "class_bio_1_1_open_in_tab.html", null ],
      [ "Bio.PlaySpeed", "class_bio_1_1_play_speed.html", null ],
      [ "Bio.Progress", "class_bio_1_1_progress.html", null ],
      [ "Bio.ROIManager", "class_bio_1_1_r_o_i_manager.html", null ],
      [ "Bio.RangeTool", "class_bio_1_1_range_tool.html", null ],
      [ "Bio.Recorder", "class_bio_1_1_recorder.html", null ],
      [ "Bio.Recordings", "class_bio_1_1_recordings.html", null ],
      [ "Bio.Resolutions", "class_bio_1_1_resolutions.html", null ],
      [ "Bio.Scripting", "class_bio_1_1_scripting.html", null ],
      [ "Bio.SelectRecording", "class_bio_1_1_select_recording.html", null ],
      [ "Bio.Series", "class_bio_1_1_series.html", null ],
      [ "Bio.SetTool", "class_bio_1_1_set_tool.html", null ],
      [ "Bio.Source.ImagesView", "class_bio_1_1_source_1_1_images_view.html", null ],
      [ "Bio.StackTools", "class_bio_1_1_stack_tools.html", null ],
      [ "Bio.TabsView", "class_bio_1_1_tabs_view.html", null ],
      [ "Bio.TextInput", "class_bio_1_1_text_input.html", null ],
      [ "Bio.Tools", "class_bio_1_1_tools.html", null ],
      [ "Bio.XMLView", "class_bio_1_1_x_m_l_view.html", null ]
    ] ],
    [ "Bio.Function", "class_bio_1_1_function.html", null ],
    [ "IDisposable", null, [
      [ "Bio.BioImage", "class_bio_1_1_bio_image.html", null ],
      [ "Bio.BufferInfo", "class_bio_1_1_buffer_info.html", null ],
      [ "Bio.Channel", "class_bio_1_1_channel.html", null ],
      [ "Bio.ColorS", "struct_bio_1_1_color_s.html", null ],
      [ "Bio.Graphics.Direct2D", "class_bio_1_1_graphics_1_1_direct2_d.html", null ],
      [ "Bio.Graphics.Graphics", "class_bio_1_1_graphics_1_1_graphics.html", null ],
      [ "Bio.Graphics.Pen", "struct_bio_1_1_graphics_1_1_pen.html", null ],
      [ "Bio.ImageView", "class_bio_1_1_image_view.html", null ]
    ] ],
    [ "Bio.ImageInfo", "class_bio_1_1_image_info.html", null ],
    [ "Bio.ImageJ", "class_bio_1_1_image_j.html", null ],
    [ "Bio.BioImage.ImageJDesc", "class_bio_1_1_bio_image_1_1_image_j_desc.html", null ],
    [ "Bio.Lib", "class_bio_1_1_lib.html", null ],
    [ "Bio.MouseOperations", "class_bio_1_1_mouse_operations.html", null ],
    [ "Bio.MouseOperations.MousePoint", "struct_bio_1_1_mouse_operations_1_1_mouse_point.html", null ],
    [ "Bio.Filter.Node", "class_bio_1_1_filter_1_1_node.html", null ],
    [ "Bio.NodeView.Node", "class_bio_1_1_node_view_1_1_node.html", null ],
    [ "Bio.Recordings.Node", "class_bio_1_1_recordings_1_1_node.html", null ],
    [ "Bio.Lib.ObjectInfo", "class_bio_1_1_lib_1_1_object_info.html", null ],
    [ "Bio.Objectives.Objective", "class_bio_1_1_objectives_1_1_objective.html", null ],
    [ "Bio.Objectives", "class_bio_1_1_objectives.html", null ],
    [ "Bio.Plane", "class_bio_1_1_plane.html", null ],
    [ "Bio.Point3D", "struct_bio_1_1_point3_d.html", null ],
    [ "Bio.PointD", "struct_bio_1_1_point_d.html", null ],
    [ "Bio.Automation.Recording", "class_bio_1_1_automation_1_1_recording.html", null ],
    [ "Bio.Win32.Rect", "struct_bio_1_1_win32_1_1_rect.html", null ],
    [ "Bio.RectangleD", "struct_bio_1_1_rectangle_d.html", null ],
    [ "Bio.Resolution", "struct_bio_1_1_resolution.html", null ],
    [ "RichTextBox", null, [
      [ "Bio.CodeView.ScrollTextBox", "class_bio_1_1_code_view_1_1_scroll_text_box.html", null ]
    ] ],
    [ "Bio.RLShutter", "class_bio_1_1_r_l_shutter.html", null ],
    [ "Bio.ROI", "class_bio_1_1_r_o_i.html", null ],
    [ "Bio.Scripting.Script", "class_bio_1_1_scripting_1_1_script.html", null ],
    [ "Bio.Stage", "class_bio_1_1_stage.html", null ],
    [ "Bio.Scripting.State", "class_bio_1_1_scripting_1_1_state.html", null ],
    [ "Bio.Statistics", "class_bio_1_1_statistics.html", null ],
    [ "Bio.TLShutter", "class_bio_1_1_t_l_shutter.html", null ],
    [ "Bio.Tools.Tool", "class_bio_1_1_tools_1_1_tool.html", null ],
    [ "Bio.Lib.TypeInfo", "class_bio_1_1_lib_1_1_type_info.html", null ],
    [ "System.Windows.Forms.UserControl", null, [
      [ "Bio.XmlTreeDisplay", "class_bio_1_1_xml_tree_display.html", null ]
    ] ],
    [ "UserControl", null, [
      [ "Bio.CodeView", "class_bio_1_1_code_view.html", null ],
      [ "Bio.HistogramControl", "class_bio_1_1_histogram_control.html", null ],
      [ "Bio.ImageView", "class_bio_1_1_image_view.html", null ]
    ] ],
    [ "Bio.VolumeD", "struct_bio_1_1_volume_d.html", null ],
    [ "Bio.Win32", "class_bio_1_1_win32.html", null ],
    [ "Bio.ZCT", "struct_bio_1_1_z_c_t.html", null ],
    [ "Bio.ZCTXY", "struct_bio_1_1_z_c_t_x_y.html", null ]
];