BioImager: microscope.controllers.zaber._ZaberConnection Class Reference
microscope.controllers.zaber._ZaberConnection Class Reference
Public Member Functions
None __init__ (self, str port, int baudrate, float timeout)
threading.RLock lock (self)
int write (self, bytes data)
bytes readline (self, int size=-1)
Detailed Description
Wraps a serial connection with a reentrant lock.
This class is just the wrap to :class:`serial.Serial`.  The class
exposing the Zaber commands interface is
:class:`_ZaberDeviceConnection`.
.. todo: replace with microscope._utils.SharedSerial
Definition at line 112 of file zaber.py.
Constructor & Destructor Documentation
__init__()
None microscope.controllers.zaber._ZaberConnection.__init__ (self, str port, int baudrate, float timeout)
Definition at line 122 of file zaber.py.
    def __init__(self, port: str, baudrate: int, timeout: float) -> None:
        self._serial = serial.Serial(
            port=port,
            baudrate=baudrate,
            timeout=timeout,
            bytesize=serial.EIGHTBITS,
            stopbits=serial.STOPBITS_ONE,
            parity=serial.PARITY_NONE,
            xonxoff=False,
            rtscts=False,
            dsrdtr=False,
        )
        self._lock = threading.RLock()
        with self._lock:
            # The command / does nothing other than getting a response
            # from all devices in the chain.  This seems to be the
            # most innocent command we can use.
            self._serial.write(b"/\n")
            lines = self._serial.readlines()
        if not all([l.startswith(b"@") for l in lines]):
            raise RuntimeError(
                "'%s' does not respond like a Zaber device" % port
            )
Member Function Documentation
lock()
threading.RLock microscope.controllers.zaber._ZaberConnection.lock (self)
Definition at line 147 of file zaber.py.
    def lock(self) -> threading.RLock:
        return self._lock
readline()
bytes microscope.controllers.zaber._ZaberConnection.readline (self, int size = -1)
Definition at line 154 of file zaber.py.
    def readline(self, size: int = -1) -> bytes:
        with self.lock:
            return self._serial.readline(size)
Referenced by microscope.controllers.prior._ProScanIIIConnection.get_command(), microscope.stages.ludl._LudlController.get_command(), and microscope.stages.ludl._LudlController.readline().
write()
int microscope.controllers.zaber._ZaberConnection.write (self, bytes data)
Definition at line 150 of file zaber.py.
    def write(self, data: bytes) -> int:
        with self.lock:
            return self._serial.write(data)
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/PythonMicroscope/microscope/controllers/zaber.py