BioImager: BioImager.SlideImage Class Reference
BioImager.SlideImage Class Reference
openslide wrapper
Public Member Functions
SlideImage ()
ImageDimension GetLevelDimension (int level)
Get the dimensions of a level.
IEnumerable< ImageDimension > GetLevelDimensions ()
Get all level dimensions.
unsafe byte[] ReadRegion (int level, long x, long y, long width, long height)
Copy pre-multiplied BGRA data from a whole slide image.
unsafe bool TryReadRegion (int level, long x, long y, long width, long height, ZCT coord, out byte[] data)
Copy pre-multiplied BGRA data from a whole slide image.
void Close ()
void Dispose ()
async Task< byte[]> ReadRegionAsync (int level, long curLevelOffsetXPixel, long curLevelOffsetYPixel, int curTileWidth, int curTileHeight, ZCT coord)
Static Public Member Functions
static string DetectVendor (string filename)
Quickly determine whether a whole slide image is recognized.
static void Initialize (string path=null)
Add .dll directory to PATH
static SlideImage Open (BioImage b)
Open.
static double CalculateBaseFactor (int originalResolution, int lastLevelResolution, int totalLevels)
Calculates the base downsampling factor between two levels of a slide.
static List< double > GetLevelDownsamples (double baseDownsampleFactor, int totalLevels)
Calculates the downsample factors for each level of a slide.
Protected Member Functions
virtual void Dispose (bool disposing)
Dispose
Properties
BioImage BioImage [get, set]
int LevelCount [get]
Get the number of levels in the whole slide image.
ImageDimension Dimensions [get]
Get the dimensions of level 0 (the largest level). Exactly equivalent to calling GetLevelDimensions(0).
Detailed Description
openslide wrapper
Definition at line 19 of file SlideImage.cs.
Constructor & Destructor Documentation
SlideImage()
BioImager.SlideImage.SlideImage ()
Parameters
handle
isOwner close handle when disposed
Exceptions
OpenSlideException
Definition at line 49 of file SlideImage.cs.
        {
        }
Referenced by BioImager.SlideImage.Open().
Member Function Documentation
CalculateBaseFactor()
static double BioImager.SlideImage.CalculateBaseFactor (int originalResolution, int lastLevelResolution, int totalLevels) static
Calculates the base downsampling factor between two levels of a slide.
Parameters
originalDimension The dimension (width or height) of the original level.
nextLevelDimension The dimension (width or height) of the next level.
Returns
The base downsampling factor.
Definition at line 151 of file SlideImage.cs.
        {
            if (totalLevels <= 1)
            {
                throw new ArgumentException("Total levels must be greater than 1 to calculate a base factor.");
            }
            if (lastLevelResolution <= 0 || originalResolution <= 0)
            {
                throw new ArgumentException("Resolutions must be greater than 0.");
            }
            // Calculate the base downsampling factor
            double baseFactor = Math.Pow((double)originalResolution / lastLevelResolution, 1.0 / (totalLevels - 1));
            return baseFactor;
        }
Close()
void BioImager.SlideImage.Close ()
Definition at line 265 of file SlideImage.cs.
        {
        }
DetectVendor()
static string BioImager.SlideImage.DetectVendor (string filename) static
Quickly determine whether a whole slide image is recognized.
If OpenSlide recognizes the file referenced by filename , return a string identifying the slide format vendor.This is equivalent to the value of the NativeMethods.VENDOR property. Calling Open(string) on this file will return a valid OpenSlide object or an OpenSlide object in error state.
Otherwise, return null.Calling Open(string) on this file will also return null.
Parameters
filename The filename to check. On Windows, this must be in UTF-8.
Returns
An identification of the format vendor for this file, or NULL.
Definition at line 39 of file SlideImage.cs.
        {
            return filename;
        }
Dispose() [1/2]
void BioImager.SlideImage.Dispose ()
Definition at line 300 of file SlideImage.cs.
        {
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
References BioImager.SlideImage.Dispose().
Referenced by BioImager.SlideImage.Dispose().
Dispose() [2/2]
virtual void BioImager.SlideImage.Dispose (bool disposing) protected virtual
Dispose
Parameters
disposing
Definition at line 278 of file SlideImage.cs.
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                }
                Close();
                disposedValue = true;
            }
        }
GetLevelDimension()
ImageDimension BioImager.SlideImage.GetLevelDimension (int level)
Get the dimensions of a level.
Parameters
level The desired level.
Exceptions
OpenSlideException
Definition at line 127 of file SlideImage.cs.
        {
            return new ImageDimension(BioImage.Resolutions[level].SizeX, BioImage.Resolutions[level].SizeY);
        }
Referenced by BioImager.SlideImage.GetLevelDimensions().
GetLevelDimensions()
IEnumerable< ImageDimension > BioImager.SlideImage.GetLevelDimensions ()
Get all level dimensions.
Returns
Exceptions
OpenSlideException
Definition at line 137 of file SlideImage.cs.
        {
            var count = LevelCount;
            for (int i = 0; i < count; i++)
            {
                yield return GetLevelDimension(i);
            }
        }
References BioImager.SlideImage.GetLevelDimension(), and BioImager.SlideImage.LevelCount.
GetLevelDownsamples()
static List< double > BioImager.SlideImage.GetLevelDownsamples (double baseDownsampleFactor, int totalLevels) static
Calculates the downsample factors for each level of a slide.
Parameters
baseDownsampleFactor The downsample factor between each level.
totalLevels Total number of levels in the slide.
Returns
A list of downsample factors for each level.
Definition at line 173 of file SlideImage.cs.
        {
            var levelDownsamples = new List<double>();
            for (int level = 0; level < totalLevels; level++)
            {
                // Calculate the downsample factor for the current level.
                // Math.Pow is used to raise the baseDownsampleFactor to the power of the level.
                double downsampleFactorAtLevel = Math.Pow(baseDownsampleFactor, level);
                levelDownsamples.Add(downsampleFactorAtLevel);
            }
            return levelDownsamples;
        }
Initialize()
static void BioImager.SlideImage.Initialize (string path = null) static
Add .dll directory to PATH
Parameters
path
Exceptions
OpenSlideException
Definition at line 59 of file SlideImage.cs.
        {
        }
Open()
static SlideImage BioImager.SlideImage.Open (BioImage b) static
Open.
Parameters
filename
Returns
Exceptions
OpenSlideException
Definition at line 74 of file SlideImage.cs.
        {
            SlideImage im = new SlideImage();
            im.BioImage = b;
            return im;
        }
References BioImager.SlideImage.SlideImage().
Referenced by BioImager.BioImage.OpenOME().
ReadRegion()
unsafe byte[] BioImager.SlideImage.ReadRegion (int level, long x, long y, long width, long height)
Copy pre-multiplied BGRA data from a whole slide image.
Parameters
level The desired level.
x The top left x-coordinate, in the level 0 reference frame.
y The top left y-coordinate, in the level 0 reference frame.
width The width of the region. Must be non-negative.
height The height of the region. Must be non-negative.
Returns
The pixel data of this region.
Exceptions
ArgumentOutOfRangeException
Exceptions
OpenSlideException
Definition at line 225 of file SlideImage.cs.
        {
            return BioImage.GetTile(BioImage, App.viewer.GetCoordinate(), level, (int)x, (int)y, (int)width, (int)height).RGBBytes;
        }
References BioImager.ImageView.GetCoordinate(), and BioImager.BioImage.GetTile().
ReadRegionAsync()
async Task< byte[]> BioImager.SlideImage.ReadRegionAsync (int level, long curLevelOffsetXPixel, long curLevelOffsetYPixel, int curTileWidth, int curTileHeight, ZCT coord)
Definition at line 306 of file SlideImage.cs.
        {
            try
            {
                byte[] bts;
                TryReadRegion(level, curLevelOffsetXPixel, curLevelOffsetYPixel, curTileWidth, curTileHeight, coord,out bts);
                return bts;
            }
            catch (Exception e)
            {
                return null;
            }
        }
TryReadRegion()
unsafe bool BioImager.SlideImage.TryReadRegion (int level, long x, long y, long width, long height, ZCT coord, out byte[] data)
Copy pre-multiplied BGRA data from a whole slide image.
Parameters
level The desired level.
x The top left x-coordinate, in the level 0 reference frame.
y The top left y-coordinate, in the level 0 reference frame.
width The width of the region. Must be non-negative.
height The height of the region. Must be non-negative.
data The BGRA pixel data of this region.
Returns
summary> Close an OpenSlide object. /summary> remarks> No other threads may be using the object. After this call returns, the object cannot be used anymore. /remarks>
Definition at line 240 of file SlideImage.cs.
References BioImager.BioImage.GetTile().
Property Documentation
BioImage
BioImage BioImager.SlideImage.BioImage get set
Definition at line 21 of file SlideImage.cs.
{ get; set; }
Dimensions
ImageDimension BioImager.SlideImage.Dimensions get
Get the dimensions of level 0 (the largest level). Exactly equivalent to calling GetLevelDimensions(0).
Exceptions
OpenSlideException
Definition at line 107 of file SlideImage.cs.
        {
            get
            {
                if (_dimensionsRef == null)
                {
                    lock (_dimensionsSynclock)
                    {
                        if (_dimensionsRef == null)
                            _dimensionsRef = GetLevelDimension(0);
                    }
                }
                return _dimensionsRef.Value;
            }
        }
LevelCount
int BioImager.SlideImage.LevelCount get
Get the number of levels in the whole slide image.
<return>The number of levels, or -1 if an error occurred.</return>
Exceptions
OpenSlideException
Definition at line 86 of file SlideImage.cs.
        {
            get
            {
                if (BioImage.MacroResolution.HasValue)
                {
                    return BioImage.Resolutions.Count - 2;
                }
                else
                    return BioImage.Resolutions.Count;
            }
        }
Referenced by BioImager.SlideImage.GetLevelDimensions().
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/Source/Bio/SlideImage.cs