BioImager: BioImager.BioImage.ImageJDesc Class Reference
BioImager.BioImage.ImageJDesc Class Reference
Public Member Functions
ImageJDesc FromImage (BioImage b)
string GetString ()
void SetString (string desc)
Public Attributes
string ImageJ
int images = 0
int channels = 0
int slices = 0
int frames = 0
bool hyperstack
string mode
string unit
double finterval = 0
double spacing = 0
bool loop
double min = 0
double max = 0
int count
bool bit8color = false
Detailed Description
Definition at line 2251 of file Bio.cs.
Member Function Documentation
FromImage()
ImageJDesc BioImager.BioImage.ImageJDesc.FromImage (BioImage b)
The function "FromImage" takes a BioImage object and sets the properties of an ImageJDesc object based on the properties of the BioImage object.
Parameters
BioImage The BioImage parameter represents an object that contains information about a biological image, such as the number of images, channels, slices, and frames, as well as other properties like frame interval, physical size, and channel ranges.
Returns
The method is returning an instance of the ImageJDesc class.
Definition at line 2277 of file Bio.cs.
            {
                ImageJ = "";
                images = b.ImageCount;
                channels = b.SizeC;
                slices = b.SizeZ;
                frames = b.SizeT;
                hyperstack = true;
                mode = "grayscale";
                unit = "micron";
                finterval = b.frameInterval;
                spacing = b.PhysicalSizeZ;
                loop = false;
                /*
                double dmax = double.MinValue;
                double dmin = double.MaxValue;
                foreach (Channel c in b.Channels)
                {
                    if(dmax < c.Max)
                        dmax = c.Max;
                    if(dmin > c.Min)
                        dmin = c.Min;
                }
                min = dmin;
                max = dmax;
                */
                min = b.Channels[0].RangeR.Min;
                max = b.Channels[0].RangeR.Max;
                return this;
            }
Referenced by BioImager.BioImage.SaveSeries().
GetString()
string BioImager.BioImage.ImageJDesc.GetString ()
It returns a string that contains the values of all the variables in the imagej image
Returns
A string representation of the imagej image data.
Definition at line 2310 of file Bio.cs.
            {
                string s = "";
                s += "ImageJ=" + ImageJ + "\n";
                s += "images=" + images + "\n";
                s += "channels=" + channels.ToString() + "\n";
                s += "slices=" + slices.ToString() + "\n";
                s += "frames=" + frames.ToString() + "\n";
                s += "hyperstack=" + hyperstack.ToString() + "\n";
                s += "mode=" + mode.ToString() + "\n";
                s += "unit=" + unit.ToString() + "\n";
                s += "finterval=" + finterval.ToString() + "\n";
                s += "spacing=" + spacing.ToString() + "\n";
                s += "loop=" + loop.ToString() + "\n";
                s += "min=" + min.ToString() + "\n";
                s += "max=" + max.ToString() + "\n";
                return s;
            }
Referenced by BioImager.BioImage.SaveSeries().
SetString()
void BioImager.BioImage.ImageJDesc.SetString (string desc)
It sets the string to the value of the parameter.
Parameters
desc The description of the string.
Definition at line 2331 of file Bio.cs.
            {
                string[] lines = desc.Split(new string[] { "\r\n", "\r", "\n" }, StringSplitOptions.None);
                int maxlen = 20;
                for (int i = 0; i < lines.Length; i++)
                {
                    if (i < maxlen)
                    {
                        string[] sp = lines[i].Split('=');
                        if (sp[0] == "ImageJ")
                            ImageJ = sp[1];
                        if (sp[0] == "images")
                            images = int.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "channels")
                            channels = int.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "slices")
                            slices = int.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "frames")
                            frames = int.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "hyperstack")
                            hyperstack = bool.Parse(sp[1]);
                        if (sp[0] == "mode")
                            mode = sp[1];
                        if (sp[0] == "unit")
                            unit = sp[1];
                        if (sp[0] == "finterval")
                            finterval = double.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "spacing")
                            spacing = double.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "loop")
                            loop = bool.Parse(sp[1]);
                        if (sp[0] == "min")
                            min = double.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "max")
                            max = double.Parse(sp[1], CultureInfo.InvariantCulture);
                        if (sp[0] == "8bitcolor")
                            bit8color = bool.Parse(sp[1]);
                    }
                    else
                        return;
                }
            }
Referenced by BioImager.BioImage.OpenFile(), and BioImager.BioImage.OpenSeries().
Member Data Documentation
bit8color
bool BioImager.BioImage.ImageJDesc.bit8color = false
Definition at line 2267 of file Bio.cs.
channels
int BioImager.BioImage.ImageJDesc.channels = 0
Definition at line 2255 of file Bio.cs.
count
int BioImager.BioImage.ImageJDesc.count
Definition at line 2266 of file Bio.cs.
Referenced by microscope.device_server.Filter.filter(), and microscope.cameras.pvcam.PVEnumParam.values().
finterval
double BioImager.BioImage.ImageJDesc.finterval = 0
Definition at line 2261 of file Bio.cs.
frames
int BioImager.BioImage.ImageJDesc.frames = 0
Definition at line 2257 of file Bio.cs.
hyperstack
bool BioImager.BioImage.ImageJDesc.hyperstack
Definition at line 2258 of file Bio.cs.
ImageJ
string BioImager.BioImage.ImageJDesc.ImageJ
Definition at line 2253 of file Bio.cs.
images
int BioImager.BioImage.ImageJDesc.images = 0
Definition at line 2254 of file Bio.cs.
loop
bool BioImager.BioImage.ImageJDesc.loop
Definition at line 2263 of file Bio.cs.
max
double BioImager.BioImage.ImageJDesc.max = 0
Definition at line 2265 of file Bio.cs.
min
double BioImager.BioImage.ImageJDesc.min = 0
Definition at line 2264 of file Bio.cs.
mode
string BioImager.BioImage.ImageJDesc.mode
Definition at line 2259 of file Bio.cs.
slices
int BioImager.BioImage.ImageJDesc.slices = 0
Definition at line 2256 of file Bio.cs.
spacing
double BioImager.BioImage.ImageJDesc.spacing = 0
Definition at line 2262 of file Bio.cs.
unit
string BioImager.BioImage.ImageJDesc.unit
Definition at line 2260 of file Bio.cs.
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/Source/Bio.cs