BioImager: BioImager.Scripting Class Reference
BioImager.Scripting Class Reference
Classes
class Script
class State
Public Types
enum Event
enum ScriptType
Public Member Functions
void RefreshItems ()
It reads all the files in the Scripts and Tools folders and adds them to a listview.
void RefreshStatus ()
It updates the status of the script and the log.
void RunScriptFile (string file)
void Run ()
void Stop ()
Static Public Member Functions
static void LogLine (string s)
static State GetState ()
static void UpdateState (State s)
static void RunScript (string file)
static void RunScript (Script sc)
static void RunString (string st)
static void RunByName (string name)
Public Attributes
CodeView view = null
Static Public Attributes
static string log
static string ImageJPath = Properties.Settings.Default.ImageJPath
static Dictionary< string, Script > Scripts = new Dictionary<string, Script>()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Detailed Description
Definition at line 5 of file Scripting.cs.
Member Enumeration Documentation
Event
enum BioImager.Scripting.Event
Definition at line 232 of file Scripting.cs.
        {
            Down,
            Up,
            Move,
            None
        }
ScriptType
enum BioImager.Scripting.ScriptType
Definition at line 239 of file Scripting.cs.
        {
            tool,
            script,
            imagej
        }
Constructor & Destructor Documentation
Scripting()
BioImager.Scripting.Scripting ()
Definition at line 351 of file Scripting.cs.
        {
            if (!Directory.Exists(Application.StartupPath + "//" + "Scripts"))
                Directory.CreateDirectory(Application.StartupPath + "//" + "Scripts");
            if (!Directory.Exists(Application.StartupPath + "//" + "Tools"))
                Directory.CreateDirectory(Application.StartupPath + "//" + "Tools");
            InitializeComponent();
            scriptView.MultiSelect = false;
            RefreshItems();
            timer.Start();
            codeview = new CodeView();
            codeview.Dock = DockStyle.Fill;
            scriptLabel.Text = "NewScript.cs";
            //splitContainer.Dock = DockStyle.Fill;
            textBox = codeview.TextBox;
            splitContainer.Panel1.Controls.Add(codeview);
        }
Member Function Documentation
Dispose()
override void BioImager.Scripting.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file Scripting.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
GetState()
static State BioImager.Scripting.GetState () static
It returns the state of the game.
Returns
The state of the game.
Definition at line 249 of file Scripting.cs.
        {
            return state;
        }
LogLine()
static void BioImager.Scripting.LogLine (string s) static
Definition at line 11 of file Scripting.cs.
        {
            log += s + Environment.NewLine;
        }
RefreshItems()
void BioImager.Scripting.RefreshItems ()
It reads all the files in the Scripts and Tools folders and adds them to a listview.
Definition at line 275 of file Scripting.cs.
        {
            Scripts.Clear();
            string st = Application.StartupPath;
            foreach (string file in Directory.GetFiles(st + "/Scripts"))
            {
                if (!Scripts.ContainsKey(Path.GetFileName(file)))
                {
                    //This is a script file.
                    Script sc = new Script(file, File.ReadAllText(file));
                    ListViewItem lv = new ListViewItem();
                    lv.Tag = sc;
                    lv.Text = sc.ToString();
                    scriptView.Items.Add(lv);
                    Scripts.Add(lv.Text, sc);
                }
            }
            foreach (string file in Directory.GetFiles(st + "/Tools"))
            {
                if (file.EndsWith(".cs"))
                {
                    if (!Scripts.ContainsKey(Path.GetFileName(file)))
                    {
                        //This is a script file.
                        Script sc = new Script(file, File.ReadAllText(file));
                        sc.type = ScriptType.tool;
                        ListViewItem lv = new ListViewItem();
                        lv.Tag = sc;
                        lv.Text = sc.ToString();
                        scriptView.Items.Add(lv);
                        Scripts.Add(lv.Text, sc);
                    }
                }
            }
        }
References BioImager.Scripting.Script.ToString().
Referenced by BioImager.Scripting.RunScriptFile().
RefreshStatus()
void BioImager.Scripting.RefreshStatus ()
It updates the status of the script and the log.
Definition at line 311 of file Scripting.cs.
        {
            errorView.Clear();
            foreach (ListViewItem item in scriptView.SelectedItems)
            {
                Script s = (Script)item.Tag;
                //We update item text to show Script status.
                item.Text = s.ToString();
                outputBox.Text = s.output;
                if (s.ex != null)
                {
                    string[] sps = s.ex.Message.Split('>');
                    //ListViewItem it = new ListViewItem(s.ex.ToString());
                    for (int i = 1; i < sps.Length; i++)
                    {
                        ListViewItem er = new ListViewItem(sps[i]);
                        er.Tag = s.ex;
                        errorView.Items.Add(er);
                    }
                }
            }
            foreach (ListViewItem item in scriptView.SelectedItems)
            {
                Script s = (Script)item.Tag;
                //We update item text to show Script status.
                item.Text = s.ToString();
            }
            logBox.Text = log;
            //We scroll to end of text so we see latest log output.
            if (logBox.SelectionStart != logBox.Text.Length)
            {
                logBox.SelectionStart = logBox.Text.Length;
                logBox.ScrollToCaret();
            }
        }
References BioImager.Scripting.Script.ToString().
Run()
void BioImager.Scripting.Run ()
It runs the script that is selected in the listview
Returns
The output of the script.
Definition at line 403 of file Scripting.cs.
        {
            log = "";
            outputBox.Text = "";
            logBox.Text = "";
            if (scriptView.SelectedItems.Count == 0)
                return;
            foreach (ListViewItem item in scriptView.SelectedItems)
            {
                //We run this script
                Script sc = (Script)item.Tag;
                sc.scriptString = textBox.Text;
                sc.output = "";
                sc.Run();
                outputBox.Text = sc.output;
                logBox.Text = log;
            }
        }
References BioImager.Scripting.Script.Run().
RunByName()
static void BioImager.Scripting.RunByName (string name) static
RunByName(string name)
Parameters
name The name of the script.
Definition at line 438 of file Scripting.cs.
        {
            Scripts[name].Run();
        }
Referenced by BioImager.Scripting.RunScript(), and BioImager.Scripting.RunScriptFile().
RunScript() [1/2]
static void BioImager.Scripting.RunScript (Script sc) static
Definition at line 387 of file Scripting.cs.
        {
            if(!Scripts.ContainsKey(sc.name))
            Scripts.Add(sc.name, sc);
            RunByName(sc.name);
        }
RunScript() [2/2]
static void BioImager.Scripting.RunScript (string file) static
It creates a new script object, adds it to the dictionary, and then runs it
Parameters
file The file path to the script.
Definition at line 381 of file Scripting.cs.
        {
            Script sc = new Script(file);
            Scripts.Add(sc.name, sc);
            RunByName(sc.name);
        }
References BioImager.Scripting.RunByName().
Referenced by BioImager.Imager.PerformFunction().
RunScriptFile()
void BioImager.Scripting.RunScriptFile (string file)
It runs a script file
Parameters
file The file path of the script to run.
Definition at line 371 of file Scripting.cs.
        {
            Script sc = new Script(file);
            Scripts.Add(sc.name, sc);
            RefreshItems();
            RunByName(sc.name);
        }
References BioImager.Scripting.RefreshItems(), and BioImager.Scripting.RunByName().
RunString()
static void BioImager.Scripting.RunString (string st) static
It runs a string as a Lua script
Parameters
st The string to run.
Definition at line 396 of file Scripting.cs.
        {
            Script.RunString(st);
        }
References BioImager.Scripting.Script.RunString().
Referenced by BioImager.Function.PerformFunction().
Stop()
void BioImager.Scripting.Stop ()
We stop the script
Returns
The script is being returned.
Definition at line 424 of file Scripting.cs.
        {
            if (scriptView.SelectedItems.Count == 0)
                return;
            foreach (ListViewItem item in scriptView.SelectedItems)
            {
                //We run this script
                Script sc = (Script)item.Tag;
                sc.Stop();
            }
        }
References BioImager.Scripting.Script.Stop().
UpdateState()
static void BioImager.Scripting.UpdateState (State s) static
If the state is null, return. If the state is not null, set the state to the new state. If the state is not null and the new state is the same as the old state, set the processed flag to true
Parameters
State This is the state of the game. It contains the position of the player, the type of the player, and whether the state has been processed or not.
Returns
The state of the current object.
Definition at line 261 of file Scripting.cs.
        {
            if (s == null)
                return;
            if (state == null)
                state = s;
            if (s.p.X == state.p.X && s.p.Y == state.p.Y && s.type == state.type)
            {
                state.processed = true;
            }
            else
                state = s;
        }
Referenced by BioImager.Tools.ToolDown(), and BioImager.Tools.ToolUp().
Member Data Documentation
ImageJPath
string BioImager.Scripting.ImageJPath = Properties.Settings.Default.ImageJPath static
Definition at line 9 of file Scripting.cs.
log
string BioImager.Scripting.log static
Definition at line 7 of file Scripting.cs.
Scripts
Dictionary<string, Script> BioImager.Scripting.Scripts = new Dictionary<string, Script>() static
Definition at line 15 of file Scripting.cs.
view
CodeView BioImager.Scripting.view = null
Definition at line 8 of file Scripting.cs.
The documentation for this class was generated from the following files:
F:/repos/BioImager/BioImager/Source/Scripting.cs
F:/repos/BioImager/BioImager/Source/Scripting.Designer.cs