BioImager: microscope.testsuite.mock_devices.CoherentSapphireLaserMock Class Reference
microscope.testsuite.mock_devices.CoherentSapphireLaserMock Class Reference
Public Member Functions
def __init__ (self, *args, **kwargs)
def write (self, data)
def handle (self, command)
Public Member Functions inherited from microscope.testsuite.mock_devices.SerialMock
def __init__ (self, *args, **kwargs)
def open (self)
def close (self)
def handle (self, command)
def write (self, data)
def read (self, size=1)
def readline (self, size=-1)
def reset_input_buffer (self)
def reset_output_buffer (self)
Public Attributes
key
status
light
tec
echo
prompt
power
Public Attributes inherited from microscope.testsuite.mock_devices.SerialMock
in_buffer
out_buffer
out_pending_bytes
out_parsed_bytes
in_read_bytes
Static Public Attributes
string eol = b"\r\n"
int baudrate = 19200
parity = serial.PARITY_NONE
bytesize = serial.EIGHTBITS
stopbits = serial.STOPBITS_ONE
bool rtscts = False
bool dsrdtr = False
float default_power = 50.0
float min_power = 20.0
float max_power = 220.0
Detailed Description
Modelled after a Coherent Sapphire LP 561nm laser.
This mocked device is constructed into the ready state.  That is,
after the laser has been turned on enough time to warmup (~ 30
seconds), and then the key has been turned on for enough time to
actual get the laser ready (~10 seconds).
We don't mock the turning of the key, that's much trickier and we
don't need it yet.  We'll do it if it ever becomes an issue, and
probably use a state machine library for that.
Definition at line 107 of file mock_devices.py.
Constructor & Destructor Documentation
__init__()
def microscope.testsuite.mock_devices.CoherentSapphireLaserMock.__init__ (self, * args, ** kwargs)
Reimplemented from microscope.testsuite.mock_devices.SerialMock.
Definition at line 136 of file mock_devices.py.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.key = "on"
        self.status = "laser ready"  # Laser ready, status code 5
        self.light = True  # Light Servo
        self.tec = True  # TEC (Thermo-Electric Cooler) Servo
        self.echo = True
        self.prompt = True
        self.power = CoherentSapphireLaserMock.default_power
Member Function Documentation
handle()
def microscope.testsuite.mock_devices.CoherentSapphireLaserMock.handle (self, command)
Reimplemented from microscope.testsuite.mock_devices.SerialMock.
Definition at line 158 of file mock_devices.py.
    def handle(self, command):
        # Operator's manual mentions all commands in uppercase.
        # Experimentation shows that they are case insensitive.
        command = command.upper()
        answer = None
        # Prompt
        if command == b">=0":
            self.prompt = False
        elif command == b">=1":
            self.prompt = True
        # Echo
        elif command == b"E=0":
            self.echo = False
        elif command == b"E=1":
            self.echo = True
        # Head ID
        elif command == b"?HID":
            answer = b"505925.000"
        # Head hours
        elif command == b"?HH":
            answer = b"   257:34"
        # Key switch
        elif command == b"?K":
            if self.key == "standby":
                answer = b"0"
            elif self.key == "on":
                answer = b"1"
            else:
                raise RuntimeError("unknown key state '%s'" % self.key)
        # Light servo
        elif command == b"L=0":
            self.light = False
        elif command == b"L=1":
            if self.tec:
                if self.key == "on":
                    self.light = True
                # if key switch is not on, keep light off
            else:
                answer = b"TEC must be ON (T=1) to enable Light Output!"
        elif command == b"?L":
            answer = b"1" if self.light else b"0"
        # TEC servo
        elif command == b"T=0":
            # turning this off, also turns light servo off
            self.tec = False
            self.light = False
        elif command == b"T=1":
            self.tec = True
        elif command == b"?T":
            answer = b"1" if self.tec else b"0"
        # Laser power
        elif command == b"?MINLP":
            answer = b"20.000"
        elif command == b"?MAXLP":
            answer = b"220.000"
        elif command == b"?P":
            if not self.light:
                answer = b"0.000"
            else:
                answer = b"%.3f" % (self.power)
        elif command == b"?SP":
            answer = b"%.3f" % (self.power)
        elif command.startswith(b"P="):
            new_power = float(command[2:])
            if new_power < 19.999999 or new_power > 220.00001:
                answer = b"value must be between 20.000 and 220.000"
            else:
                if not self.light:
                    answer = b"Note: Laser_Output is OFF (L=0)"
                self.power = new_power
        # Nominal output power
        elif command == b"NOMP":
            answer = b"200"
        # Laser type and nominal power
        elif command == b"LT":
            answer = b"Sapphire 200mW"
        # Laser head status
        elif command == b"?STA":
            status_codes = {
                "start up": b"1",
                "warmup": b"2",
                "standby": b"3",
                "laser on": b"4",
                "laser ready": b"5",
                "error": b"6",
            }
            answer = status_codes[self.status]
        # Fault related commands.  We don't model any faults yet.
        elif command == b"?F":
            answer = b"0"
        elif command == b"?FF":
            # Two bytes with possible faults:
            #    0 - external interlock fault
            #    1 - diode temperature fault (both TEC and light
            #        servo off)
            #    2 - base plate temperature fault (both TEC and light
            #        servo off)
            #    3 - OEM controller LP temperature (both TEC and
            #        light servo off)
            #    4 - diode current fault
            #    5 - analog interface fault
            #    6 - base plate temperature fault (only light servo
            #        turned off)
            #    7 - diode temperature fault (only light servo turned
            #        off)
            #    8 - system warning/waiting for TEC servo to reach
            #        target temperature
            #    9 - head EEPROM fault
            #   10 - OEM controller LP EEPROM fault
            #   11 - EEPOT1 fault
            #   12 - EEPOT2 fault
            #   13 - laser ready
            #   14 - not implemented
            #   15 - not implemented
            if self.light:
                # Has a bit of its own, but it's not really a fault.
                answer = b"8192"  # 00100000 00000000
            else:
                answer = b"0"
        elif command == b"?FL":
            # Show faults in text.  This is a multiline reply, one
            # per fault, plus the header line.
            answer = b"Fault(s):\r\n\tNone"
        # Software version
        elif command in [b"sv", b"svps"]:
            answer = b"8.005"
        # Nominal laser wavelength
        elif command == b"?WAVE":
            answer = b"561"
        else:
            raise NotImplementedError(
                "no handling for command '%s'" % command.decode("utf-8")
            )
        if answer is not None:
            self.in_buffer.write(answer + self.eol)
        if self.prompt:
            self.in_buffer.write(b"Sapphire:0-> ")
        return
Referenced by microscope.cameras._SDK3Cam.SDK3Camera.__init__(), microscope.cameras.pvcam.PVCamera.abort(), microscope.cameras.andorsdk3.AndorSDK3.get_id(), microscope.cameras.andorsdk3.AndorSDK3.initialize(), microscope.cameras.pvcam.PVCamera.initialize(), microscope.cameras.andorsdk3.AndorSDK3.invalidate_buffers(), microscope.cameras.pvcam.PVCamera.set_trigger(), and microscope.cameras.pvcam.PVCamera.soft_trigger().
write()
def microscope.testsuite.mock_devices.CoherentSapphireLaserMock.write (self, data)
Reimplemented from microscope.testsuite.mock_devices.SerialMock.
Definition at line 147 of file mock_devices.py.
    def write(self, data):
        # Echo as soon as we get data, do not wait for an EOL.  Also,
        # echo before handling the command because if will echo even
        # if the command is to turn the echo off.
        if self.echo:
            self.in_buffer.write(data)
        else:
            # If echo is off, we still echo EOLs
            self.in_buffer.write(self.eol * data.count(self.eol))
        return super().write(data)
Member Data Documentation
baudrate
int microscope.testsuite.mock_devices.CoherentSapphireLaserMock.baudrate = 19200 static
Definition at line 124 of file mock_devices.py.
bytesize
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.bytesize = serial.EIGHTBITS static
Definition at line 126 of file mock_devices.py.
default_power
float microscope.testsuite.mock_devices.CoherentSapphireLaserMock.default_power = 50.0 static
Definition at line 132 of file mock_devices.py.
dsrdtr
bool microscope.testsuite.mock_devices.CoherentSapphireLaserMock.dsrdtr = False static
Definition at line 129 of file mock_devices.py.
echo
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.echo
Definition at line 143 of file mock_devices.py.
eol
string microscope.testsuite.mock_devices.CoherentSapphireLaserMock.eol = b"\r\n" static
Definition at line 121 of file mock_devices.py.
Referenced by microscope.filterwheels.thorlabs.ThorlabsFilterWheel.__init__().
key
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.key
Definition at line 139 of file mock_devices.py.
light
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.light
Definition at line 141 of file mock_devices.py.
max_power
float microscope.testsuite.mock_devices.CoherentSapphireLaserMock.max_power = 220.0 static
Definition at line 134 of file mock_devices.py.
min_power
float microscope.testsuite.mock_devices.CoherentSapphireLaserMock.min_power = 20.0 static
Definition at line 133 of file mock_devices.py.
parity
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.parity = serial.PARITY_NONE static
Definition at line 125 of file mock_devices.py.
power
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.power
Definition at line 145 of file mock_devices.py.
prompt
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.prompt
Definition at line 144 of file mock_devices.py.
rtscts
bool microscope.testsuite.mock_devices.CoherentSapphireLaserMock.rtscts = False static
Definition at line 128 of file mock_devices.py.
status
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.status
Definition at line 140 of file mock_devices.py.
stopbits
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.stopbits = serial.STOPBITS_ONE static
Definition at line 127 of file mock_devices.py.
tec
microscope.testsuite.mock_devices.CoherentSapphireLaserMock.tec
Definition at line 142 of file mock_devices.py.
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/PythonMicroscope/microscope/testsuite/mock_devices.py