BioImager: microscope.testsuite.mock_devices.CoboltLaserMock Class Reference
microscope.testsuite.mock_devices.CoboltLaserMock Class Reference
Public Member Functions
def __init__ (self, *args, **kwargs)
def handle (self, command)
Public Member Functions inherited from microscope.testsuite.mock_devices.SerialMock
def __init__ (self, *args, **kwargs)
def open (self)
def close (self)
def handle (self, command)
def write (self, data)
def read (self, size=1)
def readline (self, size=-1)
def reset_input_buffer (self)
def reset_output_buffer (self)
Public Attributes
power
light
interlock_open
auto_start
direct_control
on_after_interlock
fault
Public Attributes inherited from microscope.testsuite.mock_devices.SerialMock
in_buffer
out_buffer
out_pending_bytes
out_parsed_bytes
in_read_bytes
Static Public Attributes
string eol = b"\r"
int baudrate = 115200
parity = serial.PARITY_NONE
bytesize = serial.EIGHTBITS
stopbits = serial.STOPBITS_ONE
bool rtscts = False
bool dsrdtr = False
float default_power = 50.0
float min_power = 0.0
float max_power = 600.0
Detailed Description
Modelled after a Cobolt Jive laser 561nm.
Definition at line 316 of file mock_devices.py.
Constructor & Destructor Documentation
__init__()
def microscope.testsuite.mock_devices.CoboltLaserMock.__init__ (self, * args, ** kwargs)
Reimplemented from microscope.testsuite.mock_devices.SerialMock.
Definition at line 333 of file mock_devices.py.
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.power = CoboltLaserMock.default_power
        self.light = False
        self.interlock_open = False
        self.auto_start = False
        self.direct_control = False
        self.on_after_interlock = False
        self.fault = None
Member Function Documentation
handle()
def microscope.testsuite.mock_devices.CoboltLaserMock.handle (self, command)
Reimplemented from microscope.testsuite.mock_devices.SerialMock.
Definition at line 348 of file mock_devices.py.
    def handle(self, command):
        # Leading and trailing whitespace is ignored.
        command = command.strip()
        # Acknowledgment string if command is not a query and there
        # is no error.
        answer = b"OK"
        if command == b"sn?":  # serial number
            answer = b"7863"
        elif command == b"gcn?":
            answer = b"Macro-Gen5b-SHG-0501_4W-RevA"
        elif command == b"ver?" or command == b"gfv?":
            answer = b"50070"
        elif command == b"gfvlas?":
            answer = b"This laser head does not have firmware."
        elif command == b"hrs?":  # System operating hours
            answer = b"828.98"
        # TODO: This whole @cob0 and @cob1 need better testing on
        # what it actually does.  Documentation says that @cob1 is
        # "Laser ON after interlock.  Forces laser into
        # autostart. without checking if autostart is enabled".
        # @cob0 is undocumented.
        # May be a bug but the commands @cob0 and @cob1 both have the
        # effect of also turning off the laser.
        elif command == b"@cob1":
            self.on_after_interlock = True
            self.light = False
        elif command == b"@cob0":
            self.on_after_interlock = False
            self.light = False
        elif command == b"@cobas?":
            answer = b"1" if self.auto_start else b"0"
        elif command == b"@cobas 0":
            self.auto_start = False
        elif command == b"@cobas 1":
            self.auto_start = True
        # Laser state
        elif command == b"l?":
            answer = b"1" if self.light else b"0"
        elif command == b"l1":
            if self.auto_start:
                answer = b"Syntax error: not allowed in autostart mode."
            else:
                self.light = True
        elif command == b"l0":
            self.light = False
        # Output power
        elif command.startswith(b"p "):
            # The p command takes values in W so convert to mW
            new_power = float(command[2:]) * 1000.0
            if new_power > self.max_power or new_power < self.min_power:
                answer = b"Syntax error: Value is out of range."
            else:
                self.power = new_power
        elif command == b"p?":
            answer = b"%.4f" % (self.power / 1000.0)
        elif command == b"pa?":
            if self.light:
                answer = b"%.4f" % (self.power / 1000.0)
            else:
                answer = b"0.0000"
        # Undocumented.  Seems to be the same as 'p ...'
        elif command.startswith(b"@cobasp "):
            return self.handle(command[6:])
        # Direct control
        elif command == b"@cobasdr?":
            answer = b"1" if self.direct_control else b"0"
        elif command == b"@cobasdr 0":
            self.direct_control = False
        elif command == b"@cobasdr 1":
            self.direct_control = False
        # Undocumented.  Seems to returns maximum laser power in mW.
        elif command == b"gmlp?":
            answer = b"600.000000"
        # Are you there?
        elif command == b"?":
            answer = b"OK"
        # Get operating fault
        elif command == b"f?":
            # The errors (which we don't model yet) are:
            #   1 = temperature error
            #   3 = interlock
            #   4 = constant power fault
            answer = b"0"
        # Interlock state
        elif command == b"ilk?":
            answer = b"1" if self.interlock_open else b"0"
        # Autostart program state
        elif command == b"cobast?":
            # This is completely undocumented.  Manual
            # experimentation seems to be:
            # 0 = laser off with @cob0
            # 1 = laser off with @cob1
            # 2 = waiting for temperature
            # 3 = warming up
            # 4 = completed (laser on)
            # 5 = fault (such as interlock)
            # 6 = aborted
            if self.light:
                answer = b"4"
            else:
                answer = b"1" if self.on_after_interlock else b"0"
        else:
            raise NotImplementedError(
                "no handling for command '%s'" % command.decode("utf-8")
            )
        # Sending a command is done with '\r' only.  However,
        # responses from the hardware end with '\r\n'.
        self.in_buffer.write(answer + b"\r\n")
Referenced by microscope.cameras._SDK3Cam.SDK3Camera.__init__(), microscope.cameras.pvcam.PVCamera.abort(), microscope.cameras.andorsdk3.AndorSDK3.get_id(), microscope.cameras.andorsdk3.AndorSDK3.initialize(), microscope.cameras.pvcam.PVCamera.initialize(), microscope.cameras.andorsdk3.AndorSDK3.invalidate_buffers(), microscope.cameras.pvcam.PVCamera.set_trigger(), and microscope.cameras.pvcam.PVCamera.soft_trigger().
Member Data Documentation
auto_start
microscope.testsuite.mock_devices.CoboltLaserMock.auto_start
Definition at line 341 of file mock_devices.py.
baudrate
int microscope.testsuite.mock_devices.CoboltLaserMock.baudrate = 115200 static
Definition at line 321 of file mock_devices.py.
bytesize
microscope.testsuite.mock_devices.CoboltLaserMock.bytesize = serial.EIGHTBITS static
Definition at line 323 of file mock_devices.py.
default_power
float microscope.testsuite.mock_devices.CoboltLaserMock.default_power = 50.0 static
Definition at line 329 of file mock_devices.py.
direct_control
microscope.testsuite.mock_devices.CoboltLaserMock.direct_control
Definition at line 342 of file mock_devices.py.
dsrdtr
bool microscope.testsuite.mock_devices.CoboltLaserMock.dsrdtr = False static
Definition at line 326 of file mock_devices.py.
eol
string microscope.testsuite.mock_devices.CoboltLaserMock.eol = b"\r" static
Definition at line 319 of file mock_devices.py.
Referenced by microscope.filterwheels.thorlabs.ThorlabsFilterWheel.__init__().
fault
microscope.testsuite.mock_devices.CoboltLaserMock.fault
Definition at line 346 of file mock_devices.py.
interlock_open
microscope.testsuite.mock_devices.CoboltLaserMock.interlock_open
Definition at line 339 of file mock_devices.py.
light
microscope.testsuite.mock_devices.CoboltLaserMock.light
Definition at line 337 of file mock_devices.py.
max_power
float microscope.testsuite.mock_devices.CoboltLaserMock.max_power = 600.0 static
Definition at line 331 of file mock_devices.py.
min_power
float microscope.testsuite.mock_devices.CoboltLaserMock.min_power = 0.0 static
Definition at line 330 of file mock_devices.py.
on_after_interlock
microscope.testsuite.mock_devices.CoboltLaserMock.on_after_interlock
Definition at line 344 of file mock_devices.py.
parity
microscope.testsuite.mock_devices.CoboltLaserMock.parity = serial.PARITY_NONE static
Definition at line 322 of file mock_devices.py.
power
microscope.testsuite.mock_devices.CoboltLaserMock.power
Definition at line 336 of file mock_devices.py.
rtscts
bool microscope.testsuite.mock_devices.CoboltLaserMock.rtscts = False static
Definition at line 325 of file mock_devices.py.
stopbits
microscope.testsuite.mock_devices.CoboltLaserMock.stopbits = serial.STOPBITS_ONE static
Definition at line 324 of file mock_devices.py.
The documentation for this class was generated from the following file:
F:/repos/BioImager/BioImager/PythonMicroscope/microscope/testsuite/mock_devices.py