BioImager: BioImager.Imager Class Reference
BioImager.Imager Class Reference
Classes
class ControllerFuncs
class Profile
Public Member Functions
void UpdateStatus ()
void StoreCoordinate ()
void CheckGamepadButtons (Gamepad state, Gamepad prevState)
object PerformFunction (Function f)
Static Public Member Functions
static int DigitsInString (string str)
Public Attributes
Controller controller
Gamepad gamepad
Gamepad previousGamepadState
bool prevState = false
bool connected = false
float leftTrigger
float rightTrigger
int deadzone = 5
string m_ID
Profile CurrentProfile = new Profile("Default")
Static Public Attributes
static IntPtr apph
static string AppPath = ""
static List< BioImage > StoredImages = new List<BioImage>()
static ? bool liveStatus = null
static InputSimulator input = new InputSimulator()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
string ID [get]
static Process ZenP [get, set]
uint ImagesPerSlice [get, set]
uint SliceIncrement [get, set]
uint SlicesPerSlide [get, set]
Detailed Description
Definition at line 23 of file Imager.cs.
Constructor & Destructor Documentation
Imager()
BioImager.Imager.Imager ()
Definition at line 138 of file Imager.cs.
        {
            InitializeComponent();
            if (Settings.Default.PycroManager)
            {
                topMostCheckBox.Checked = false;
                dockToApp.Checked = false;
            }
            Stopwatch timer = new Stopwatch();
            timer.Start();
            TimeSpan st1 = timer.Elapsed;
            m_ID = "";
            if (Settings.Default.AppPath != "")
            {
                //We start the imaging application making sure the we have the right path to the executable.
                AppPath = Settings.Default.AppPath;
                if (!File.Exists(AppPath))
                {
                    MessageBox.Show("Error!", "Imaging appplication not found. Please locate the executable.");
                    //path is not default. Let the user find it.
                    if (openExeFileDialog.ShowDialog() != DialogResult.OK)
                        Application.Exit();
                    Settings.Default.AppPath = openExeFileDialog.FileName;
                }
                string pn = Path.GetFileNameWithoutExtension(AppPath);
                Process[] prs = Process.GetProcessesByName(pn);
                if (prs.Length == 0)
                {
                    AppP = Process.Start(AppPath);
                }
                else
                    AppP = prs[0];
                apph = AppP.MainWindowHandle;
                //We use a try block incase of Win32 Access violation error.
                try
                {
                    AppP.WaitForInputIdle();
                }
                catch (Exception)
                {
                }
            }
            statusTimer.Start();
            for (UserIndex i = UserIndex.One; i <= UserIndex.Four; i++)
            {
                controller = new Controller(i);
                if (controller.IsConnected)
                {
                    connected = true;
                    break;
                }
                else controller = null;
            }
            ControllerFuncs.LoadSettings();
            controllerJoystickUpdate.Start();
            controllerButtonUpdate.Start();
            if (!Directory.Exists(Application.StartupPath + "\\Profiles"))
                Directory.CreateDirectory(Application.StartupPath + "\\Profiles");
            string[] sts = Directory.GetFiles(Application.StartupPath + "\\Profiles");
            foreach (string s in sts)
            {
                Profile p = new Profile(s);
                profilesBox.Items.Add(p);
            }
            if (Settings.Default.PreviousProfile != "Default")
            {
                CurrentProfile = new Profile(Settings.Default.PreviousProfile);
                CurrentProfile.Load();
                int index = 0;
                foreach (Profile item in profilesBox.Items)
                {
                    if (item.FilePath == Settings.Default.PreviousProfile)
                    {
                        profilesBox.SelectedIndex = index;
                        break;
                    }
                    index++;
                }
            }
            this.TopMost = topMostCheckBox.Checked;
            if (dockToApp.Checked && !Properties.Settings.Default.PycroManager)
            {
                //We set window location based on imaging application location.
                Win32.Rect r = new Win32.Rect();
                Win32.GetWindowRect(apph, ref r);
                System.Drawing.Point pp = new System.Drawing.Point(r.Right - this.Width, r.Bottom - this.Height - 23);
                this.Location = new System.Drawing.Point((int)pp.X, (int)pp.Y);
            }
            this.Show();
        }
Member Function Documentation
CheckGamepadButtons()
void BioImager.Imager.CheckGamepadButtons (Gamepad state, Gamepad prevState)
If the button is set to be pressed, then check if the button is pressed. If it is, then perform the function. If it's not, then do nothing. If the button is set to be released, then check if the button is released. If it is, then perform the function. If it's not, then do nothing
Parameters
Gamepad The current state of the controller
Gamepad The previous state of the controller
Definition at line 997 of file Imager.cs.
        {
            #region YBAX Keys
            if (ControllerFuncs.Y.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.Y && state.Buttons != GamepadButtonFlags.Y)
                {
                    PerformFunction(ControllerFuncs.Y);
                    prevState.Buttons = GamepadButtonFlags.None;
                    YPressedLabel.Text = "Y: released";
                }
                else
                    YPressedLabel.Text = "Y: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.Y)
                {
                    PerformFunction(ControllerFuncs.Y);
                    prevState.Buttons = GamepadButtonFlags.None;
                    YPressedLabel.Text = "Y: pressed";
                }
                else
                    YPressedLabel.Text = "Y: not pressed";
            }
            if (ControllerFuncs.B.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.B && state.Buttons != GamepadButtonFlags.B)
                {
                    PerformFunction(ControllerFuncs.B);
                    prevState.Buttons = GamepadButtonFlags.None;
                    state.Buttons = GamepadButtonFlags.None;
                    BPressedLabel.Text = "B: released";
                }
                else
                    BPressedLabel.Text = "B: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.B)
                {
                    PerformFunction(ControllerFuncs.B);
                    prevState.Buttons = GamepadButtonFlags.None;
                    BPressedLabel.Text = "B: pressed";
                }
                else
                    BPressedLabel.Text = "B: not pressed";
            }
            if (ControllerFuncs.A.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.A && state.Buttons != GamepadButtonFlags.A)
                {
                    PerformFunction(ControllerFuncs.A);
                    prevState.Buttons = GamepadButtonFlags.None;
                    APressedLabel.Text = "A: released";
                }
                else
                    APressedLabel.Text = "A: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.A)
                {
                    PerformFunction(ControllerFuncs.A);
                    prevState.Buttons = GamepadButtonFlags.None;
                    APressedLabel.Text = "A: pressed";
                }
                else
                    APressedLabel.Text = "A: not pressed";
            }
            if (ControllerFuncs.X.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.X && state.Buttons != GamepadButtonFlags.X)
                {
                    PerformFunction(ControllerFuncs.X);
                    prevState.Buttons = GamepadButtonFlags.None;
                    XPressedLabel.Text = "X: released";
                }
                else
                    XPressedLabel.Text = "X: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.X)
                {
                    PerformFunction(ControllerFuncs.X);
                    prevState.Buttons = GamepadButtonFlags.None;
                    XPressedLabel.Text = "X: pressed";
                }
                else
                    XPressedLabel.Text = "X: not pressed";
            }
            #endregion
            #region Back & Start Keys
            if (ControllerFuncs.Start.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.Start && state.Buttons != GamepadButtonFlags.Start)
                {
                    PerformFunction(ControllerFuncs.Start);
                    prevState.Buttons = GamepadButtonFlags.None;
                    StartPressedLabel.Text = "Start: released";
                }
                else
                    StartPressedLabel.Text = "Start: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.Start)
                {
                    PerformFunction(ControllerFuncs.Start);
                    prevState.Buttons = GamepadButtonFlags.None;
                    StartPressedLabel.Text = "Start: pressed";
                }
                else
                    StartPressedLabel.Text = "Start: not pressed";
            }
            if (ControllerFuncs.Back.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.Back && state.Buttons != GamepadButtonFlags.Back)
                {
                    PerformFunction(ControllerFuncs.Back);
                    prevState.Buttons = GamepadButtonFlags.None;
                    BackPressedLabel.Text = "Back: released";
                }
                else
                    BackPressedLabel.Text = "Back: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.Back)
                {
                    PerformFunction(ControllerFuncs.Back);
                    prevState.Buttons = GamepadButtonFlags.None;
                    BackPressedLabel.Text = "Back: pressed";
                }
                else
                    BackPressedLabel.Text = "Back: not pressed";
            }
            #endregion
            #region Shoulders
            if (ControllerFuncs.RShoulder.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.RightShoulder && state.Buttons != GamepadButtonFlags.RightShoulder)
                {
                    PerformFunction(ControllerFuncs.RShoulder);
                    prevState.Buttons = GamepadButtonFlags.None;
                    shoulderRightLabel.Text = "Right: released";
                }
                else
                    shoulderRightLabel.Text = "Right: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.RightShoulder)
                {
                    PerformFunction(ControllerFuncs.RShoulder);
                    prevState.Buttons = GamepadButtonFlags.None;
                    shoulderRightLabel.Text = "Right: pressed";
                }
                else
                    shoulderRightLabel.Text = "Right: not pressed";
            }
            if (ControllerFuncs.LShoulder.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.LeftShoulder && state.Buttons != GamepadButtonFlags.LeftShoulder)
                {
                    PerformFunction(ControllerFuncs.RShoulder);
                    prevState.Buttons = GamepadButtonFlags.None;
                    shoulderLeftLabel.Text = "Left: released";
                }
                else
                    shoulderLeftLabel.Text = "Left: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.LeftShoulder)
                {
                    PerformFunction(ControllerFuncs.LShoulder);
                    prevState.Buttons = GamepadButtonFlags.None;
                    shoulderLeftLabel.Text = "Left: pressed";
                }
                else
                    shoulderLeftLabel.Text = "Left: not pressed";
            }
            #endregion
            #region L3 & R3
            if (ControllerFuncs.R3.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.RightThumb && state.Buttons != GamepadButtonFlags.RightThumb)
                {
                    PerformFunction(ControllerFuncs.R3);
                    prevState.Buttons = GamepadButtonFlags.None;
                    r3PressedLabel.Text = "R3: released";
                }
                else
                    r3PressedLabel.Text = "R3: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.RightThumb)
                {
                    PerformFunction(ControllerFuncs.R3);
                    prevState.Buttons = GamepadButtonFlags.None;
                    r3PressedLabel.Text = "R3: pressed";
                }
                else
                    r3PressedLabel.Text = "R3: not pressed";
            }
            if (ControllerFuncs.L3.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.LeftThumb && state.Buttons != GamepadButtonFlags.LeftThumb)
                {
                    PerformFunction(ControllerFuncs.L3);
                    prevState.Buttons = GamepadButtonFlags.None;
                    l3PressedLabel.Text = "L3: released";
                }
                else
                    l3PressedLabel.Text = "L3: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.LeftThumb)
                {
                    PerformFunction(ControllerFuncs.L3);
                    prevState.Buttons = GamepadButtonFlags.None;
                    l3PressedLabel.Text = "L3: pressed";
                }
                else
                    l3PressedLabel.Text = "L3: not pressed";
            }
            #endregion
            #region DPAD BUTTONS
            if (ControllerFuncs.DPadUp.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.DPadUp && state.Buttons != GamepadButtonFlags.DPadUp)
                {
                    PerformFunction(ControllerFuncs.DPadUp);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadUpLabel.Text = "Up: released";
                }
                else
                    DPadUpLabel.Text = "Up: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.DPadUp)
                {
                    PerformFunction(ControllerFuncs.DPadUp);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadUpLabel.Text = "Up: pressed";
                }
                else
                    DPadUpLabel.Text = "Up: not pressed";
            }
            if (ControllerFuncs.DPadRight.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.DPadRight && state.Buttons != GamepadButtonFlags.DPadRight)
                {
                    PerformFunction(ControllerFuncs.DPadRight);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadRightLabel.Text = "Right: released";
                }
                else
                    DPadRightLabel.Text = "Right: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.DPadRight)
                {
                    PerformFunction(ControllerFuncs.DPadRight);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadRightLabel.Text = "Right: pressed";
                }
                else
                    DPadRightLabel.Text = "Right: not pressed";
            }
            if (ControllerFuncs.DPadDown.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.DPadDown && state.Buttons != GamepadButtonFlags.DPadDown)
                {
                    PerformFunction(ControllerFuncs.DPadDown);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadDownLabel.Text = "Down: released";
                }
                else
                    DPadDownLabel.Text = "Down: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.DPadDown)
                {
                    PerformFunction(ControllerFuncs.DPadDown);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadDownLabel.Text = "Down: pressed";
                }
                else
                    DPadDownLabel.Text = "Down: not pressed";
            }
            if (ControllerFuncs.DPadLeft.State == Function.ButtonState.Released)
            {
                if (prevState.Buttons == GamepadButtonFlags.DPadLeft && state.Buttons != GamepadButtonFlags.DPadLeft)
                {
                    PerformFunction(ControllerFuncs.DPadLeft);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadLeftLabel.Text = "Left: released";
                }
                else
                    DPadLeftLabel.Text = "Left: not pressed";
            }
            else
            {
                if (state.Buttons == GamepadButtonFlags.DPadLeft)
                {
                    PerformFunction(ControllerFuncs.DPadLeft);
                    prevState.Buttons = GamepadButtonFlags.None;
                    DPadLeftLabel.Text = "Left: pressed";
                }
                else
                    DPadLeftLabel.Text = "Left: not pressed";
            }
            #endregion
        }
References BioImager.Imager.PerformFunction().
DigitsInString()
static int BioImager.Imager.DigitsInString (string str) static
It loops through the string and counts the number of times a digit is found
Parameters
str The string to be searched.
Returns
The number of digits in the string.
Definition at line 477 of file Imager.cs.
        {
            int count = 0;
            for (int i = 0; i < str.Length; i++)
            {
                if ((str[i] >= '0') && (str[i] <= '9'))
                {
                    count++;
                }
            }
            return count;
        }
Dispose()
override void BioImager.Imager.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 15 of file Imager.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
PerformFunction()
object BioImager.Imager.PerformFunction (Function f)
It takes a function object and performs the function
Parameters
Function The function to be performed
Returns
Nothing.
Definition at line 1338 of file Imager.cs.
        {
            if (f.FuncType == Function.FunctionType.Key)
            {
                if (AppP.HasExited)
                    return null;
                AppP.WaitForInputIdle();
                Win32.SetForegroundWindow(apph);
                if (f.Modifier != VirtualKeyCode.NONAME)
                {
                    input.Keyboard.ModifiedKeyStroke(f.Modifier, f.Key);
                }
                else
                {
                    input.Keyboard.KeyPress(f.Key);
                }
                return null;
            }
            if (f.FuncType == Function.FunctionType.Objective)
            {
                Objectives.Objective obj = BioImager.Microscope.Objectives.GetObjective();
                Microscope.Objectives.SetPosition((int)f.Value);
                //We set locate exposure as the locate tab is the only one that updates lightpath automatically after objective change.
                //Automation.SetProperty("LocateExposure", obj.LocateExposure.ToString());
                LJoystickStageMoveAmountBox.Value = (decimal)obj.MoveAmountL;
                RJoystickStageMoveAmountBox.Value = (decimal)obj.MoveAmountR;
                triggerFocusBox.Value = (decimal)obj.FocusMoveAmount;
                return null;
            }
            if (f.FuncType == Function.FunctionType.StoreCoordinate)
            {
                StoreCoordinate();
                return null;
            }
            if (f.FuncType == Function.FunctionType.NextCoordinate)
            {
                //If stored coordinates selected index is -1 then nothing is selected.
                //so we can't go to next stored coordinate
                if (storedCoordsBox.SelectedIndex != -1)
                {
                    //We go to the next stored coordinate
                    if (storedCoordsBox.SelectedIndex + 1 < storedCoordsBox.Items.Count)
                    {
                        Point3D p = (Point3D)storedCoordsBox.Items[storedCoordsBox.SelectedIndex + 1];
                        Microscope.SetPosition(p);
                        storedCoordsBox.SelectedIndex = storedCoordsBox.SelectedIndex + 1;
                    }
                    if (storedCoordsBox.SelectedIndex == 0)
                    {
                        Point3D p = (Point3D)storedCoordsBox.Items[storedCoordsBox.SelectedIndex];
                        Microscope.SetPosition(p);
                    }
                }
                return null;
            }
            if (f.FuncType == Function.FunctionType.PreviousCoordinate)
            {
                //We go to the previous stored coordinate unless selected index is 0
                //in which case we go to coordinate of selected point.
                //If stored coordinates selected index is -1 then nothing is selected.
                //so we can't go to next stored coordinate
                if (storedCoordsBox.SelectedIndex != -1)
                {
                    if (storedCoordsBox.SelectedIndex == 0)
                    {
                        Point3D p = (Point3D)storedCoordsBox.Items[storedCoordsBox.SelectedIndex];
                        Microscope.SetPosition(p);
                    }
                    if (storedCoordsBox.SelectedIndex > 0)
                    {
                        Point3D p = (Point3D)storedCoordsBox.Items[storedCoordsBox.SelectedIndex - 1];
                        Microscope.SetPosition(p);
                        storedCoordsBox.SelectedIndex = storedCoordsBox.SelectedIndex - 1;
                    }
                }
                return null;
            }
            if (f.FuncType == Function.FunctionType.NextSnapCoordinate)
            {
                //If stored coordinates selected index is -1 then nothing is selected.
                //so we can't go to next stored coordinate
                if (storedImageBox.SelectedIndex != -1)
                {
                    //We go to the next stored coordinate
                    if (storedImageBox.SelectedIndex + 1 < storedImageBox.Items.Count)
                    {
                        Point3D p = (Point3D)storedImageBox.Items[storedImageBox.SelectedIndex + 1];
                        Microscope.SetPosition(p);
                        storedImageBox.SelectedIndex = storedImageBox.SelectedIndex + 1;
                    }
                    if (storedImageBox.SelectedIndex == 0)
                    {
                        Point3D p = (Point3D)storedImageBox.Items[storedImageBox.SelectedIndex];
                        Microscope.SetPosition(p);
                    }
                }
                return null;
            }
            if (f.FuncType == Function.FunctionType.PreviousSnapCoordinate)
            {
                //We go to the previous stored coordinate unless selected index is 0
                //in which case we go to coordinate of selected point.
                //If stored coordinates selected index is -1 then nothing is selected.
                //so we can't go to next stored coordinate
                if (storedImageBox.SelectedIndex != -1)
                {
                    if (storedImageBox.SelectedIndex == 0)
                    {
                        Point3D p = (Point3D)storedImageBox.Items[storedImageBox.SelectedIndex];
                        Microscope.SetPosition(p);
                    }
                    if (storedImageBox.SelectedIndex > 0)
                    {
                        Point3D p = (Point3D)storedImageBox.Items[storedImageBox.SelectedIndex - 1];
                        Microscope.SetPosition(p);
                        //We stop the controller update timer so we can update the stored coordinates list it operates on safely
                        storedImageBox.SelectedIndex = storedImageBox.SelectedIndex - 1;
                    }
                }
                return null;
            }
            if (f.FuncType == Function.FunctionType.Script)
            {
                Scripting.RunScript(f.File);
            }
            if (f.FuncType == Function.FunctionType.ImageJ)
            {
                ImageJ.RunMacro(f.File, "");
            }
            if (f.FuncType.ToString() == "StageUp")
            {
                Microscope.MoveUp(f.Value);
            }
            else
            if (f.FuncType.ToString() == "StageRight")
            {
                Microscope.MoveRight(f.Value);
            }
            else
            if (f.FuncType.ToString() == "StageDown")
            {
                Microscope.MoveDown(f.Value);
            }
            else
            if (f.FuncType.ToString() == "StageLeft")
            {
                Microscope.MoveLeft(f.Value);
            }
            else
            if (f.FuncType.ToString() == "FocusUp")
            {
                Microscope.SetFocus(f.Value);
            }
            else
            if (f.FuncType.ToString() == "FocusDown")
            {
                Microscope.SetFocus(-f.Value);
            }
            else
            if (f.FuncType.ToString() == "StageFieldUp")
            {
                Microscope.MoveFieldUp();
            }
            else
            if (f.FuncType.ToString() == "StageFieldRight")
            {
                Microscope.MoveFieldRight();
            }
            else
            if (f.FuncType.ToString() == "StageFieldDown")
            {
                Microscope.MoveFieldDown();
            }
            else
            if (f.FuncType.ToString() == "StageFieldLeft")
            {
                Microscope.MoveFieldLeft();
            }
            else
            if (f.FuncType.ToString() == "TakeImage")
            {
                Microscope.TakeImage();
                }
                else
                if (f.FuncType.ToString() == "TakeImageStack")
                {
                    Microscope.TakeImageStack();
                }
                else
                if (f.FuncType.ToString() == "RL")
                {
                    Microscope.RLShutter.SetPosition((int)f.Value);
                }
                else
                if (f.FuncType.ToString() == "TL")
                {
                    Microscope.TLShutter.SetPosition((int)f.Value);
                }
            if (f.FuncType == Function.FunctionType.Property)
            {
                if (f.Name.StartsWith("Get"))
                {
                    Automation.Recording r = (Automation.Recording)Automation.Properties[Path.GetFileNameWithoutExtension(f.File)];
                    return r.Get();
                }
                else if (f.Name.StartsWith("Set"))
                {
                    Automation.Recording r = (Automation.Recording)Automation.Properties[Path.GetFileNameWithoutExtension(f.File)];
                    r.Set(f.Value.ToString());
                }
            }
            if (f.FuncType == Function.FunctionType.Recording)
            {
                Automation.Recording r = (Automation.Recording)Automation.Recordings[Path.GetFileNameWithoutExtension(f.File)];
                r.Run();
            }
            return null;
        }
References BioImager.ImageJ.RunMacro(), and BioImager.Scripting.RunScript().
Referenced by BioImager.Imager.CheckGamepadButtons(), BioImager.Function.PerformFunction(), and BioImager.Objectives.SetPosition().
StoreCoordinate()
void BioImager.Imager.StoreCoordinate ()
Definition at line 263 of file Imager.cs.
        {
            Point3D p3 = Microscope.GetPosition();
            storedCoordsBox.Items.Add(p3);
            storedCoordsBox.SelectedIndex = storedCoordsBox.Items.Count - 1;
        }
UpdateStatus()
void BioImager.Imager.UpdateStatus ()
"If the number of images in the list is greater than the number of items in the listbox, add the difference to the listbox."
This is a very simple function, but it's a good example of how to add items to a listbox
Returns
The return type is void, so nothing is being returned.
Definition at line 243 of file Imager.cs.
        {
            //GetLiveStatus();
            if (AppP.HasExited)
                return;
            Point3D p = Microscope.GetPosition();
            double f = Microscope.GetFocus();
            Point3D point = new Point3D(p.X, p.Y, f);
            statusLabel.Text = "Stage: " + p.X + " , " + p.Y + " Focus: " + f;
            if (StoredImages.Count > storedImageBox.Items.Count)
            {
                int dif = StoredImages.Count - storedImageBox.Items.Count;
                for (int i = 0; i < dif; i++)
                {
                    int index = (StoredImages.Count - 1) + dif;
                    storedImageBox.Items.Add(StoredImages[index - 1]);
                }
            }
        }
Member Data Documentation
apph
IntPtr BioImager.Imager.apph static
Definition at line 26 of file Imager.cs.
AppPath
string BioImager.Imager.AppPath = "" static
Definition at line 28 of file Imager.cs.
connected
bool BioImager.Imager.connected = false
Definition at line 33 of file Imager.cs.
controller
Controller BioImager.Imager.controller
Definition at line 30 of file Imager.cs.
CurrentProfile
Profile BioImager.Imager.CurrentProfile = new Profile("Default")
Definition at line 84 of file Imager.cs.
deadzone
int BioImager.Imager.deadzone = 5
Definition at line 35 of file Imager.cs.
gamepad
Gamepad BioImager.Imager.gamepad
Definition at line 31 of file Imager.cs.
input
InputSimulator BioImager.Imager.input = new InputSimulator() static
Definition at line 1331 of file Imager.cs.
leftTrigger
float BioImager.Imager.leftTrigger
Definition at line 34 of file Imager.cs.
liveStatus
? bool BioImager.Imager.liveStatus = null static
Definition at line 270 of file Imager.cs.
m_ID
string BioImager.Imager.m_ID
Definition at line 37 of file Imager.cs.
previousGamepadState
Gamepad BioImager.Imager.previousGamepadState
Definition at line 31 of file Imager.cs.
prevState
bool BioImager.Imager.prevState = false
Definition at line 32 of file Imager.cs.
rightTrigger
float BioImager.Imager.rightTrigger
Definition at line 34 of file Imager.cs.
StoredImages
List<BioImage> BioImager.Imager.StoredImages = new List<BioImage>() static
Definition at line 29 of file Imager.cs.
Property Documentation
ID
string BioImager.Imager.ID get
Definition at line 38 of file Imager.cs.
ImagesPerSlice
uint BioImager.Imager.ImagesPerSlice get set
Definition at line 50 of file Imager.cs.
        {
            get
            {
                return (uint)imagesPerSliceBox.Value;
            }
            set
            {
                imagesPerSliceBox.Value = (decimal)value;
            }
        }
SliceIncrement
uint BioImager.Imager.SliceIncrement get set
Definition at line 61 of file Imager.cs.
        {
            get
            {
                return (uint)sliceIncrementBox.Value;
            }
            set
            {
                sliceIncrementBox.Value = (decimal)value;
            }
        }
SlicesPerSlide
uint BioImager.Imager.SlicesPerSlide get set
Definition at line 72 of file Imager.cs.
        {
            get
            {
                return (uint)slicesPerSlideBox.Value;
            }
            set
            {
                slicesPerSlideBox.Value = (decimal)value;
            }
        }
ZenP
Process BioImager.Imager.ZenP static get set
Definition at line 39 of file Imager.cs.
        {
            get
            {
                return AppP;
            }
            set
            {
                AppP = value;
            }
        }
The documentation for this class was generated from the following files:
F:/repos/BioImager/BioImager/Source/Imager.cs
F:/repos/BioImager/BioImager/Source/Imager.Designer.cs