BioImager: BioImager.Tools Class Reference
BioImager.Tools Class Reference
Classes
class Tool
Public Member Functions
void UpdateOverlay ()
void UpdateView ()
void UpdateSelected ()
void ToolDown (PointD e, MouseButtons buts)
void ToolUp (PointD e, MouseButtons buts)
void ToolMove (PointD e, MouseButtons buts)
Static Public Member Functions
static Tool GetTool (string name)
static Tool GetTool (Tool.Type typ)
Public Attributes
Font font
Static Public Attributes
static bool applyToStack = false
static ColorTool colorTool
static bool rEnabled = true
static bool gEnabled = true
static bool bEnabled = true
static System.Drawing.Rectangle selectionRectangle
static Hashtable tools = new Hashtable()
static Tool currentTool
static RectangleD selectionRect
static float selectBoxSize = ROI.selectBoxSize
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
static ColorS DrawColor [get, set]
static ColorS EraseColor [get, set]
static int StrokeWidth [get, set]
Detailed Description
Definition at line 23 of file Tools.cs.
Constructor & Destructor Documentation
Tools()
BioImager.Tools.Tools ()
Definition at line 168 of file Tools.cs.
        {
            InitializeComponent();
            Tool.Init();
            ColorS col = new ColorS(ushort.MaxValue);
            //We initialize the tools
            currentTool = GetTool(Tool.Type.move);
            floodFiller = null;
            floodFiller = new QueueLinearFloodFiller(floodFiller);
        }
Member Function Documentation
Dispose()
override void BioImager.Tools.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file Tools.Designer.cs.
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
GetTool() [1/2]
static Tool BioImager.Tools.GetTool (string name) static
Definition at line 180 of file Tools.cs.
        {
            return (Tool)tools[name];
        }
GetTool() [2/2]
static Tool BioImager.Tools.GetTool (Tool.Type typ) static
Definition at line 184 of file Tools.cs.
        {
            return (Tool)tools[typ.ToString()];
        }
ToolDown()
void BioImager.Tools.ToolDown (PointD e, MouseButtons buts)
The function is called when the user clicks the mouse button.
The function checks if the user is using the line, polygon, freeform, rectangle, ellipse, delete, or text tool.
If the user is using the line tool, the function creates a new ROI object and adds it to the image's annotations.
If the user is using the polygon tool, the function creates a new ROI object and adds it to the image's annotations.
If the user is using the freeform tool, the function creates a new ROI object and adds it to the image's annotations.
If the user is using the rectangle tool, the function creates a new ROI object and adds it to the image's annotations.
If the user is using the ellipse tool, the function creates a new ROI object and adds it to the image's annotations.
If
Parameters
PointD A point with double precision
MouseButtons A set of values that indicate which mouse button was pressed.
Returns
The return type is void.
Definition at line 245 of file Tools.cs.
        {
            if (App.viewer == null || currentTool == null || ImageView.SelectedImage == null)
                return;
            Scripting.UpdateState(Scripting.State.GetDown(e, buts));
            PointD p;
            if(ImageView.SelectedImage!=null)
            if (App.viewer.HardwareAcceleration)
                p = ImageView.SelectedImage.ToImageSpace(new PointD(ImageView.SelectedImage.Volume.Width - e.X, ImageView.SelectedImage.Volume.Height - e.Y));
            else
                p = ImageView.SelectedImage.ToImageSpace(e);
            if (currentTool.type == Tool.Type.line && buts == MouseButtons.Left)
            {
                if (anno.GetPointCount() == 0)
                {
                    anno = new ROI();
                    anno.type = ROI.Type.Line;
                    anno.AddPoint(new PointD(e.X, e.Y));
                    anno.AddPoint(new PointD(e.X, e.Y));
                    anno.coord = App.viewer.GetCoordinate();
                    ImageView.SelectedImage.Annotations.Add(anno);
                }
            }
            else
            if (currentTool.type == Tool.Type.polygon && buts == MouseButtons.Left)
            {
                if (anno.GetPointCount() == 0)
                {
                    anno = new ROI();
                    anno.type = ROI.Type.Polygon;
                    anno.AddPoint(new PointD(e.X, e.Y));
                    anno.coord = App.viewer.GetCoordinate();
                    ImageView.SelectedImage.Annotations.Add(anno);
                }
                else
                {
                    //If we click on a point 1 we close this polygon
                    RectangleD d = new RectangleD(e.X, e.Y, ROI.selectBoxSize, ROI.selectBoxSize);
                    if (d.IntersectsWith(anno.Point))
                    {
                        anno.closed = true;
                        anno = new ROI();
                    }
                    else
                    {
                        anno.AddPoint(new PointD(e.X, e.Y));
                    }
                }
            }
            else
            if (currentTool.type == Tool.Type.freeform && buts == MouseButtons.Left)
            {
                if (anno.GetPointCount() == 0)
                {
                    anno = new ROI();
                    anno.type = ROI.Type.Freeform;
                    anno.AddPoint(new PointD(e.X, e.Y));
                    anno.coord = App.viewer.GetCoordinate();
                    anno.closed = true;
                    ImageView.SelectedImage.Annotations.Add(anno);
                }
                else
                {
                    anno.AddPoint(new PointD(e.X, e.Y));
                }
            }
            else
            if (currentTool.type == Tool.Type.rect && buts == MouseButtons.Left)
            {
                anno.type = ROI.Type.Rectangle;
                anno.Rect = new RectangleD(e.X, e.Y, 1, 1);
                anno.coord = App.viewer.GetCoordinate();
                ImageView.SelectedImage.Annotations.Add(anno);
            }
            else
            if (currentTool.type == Tool.Type.ellipse && buts == MouseButtons.Left)
            {
                anno.type = ROI.Type.Ellipse;
                anno.Rect = new RectangleD(e.X, e.Y, 1, 1);
                anno.coord = App.viewer.GetCoordinate();
                ImageView.SelectedImage.Annotations.Add(anno);
            }
            else
            if (currentTool.type == Tool.Type.delete && buts == MouseButtons.Left)
            {
                for (int i = 0; i < ImageView.SelectedImage.Annotations.Count; i++)
                {
                    ROI an = ImageView.SelectedImage.Annotations[i];
                    if (an.BoundingBox.IntersectsWith(e.X, e.Y))
                    {
                        if (an.selectedPoints.Count == 0)
{
                            ImageView.SelectedImage.Annotations.Remove(an);
                            break;
                        }
                        else
                        if (an.selectedPoints.Count == 1 && !(an.type == ROI.Type.Polygon || an.type == ROI.Type.Polyline || an.type == ROI.Type.Freeform))
{
                            ImageView.SelectedImage.Annotations.Remove(an);
                            break;
                        }
                        else
{
                            if (an.type == ROI.Type.Polygon ||
                                an.type == ROI.Type.Polyline ||
                                an.type == ROI.Type.Freeform)
{
                                an.closed = false;
                                an.RemovePoints(an.selectedPoints.ToArray());
                                break;
                            }
                        }
                    }
                }
                UpdateOverlay();
            }
            else
            if (currentTool.type == Tool.Type.text && buts == MouseButtons.Left)
            {
                ROI an = new ROI();
                an.type = ROI.Type.Label;
                an.AddPoint(new PointD(e.X, e.Y));
                an.coord = App.viewer.GetCoordinate();
                TextInput ti = new TextInput("");
                if (ti.ShowDialog() != DialogResult.OK)
                    return;
                an.font = new Font(ti.font.FontFamily, ti.font.Size);
                an.strokeColor = ti.color;
                an.Text = ti.TextValue;
                ImageView.SelectedImage.Annotations.Add(an);
            }
            else
            if (buts == MouseButtons.Middle || currentTool.type == Tool.Type.pan)
            {
                currentTool = GetTool(Tool.Type.pan);
                UpdateSelected();
                panPanel.BackColor = System.Drawing.Color.LightGray;
                Cursor.Current = Cursors.Hand;
            }
            UpdateOverlay();
        }
References BioImager.ROI.AddPoint(), BioImager.ImageView.GetCoordinate(), BioImager.Scripting.State.GetDown(), BioImager.ROI.GetPointCount(), BioImager.ImageView.HardwareAcceleration, BioImager.ROI.RemovePoints(), BioImager.BioImage.ToImageSpace(), BioImager.Tools.UpdateSelected(), and BioImager.Scripting.UpdateState().
ToolMove()
void BioImager.Tools.ToolMove (PointD e, MouseButtons buts)
Definition at line 550 of file Tools.cs.
        {
            if (App.viewer == null)
                return;
            Scripting.UpdateState(Scripting.State.GetMove(e, buts));
            if (Tools.currentTool.type == Tools.Tool.Type.pan && buts == MouseButtons.Left || buts == MouseButtons.Middle)
            {
                PointD pf = new PointD(e.X - ImageView.mouseDown.X, e.Y - ImageView.mouseDown.Y);
                App.viewer.Origin = new PointD(App.viewer.Origin.X + pf.X, App.viewer.Origin.Y + pf.Y);
                UpdateView();
            }
            if (ImageView.SelectedImage == null)
                return;
            PointD p;
            if (App.viewer.HardwareAcceleration)
                p = ImageView.SelectedImage.ToImageSpace(new PointD(ImageView.SelectedImage.Volume.Width - e.X, ImageView.SelectedImage.Volume.Height - e.Y));
            else
                p = ImageView.SelectedImage.ToImageSpace(e);
            if (currentTool.type == Tool.Type.line && ImageView.down)
            {
                anno.UpdatePoint(new PointD(e.X, e.Y), 1);
                UpdateOverlay();
            }
            else
            if (currentTool.type == Tool.Type.freeform && buts == MouseButtons.Left && ImageView.down)
            {
                if (anno.GetPointCount() == 0)
                {
                    anno.type = ROI.Type.Freeform;
                    anno.AddPoint(new PointD(e.X, e.Y));
                    anno.coord = App.viewer.GetCoordinate();
                    anno.closed = true;
                    ImageView.SelectedImage.Annotations.Add(anno);
                }
                else
                {
                    anno.AddPoint(new PointD(e.X, e.Y));
                }
                UpdateOverlay();
            }
            else
            if (currentTool.type == Tool.Type.rect && anno.type == ROI.Type.Rectangle)
            {
                if (anno.GetPointCount() == 4)
                {
                    anno.Rect = new RectangleD(anno.X, anno.Y, e.X - anno.X, e.Y - anno.Y);
                    UpdateOverlay();
                }
            }
            else
            if (currentTool.type == Tool.Type.ellipse && anno.type == ROI.Type.Ellipse)
            {
                if (anno.GetPointCount() == 4)
                {
                    anno.Rect = new RectangleD(anno.X, anno.Y, e.X - anno.X, e.Y - anno.Y);
                    UpdateOverlay();
                }
            }
            else
            if (currentTool.type == Tool.Type.rectSel && buts == MouseButtons.Left && ImageView.down)
            {
                PointD d = new PointD(e.X - ImageView.mouseDown.X, e.Y - ImageView.mouseDown.Y);
                Tools.GetTool(Tools.Tool.Type.rectSel).Rectangle = new RectangleD(ImageView.mouseDown.X, ImageView.mouseDown.Y, d.X, d.Y);
                RectangleD r = Tools.GetTool(Tools.Tool.Type.rectSel).Rectangle;
                foreach (ROI an in App.viewer.AnnotationsRGB)
                {
                    if (an.GetSelectBound(App.viewer.GetScale(), App.viewer.GetScale()).IntersectsWith(r))
                    {
                        an.selectedPoints.Clear();
                        ImageView.selectedAnnotations.Add(an);
                        an.selected = true;
                        RectangleD[] sels = an.GetSelectBoxes(selectBoxSize);
                        for (int i = 0; i < sels.Length; i++)
{
                            if (sels[i].IntersectsWith(r))
{
                                an.selectedPoints.Add(i);
                            }
                        }
                    }
                    else
                        an.selected = false;
                }
                UpdateOverlay();
            }
            else
            if (currentTool.type == Tool.Type.rectSel && ImageView.up)
            {
                Tools.GetTool(Tools.Tool.Type.rectSel).Rectangle = new RectangleD(0, 0, 0, 0);
            }
            else
            if (Win32.GetKeyState(Keys.Delete))
            {
                foreach (ROI an in ImageView.selectedAnnotations)
                {
                    if (an != null)
                    {
                        if (an.selectedPoints.Count == 0)
{
                            ImageView.SelectedImage.Annotations.Remove(an);
                        }
                        else
{
                            if (an.type == ROI.Type.Polygon ||
                                an.type == ROI.Type.Polyline ||
                                an.type == ROI.Type.Freeform)
{
                                an.closed = false;
                                an.RemovePoints(an.selectedPoints.ToArray());
                            }
                        }
                    }
                }
                UpdateOverlay();
            }
            if (Tools.currentTool.type == Tools.Tool.Type.magic && buts == MouseButtons.Left)
            {
                //First we draw the selection rectangle
                PointD d = new PointD(e.X - ImageView.mouseDown.X, e.Y - ImageView.mouseDown.Y);
                Tools.GetTool(Tools.Tool.Type.rectSel).Rectangle = new RectangleD(ImageView.mouseDown.X, ImageView.mouseDown.Y, d.X, d.Y);
                UpdateOverlay();
            }
            if (buts == MouseButtons.Left && currentTool.type == Tool.Type.eraser)
            {
                Graphics.Graphics g = Graphics.Graphics.FromImage(ImageView.SelectedBuffer);
                Graphics.Pen pen = new Graphics.Pen(Tools.EraseColor, (int)Tools.StrokeWidth, ImageView.SelectedBuffer.BitsPerPixel);
                g.FillEllipse(new Rectangle((int)p.X, (int)p.Y, (int)width, (int)Tools.StrokeWidth), pen.color);
                pen.Dispose();
                App.viewer.UpdateImage();
            }
        }
ToolUp()
void BioImager.Tools.ToolUp (PointD e, MouseButtons buts)
The function ToolUp() is called when the mouse button is released
Parameters
PointD X,Y
MouseButtons Left, Right, Middle, XButton1, XButton2
Returns
a RectangleF.
Definition at line 393 of file Tools.cs.
        {
            PointD p = new PointD();
            if(ImageView.SelectedImage != null)
            if (App.viewer.HardwareAcceleration)
                p = ImageView.SelectedImage.ToImageSpace(new PointD(ImageView.SelectedImage.Volume.Width - e.X, ImageView.SelectedImage.Volume.Height - e.Y));
            else
                p = ImageView.SelectedImage.ToImageSpace(e);
            if (App.viewer == null || currentTool == null || ImageView.SelectedImage == null || anno == null)
                return;
            Scripting.UpdateState(Scripting.State.GetUp(e, buts));
            if (currentTool.type == Tool.Type.point && buts == MouseButtons.Left)
            {
                ROI an = new ROI();
                an.AddPoint(new PointD(e.X, e.Y));
                an.type = ROI.Type.Point;
                an.coord = App.viewer.GetCoordinate();
                ImageView.SelectedImage.Annotations.Add(an);
            }
            else
            if (currentTool.type == Tool.Type.line && anno.type == ROI.Type.Line && buts == MouseButtons.Left)
            {
                if (anno.GetPointCount() > 0)
                {
                    anno.UpdatePoint(new PointD(e.X, e.Y), 1);
                    anno = new ROI();
                }
            }
            else
            if (currentTool.type == Tool.Type.rect && anno.type == ROI.Type.Rectangle && buts == MouseButtons.Left)
            {
                if (anno.GetPointCount() == 4)
                {
                    anno = new ROI();
                }
            }
            else
            if (currentTool.type == Tool.Type.ellipse && anno.type == ROI.Type.Ellipse && buts == MouseButtons.Left)
            {
                if (anno.GetPointCount() == 4)
                {
                    anno = new ROI();
                }
            }
            else
            if (currentTool.type == Tool.Type.freeform && anno.type == ROI.Type.Freeform && buts == MouseButtons.Left)
            {
                anno = new ROI();
            }
            else
            if (currentTool.type == Tool.Type.rectSel && buts == MouseButtons.Left)
            {
                ImageView.selectedAnnotations.Clear();
                RectangleD r = GetTool(Tool.Type.rectSel).Rectangle;
                foreach (ROI an in App.viewer.AnnotationsRGB)
                {
                    if (an.GetSelectBound(App.viewer.GetScale(), App.viewer.GetScale()).ToRectangleF().IntersectsWith(r.ToRectangleF()))
                    {
                        an.selectedPoints.Clear();
                        ImageView.selectedAnnotations.Add(an);
                        an.selected = true;
                        RectangleD[] sels = an.GetSelectBoxes(selectBoxSize);
                        for (int i = 0; i < sels.Length; i++)
{
                            if (sels[i].IntersectsWith(r))
{
                                an.selectedPoints.Add(i);
                            }
                        }
                    }
                    else
                        an.selected = false;
                }
                Tools.GetTool(Tools.Tool.Type.rectSel).Rectangle = new RectangleD(0, 0, 0, 0);
            }
            else
            if (Tools.currentTool.type == Tools.Tool.Type.magic && buts == MouseButtons.Left)
            {
                PointD pf = new PointD(ImageView.mouseUp.X - ImageView.mouseDown.X, ImageView.mouseUp.Y - ImageView.mouseDown.Y);
                ZCT coord = App.viewer.GetCoordinate();
                Rectangle r = new Rectangle((int)ImageView.mouseDown.X, (int)ImageView.mouseDown.Y, (int)(ImageView.mouseUp.X - ImageView.mouseDown.X), (int)(ImageView.mouseUp.Y - ImageView.mouseDown.Y));
                if (r.Width <= 2 || r.Height <= 2)
                    return;
                Bitmap bf = ImageView.SelectedImage.Buffers[ImageView.SelectedImage.Coords[coord.Z, coord.C, coord.T]].GetCropBuffer(r);
                Statistics[] sts = Statistics.FromBytes(bf);
                Statistics st = sts[0];
                Threshold th;
                if (magicSel.Numeric)
                {
                    th = new Threshold((int)magicSel.Threshold);
                }
                else
                if (magicSel.Index == 2)
                    th = new Threshold((int)(st.Min + st.Mean));
                else
                if (magicSel.Index == 1)
                    th = new Threshold((int)st.Median);
                else
                    th = new Threshold(st.Min);
                th.ApplyInPlace((Bitmap)bf.Image);
                Invert inv = new Invert();
                Bitmap det;
                if (bf.BitsPerPixel > 8)
                    det = AForge.Imaging.Image.Convert16bppTo8bpp((Bitmap)bf.Image);
                else
                    det = (Bitmap)bf.Image;
                BlobCounter blobCounter = new BlobCounter();
                blobCounter.ProcessImage(det);
                Blob[] blobs = blobCounter.GetObjectsInformation();
                // create convex hull searching algorithm
                GrahamConvexHull hullFinder = new GrahamConvexHull();
                // lock image to draw on it
                // process each blob
                foreach (Blob blob in blobs)
                {
                    if (blob.Rectangle.Width < magicSel.Max && blob.Rectangle.Height < magicSel.Max)
                        continue;
                    List<IntPoint> leftPoints = new List<IntPoint>();
                    List<IntPoint> rightPoints = new List<IntPoint>();
                    List<IntPoint> edgePoints = new List<IntPoint>();
                    List<IntPoint> hull = new List<IntPoint>();
                    // get blob's edge points
                    blobCounter.GetBlobsLeftAndRightEdges(blob,
                        out leftPoints, out rightPoints);
                    edgePoints.AddRange(leftPoints);
                    edgePoints.AddRange(rightPoints);
                    // blob's convex hull
                    hull = hullFinder.FindHull(edgePoints);
                    PointD[] pfs = new PointD[hull.Count];
                    for (int i = 0; i < hull.Count; i++)
                    {
                        pfs[i] = new PointD(r.X + hull[i].X, r.Y + hull[i].Y);
                    }
                    ROI an = ROI.CreateFreeform(coord, pfs);
                    ImageView.SelectedImage.Annotations.Add(an);
                }
            }
            else
            if (Tools.currentTool.type == Tools.Tool.Type.bucket && buts == MouseButtons.Left)
            {
                ZCT coord = App.viewer.GetCoordinate();
                floodFiller.FillColor = DrawColor;
                floodFiller.Tolerance = currentTool.tolerance;
                floodFiller.Bitmap = ImageView.SelectedImage.Buffers[ImageView.SelectedImage.Coords[coord.C, coord.Z, coord.T]];
                floodFiller.FloodFill(new AForge.Point((int)p.X, (int)p.Y));
                App.viewer.UpdateImages();
            }
            else
            if (Tools.currentTool.type == Tools.Tool.Type.dropper && buts == MouseButtons.Left)
            {
                DrawColor = ImageView.SelectedBuffer.GetPixel((int)p.X, (int)p.Y);
                UpdateGUI();
            }
            UpdateOverlay();
        }
References BioImager.ROI.AddPoint(), BioImager.ROI.CreateFreeform(), BioImager.ImageView.GetCoordinate(), BioImager.ROI.GetPointCount(), BioImager.ImageView.GetScale(), BioImager.ROI.GetSelectBound(), BioImager.ROI.GetSelectBoxes(), BioImager.Scripting.State.GetUp(), BioImager.ImageView.HardwareAcceleration, BioImager.BioImage.ToImageSpace(), BioImager.ImageView.UpdateImages(), BioImager.ROI.UpdatePoint(), and BioImager.Scripting.UpdateState().
UpdateOverlay()
void BioImager.Tools.UpdateOverlay ()
Definition at line 188 of file Tools.cs.
        {
            App.viewer.UpdateOverlay();
        }
UpdateSelected()
void BioImager.Tools.UpdateSelected ()
It loops through all the controls in the form and if the control has a tag of "tool" it sets the background color to white
Definition at line 198 of file Tools.cs.
        {
            foreach (Control item in this.Controls)
            {
                if (item.Tag != null)
                    if (item.Tag.ToString() == "tool")
                        item.BackColor = System.Drawing.Color.White;
            }
        }
Referenced by BioImager.Tools.ToolDown().
UpdateView()
void BioImager.Tools.UpdateView ()
Definition at line 192 of file Tools.cs.
        {
            App.viewer.UpdateView();
        }
Member Data Documentation
applyToStack
bool BioImager.Tools.applyToStack = false static
Definition at line 25 of file Tools.cs.
bEnabled
bool BioImager.Tools.bEnabled = true static
Definition at line 29 of file Tools.cs.
colorTool
ColorTool BioImager.Tools.colorTool static
Definition at line 26 of file Tools.cs.
currentTool
Tool BioImager.Tools.currentTool static
Definition at line 128 of file Tools.cs.
font
Font BioImager.Tools.font
Definition at line 166 of file Tools.cs.
gEnabled
bool BioImager.Tools.gEnabled = true static
Definition at line 28 of file Tools.cs.
rEnabled
bool BioImager.Tools.rEnabled = true static
Definition at line 27 of file Tools.cs.
selectBoxSize
float BioImager.Tools.selectBoxSize = ROI.selectBoxSize static
Definition at line 217 of file Tools.cs.
selectionRect
RectangleD BioImager.Tools.selectionRect static
Definition at line 165 of file Tools.cs.
selectionRectangle
System.Drawing.Rectangle BioImager.Tools.selectionRectangle static
Definition at line 34 of file Tools.cs.
tools
Hashtable BioImager.Tools.tools = new Hashtable() static
Definition at line 35 of file Tools.cs.
Property Documentation
DrawColor
ColorS BioImager.Tools.DrawColor static get set
Definition at line 129 of file Tools.cs.
        {
            get
            {
                return drawColor;
            }
            set
            {
                drawColor = value;
            }
        }
EraseColor
ColorS BioImager.Tools.EraseColor static get set
Definition at line 140 of file Tools.cs.
        {
            get
            {
                return eraseColor;
            }
            set
            {
                eraseColor = value;
            }
        }
StrokeWidth
int BioImager.Tools.StrokeWidth static get set
Definition at line 152 of file Tools.cs.
        {
            get
            {
                return width;
            }
            set
            {
                width = value;
                App.tools.UpdateGUI();
            }
        }
The documentation for this class was generated from the following files:
F:/repos/BioImager/BioImager/Source/Tools.cs
F:/repos/BioImager/BioImager/Source/Tools.Designer.cs