var hierarchy =
[
    [ "Bio.Graphics.AbstractFloodFiller", "class_bio_1_1_graphics_1_1_abstract_flood_filler.html", [
      [ "Bio.Graphics.QueueLinearFloodFiller", "class_bio_1_1_graphics_1_1_queue_linear_flood_filler.html", null ]
    ] ],
    [ "BioGTK.ImageJ.Macro.Command", "class_bio_g_t_k_1_1_image_j_1_1_macro_1_1_command.html", null ],
    [ "Gtk.Dialog", null, [
      [ "BioGTK.ApplyFilter", "class_bio_g_t_k_1_1_apply_filter.html", null ],
      [ "BioGTK.ColorTool", "class_bio_g_t_k_1_1_color_tool.html", null ],
      [ "BioGTK.ComboPicker", "class_bio_g_t_k_1_1_combo_picker.html", null ],
      [ "BioGTK.NumberPicker", "class_bio_g_t_k_1_1_number_picker.html", null ],
      [ "BioGTK.Progress", "class_bio_g_t_k_1_1_progress.html", null ],
      [ "BioGTK.Resolutions", "class_bio_g_t_k_1_1_resolutions.html", null ],
      [ "BioGTK.TextInput", "class_bio_g_t_k_1_1_text_input.html", null ],
      [ "BioGTK.Tolerance", "class_bio_g_t_k_1_1_tolerance.html", null ]
    ] ],
    [ "BioGTK.Filt", "class_bio_g_t_k_1_1_filt.html", null ],
    [ "Bio.Graphics.FloodFillRange", "struct_bio_1_1_graphics_1_1_flood_fill_range.html", null ],
    [ "Bio.Graphics.FloodFillRangeQueue", "class_bio_1_1_graphics_1_1_flood_fill_range_queue.html", null ],
    [ "BioGTK.Focus", "class_bio_g_t_k_1_1_focus.html", null ],
    [ "BioGTK.Function", "class_bio_g_t_k_1_1_function.html", null ],
    [ "BioGTK.ImageJ.Macro.Function", "class_bio_g_t_k_1_1_image_j_1_1_macro_1_1_function.html", null ],
    [ "BioGTK.QuPath.GeoJsonFeature", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_feature.html", null ],
    [ "BioGTK.QuPath.GeoJsonFeatureCollection", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_feature_collection.html", null ],
    [ "BioGTK.QuPath.GeoJsonGeometry", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_geometry.html", null ],
    [ "BioGTK.QuPath.GeoJsonLineString", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_line_string.html", null ],
    [ "BioGTK.QuPath.GeoJsonGeometry.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_geometry_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonLineString.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_line_string_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonPoint.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_point_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonPolygon.GeoJsonPlane", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_polygon_1_1_geo_json_plane.html", null ],
    [ "BioGTK.QuPath.GeoJsonPoint", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_point.html", null ],
    [ "BioGTK.QuPath.GeoJsonPolygon", "class_bio_g_t_k_1_1_qu_path_1_1_geo_json_polygon.html", null ],
    [ "IDisposable", null, [
      [ "Bio.Graphics.Graphics", "class_bio_1_1_graphics_1_1_graphics.html", null ],
      [ "Bio.Graphics.Pen", "struct_bio_1_1_graphics_1_1_pen.html", null ],
      [ "BioGTK.BioImage", "class_bio_g_t_k_1_1_bio_image.html", null ],
      [ "BioGTK.ROI", "class_bio_g_t_k_1_1_r_o_i.html", null ],
      [ "BioGTK.ROI.Mask", "class_bio_g_t_k_1_1_r_o_i_1_1_mask.html", null ]
    ] ],
    [ "BioGTK.ImageInfo", "class_bio_g_t_k_1_1_image_info.html", null ],
    [ "BioGTK.BioImage.ImageJDesc", "class_bio_g_t_k_1_1_bio_image_1_1_image_j_desc.html", null ],
    [ "BioGTK.Plugin.IPlugin", "interface_bio_g_t_k_1_1_plugin_1_1_i_plugin.html", null ],
    [ "BioGTK.Objectives.Objective", "class_bio_g_t_k_1_1_objectives_1_1_objective.html", null ],
    [ "BioGTK.Objectives", "class_bio_g_t_k_1_1_objectives.html", null ],
    [ "BioGTK.Plugin", "class_bio_g_t_k_1_1_plugin.html", null ],
    [ "BioGTK.QuPath.Properties", "class_bio_g_t_k_1_1_qu_path_1_1_properties.html", null ],
    [ "BioGTK.QuPath", "class_bio_g_t_k_1_1_qu_path.html", null ],
    [ "BioGTK.RectangleD", "struct_bio_g_t_k_1_1_rectangle_d.html", null ],
    [ "BioGTK.Resolution", "struct_bio_g_t_k_1_1_resolution.html", null ],
    [ "BioGTK.RLShutter", "class_bio_g_t_k_1_1_r_l_shutter.html", null ],
    [ "BioGTK.ImageJ.RoiDecoder", "class_bio_g_t_k_1_1_image_j_1_1_roi_decoder.html", null ],
    [ "BioGTK.ImageJ.RoiEncoder", "class_bio_g_t_k_1_1_image_j_1_1_roi_encoder.html", null ],
    [ "BioGTK.Scripting.Script", "class_bio_g_t_k_1_1_scripting_1_1_script.html", null ],
    [ "BioGTK.Stage", "class_bio_g_t_k_1_1_stage.html", null ],
    [ "BioGTK.Scripting.State", "class_bio_g_t_k_1_1_scripting_1_1_state.html", null ],
    [ "BioGTK.TLShutter", "class_bio_g_t_k_1_1_t_l_shutter.html", null ],
    [ "BioGTK.Tools.Tool", "class_bio_g_t_k_1_1_tools_1_1_tool.html", null ],
    [ "Gtk.Window", null, [
      [ "BioGTK.About", "class_bio_g_t_k_1_1_about.html", null ],
      [ "BioGTK.BioConsole", "class_bio_g_t_k_1_1_bio_console.html", null ],
      [ "BioGTK.ChannelsTool", "class_bio_g_t_k_1_1_channels_tool.html", null ],
      [ "BioGTK.FiltersView", "class_bio_g_t_k_1_1_filters_view.html", null ],
      [ "BioGTK.Functions", "class_bio_g_t_k_1_1_functions.html", null ],
      [ "BioGTK.HistogramControl", "class_bio_g_t_k_1_1_histogram_control.html", null ],
      [ "BioGTK.ImageView", "class_bio_g_t_k_1_1_image_view.html", null ],
      [ "BioGTK.NodeView", "class_bio_g_t_k_1_1_node_view.html", null ],
      [ "BioGTK.Play", "class_bio_g_t_k_1_1_play.html", null ],
      [ "BioGTK.Plot", "class_bio_g_t_k_1_1_plot.html", null ],
      [ "BioGTK.Recorder", "class_bio_g_t_k_1_1_recorder.html", null ],
      [ "BioGTK.Scripting", "class_bio_g_t_k_1_1_scripting.html", null ],
      [ "BioGTK.Search", "class_bio_g_t_k_1_1_search.html", null ],
      [ "BioGTK.SetTool", "class_bio_g_t_k_1_1_set_tool.html", null ],
      [ "BioGTK.StackTools", "class_bio_g_t_k_1_1_stack_tools.html", null ],
      [ "BioGTK.TabsView", "class_bio_g_t_k_1_1_tabs_view.html", null ],
      [ "BioGTK.Tools", "class_bio_g_t_k_1_1_tools.html", null ]
    ] ],
    [ "Window", null, [
      [ "Bio.MagicSelect", "class_bio_1_1_magic_select.html", null ],
      [ "Bio.ROIManager", "class_bio_1_1_r_o_i_manager.html", null ]
    ] ]
];