var hierarchy =
[
    [ "BioImager.AbstractFloodFiller", "class_bio_imager_1_1_abstract_flood_filler.html", [
      [ "BioImager.QueueLinearFloodFiller", "class_bio_imager_1_1_queue_linear_flood_filler.html", null ]
    ] ],
    [ "BioImager.Automation.Action", "class_bio_imager_1_1_automation_1_1_action.html", null ],
    [ "BioImager.App", "class_bio_imager_1_1_app.html", null ],
    [ "BioImager.Automation", "class_bio_imager_1_1_automation.html", null ],
    [ "BioImager.MicroscopeConsole.Command", "struct_bio_imager_1_1_microscope_console_1_1_command.html", null ],
    [ "BioImager.Configuration", "class_bio_imager_1_1_configuration.html", null ],
    [ "BioImager.Imager.ControllerFuncs", "class_bio_imager_1_1_imager_1_1_controller_funcs.html", null ],
    [ "BioImager.DBitmap", "class_bio_imager_1_1_d_bitmap.html", null ],
    [ "BioImager.DCamera", "class_bio_imager_1_1_d_camera.html", null ],
    [ "BioImager.DColorShader", "class_bio_imager_1_1_d_color_shader.html", null ],
    [ "BioImager.DDX11", "class_bio_imager_1_1_d_d_x11.html", null ],
    [ "BioImager.DGraphics", "class_bio_imager_1_1_d_graphics.html", null ],
    [ "BioImager.DInput", "class_bio_imager_1_1_d_input.html", null ],
    [ "BioImager.DModel", "class_bio_imager_1_1_d_model.html", null ],
    [ "BioImager.DSystem", "class_bio_imager_1_1_d_system.html", null ],
    [ "BioImager.DSystemConfiguration", "class_bio_imager_1_1_d_system_configuration.html", null ],
    [ "BioImager.DTimer", "class_bio_imager_1_1_d_timer.html", null ],
    [ "BioImager.Filt", "class_bio_imager_1_1_filt.html", null ],
    [ "BioImager.FilterWheel", "class_bio_imager_1_1_filter_wheel.html", null ],
    [ "BioImager.FloodFillRange", "struct_bio_imager_1_1_flood_fill_range.html", null ],
    [ "BioImager.FloodFillRangeQueue", "class_bio_imager_1_1_flood_fill_range_queue.html", null ],
    [ "BioImager.Focus", "class_bio_imager_1_1_focus.html", null ],
    [ "Form", null, [
      [ "BioImager.About", "class_bio_imager_1_1_about.html", null ],
      [ "BioImager.Action", "class_bio_imager_1_1_action.html", null ],
      [ "BioImager.ApplyFilter", "class_bio_imager_1_1_apply_filter.html", null ],
      [ "BioImager.BioConsole", "class_bio_imager_1_1_bio_console.html", null ],
      [ "BioImager.CellImager", "class_bio_imager_1_1_cell_imager.html", null ],
      [ "BioImager.ChannelsTool", "class_bio_imager_1_1_channels_tool.html", null ],
      [ "BioImager.ColorTool", "class_bio_imager_1_1_color_tool.html", null ],
      [ "BioImager.Filter", "class_bio_imager_1_1_filter.html", null ],
      [ "BioImager.FunctionForm", "class_bio_imager_1_1_function_form.html", null ],
      [ "BioImager.Graphics.FloodTool", "class_bio_imager_1_1_graphics_1_1_flood_tool.html", null ],
      [ "BioImager.Graphics.PenTool", "class_bio_imager_1_1_graphics_1_1_pen_tool.html", null ],
      [ "BioImager.ImageTiles", "class_bio_imager_1_1_image_tiles.html", null ],
      [ "BioImager.ImageWindow", "class_bio_imager_1_1_image_window.html", null ],
      [ "BioImager.Imager", "class_bio_imager_1_1_imager.html", null ],
      [ "BioImager.ImagesToStack", "class_bio_imager_1_1_images_to_stack.html", null ],
      [ "BioImager.ImagesView", "class_bio_imager_1_1_images_view.html", null ],
      [ "BioImager.Library", "class_bio_imager_1_1_library.html", null ],
      [ "BioImager.Light", "class_bio_imager_1_1_light.html", null ],
      [ "BioImager.MagicSelect", "class_bio_imager_1_1_magic_select.html", null ],
      [ "BioImager.MicroscopeSetup", "class_bio_imager_1_1_microscope_setup.html", null ],
      [ "BioImager.NodeView", "class_bio_imager_1_1_node_view.html", null ],
      [ "BioImager.OpenInTab", "class_bio_imager_1_1_open_in_tab.html", null ],
      [ "BioImager.PlaySpeed", "class_bio_imager_1_1_play_speed.html", null ],
      [ "BioImager.Plot", "class_bio_imager_1_1_plot.html", null ],
      [ "BioImager.Progress", "class_bio_imager_1_1_progress.html", null ],
      [ "BioImager.ROIManager", "class_bio_imager_1_1_r_o_i_manager.html", null ],
      [ "BioImager.RangeTool", "class_bio_imager_1_1_range_tool.html", null ],
      [ "BioImager.Recorder", "class_bio_imager_1_1_recorder.html", null ],
      [ "BioImager.Recordings", "class_bio_imager_1_1_recordings.html", null ],
      [ "BioImager.Resolutions", "class_bio_imager_1_1_resolutions.html", null ],
      [ "BioImager.Scripting", "class_bio_imager_1_1_scripting.html", null ],
      [ "BioImager.SelectRecording", "class_bio_imager_1_1_select_recording.html", null ],
      [ "BioImager.Series", "class_bio_imager_1_1_series.html", null ],
      [ "BioImager.SetTool", "class_bio_imager_1_1_set_tool.html", null ],
      [ "BioImager.Setup", "class_bio_imager_1_1_setup.html", null ],
      [ "BioImager.StackTools", "class_bio_imager_1_1_stack_tools.html", null ],
      [ "BioImager.StageTool", "class_bio_imager_1_1_stage_tool.html", null ],
      [ "BioImager.TabsView", "class_bio_imager_1_1_tabs_view.html", null ],
      [ "BioImager.TextInput", "class_bio_imager_1_1_text_input.html", null ],
      [ "BioImager.Tools", "class_bio_imager_1_1_tools.html", null ],
      [ "BioImager.View3D", "class_bio_imager_1_1_view3_d.html", null ],
      [ "BioImager.XMLView", "class_bio_imager_1_1_x_m_l_view.html", null ]
    ] ],
    [ "BioImager.Function", "class_bio_imager_1_1_function.html", null ],
    [ "BioImager.HXPShutter", "class_bio_imager_1_1_h_x_p_shutter.html", null ],
    [ "IDisposable", null, [
      [ "BioImager.BioImage", "class_bio_imager_1_1_bio_image.html", null ],
      [ "BioImager.Direct2D", "class_bio_imager_1_1_direct2_d.html", null ],
      [ "BioImager.Graphics.Graphics", "class_bio_imager_1_1_graphics_1_1_graphics.html", null ],
      [ "BioImager.Graphics.Pen", "struct_bio_imager_1_1_graphics_1_1_pen.html", null ],
      [ "BioImager.ImageView", "class_bio_imager_1_1_image_view.html", null ]
    ] ],
    [ "BioImager.ImageInfo", "class_bio_imager_1_1_image_info.html", null ],
    [ "BioImager.ImageJ", "class_bio_imager_1_1_image_j.html", null ],
    [ "BioImager.BioImage.ImageJDesc", "class_bio_imager_1_1_bio_image_1_1_image_j_desc.html", null ],
    [ "BioImager.Lib", "class_bio_imager_1_1_lib.html", null ],
    [ "BioImager.LightSource", "class_bio_imager_1_1_light_source.html", null ],
    [ "BioImager.MouseOperations", "class_bio_imager_1_1_mouse_operations.html", null ],
    [ "BioImager.MouseOperations.MousePoint", "struct_bio_imager_1_1_mouse_operations_1_1_mouse_point.html", null ],
    [ "BioImager.Filter.Node", "class_bio_imager_1_1_filter_1_1_node.html", null ],
    [ "BioImager.NodeView.Node", "class_bio_imager_1_1_node_view_1_1_node.html", null ],
    [ "BioImager.Recordings.Node", "class_bio_imager_1_1_recordings_1_1_node.html", null ],
    [ "BioImager.Lib.ObjectInfo", "class_bio_imager_1_1_lib_1_1_object_info.html", null ],
    [ "BioImager.Objectives.Objective", "class_bio_imager_1_1_objectives_1_1_objective.html", null ],
    [ "BioImager.Objectives", "class_bio_imager_1_1_objectives.html", null ],
    [ "BioImager.Imager.Profile", "class_bio_imager_1_1_imager_1_1_profile.html", null ],
    [ "BioImager.Automation.Recording", "class_bio_imager_1_1_automation_1_1_recording.html", null ],
    [ "BioImager.Win32.Rect", "struct_bio_imager_1_1_win32_1_1_rect.html", null ],
    [ "BioImager.Resolution", "struct_bio_imager_1_1_resolution.html", null ],
    [ "RichTextBox", null, [
      [ "BioImager.CodeView.ScrollTextBox", "class_bio_imager_1_1_code_view_1_1_scroll_text_box.html", null ]
    ] ],
    [ "BioImager.RLShutter", "class_bio_imager_1_1_r_l_shutter.html", null ],
    [ "BioImager.ROI", "class_bio_imager_1_1_r_o_i.html", null ],
    [ "BioImager.ImageJ.RoiDecoder", "class_bio_imager_1_1_image_j_1_1_roi_decoder.html", null ],
    [ "BioImager.ImageJ.RoiEncoder", "class_bio_imager_1_1_image_j_1_1_roi_encoder.html", null ],
    [ "BioImager.Scripting.Script", "class_bio_imager_1_1_scripting_1_1_script.html", null ],
    [ "BioImager.SDK", "class_bio_imager_1_1_s_d_k.html", null ],
    [ "BioImager.Stage", "class_bio_imager_1_1_stage.html", null ],
    [ "BioImager.Scripting.State", "class_bio_imager_1_1_scripting_1_1_state.html", null ],
    [ "BioImager.TLShutter", "class_bio_imager_1_1_t_l_shutter.html", null ],
    [ "BioImager.Tools.Tool", "class_bio_imager_1_1_tools_1_1_tool.html", null ],
    [ "BioImager.Lib.TypeInfo", "class_bio_imager_1_1_lib_1_1_type_info.html", null ],
    [ "System.Windows.Forms.UserControl", null, [
      [ "BioImager.XmlTreeDisplay", "class_bio_imager_1_1_xml_tree_display.html", null ]
    ] ],
    [ "UserControl", null, [
      [ "BioImager.CodeView", "class_bio_imager_1_1_code_view.html", null ],
      [ "BioImager.HistogramControl", "class_bio_imager_1_1_histogram_control.html", null ],
      [ "BioImager.ImageView", "class_bio_imager_1_1_image_view.html", null ]
    ] ],
    [ "BioImager.Win32", "class_bio_imager_1_1_win32.html", null ]
];