var hierarchy =
[
    [ "BioCore.Graphics.AbstractFloodFiller", "class_bio_core_1_1_graphics_1_1_abstract_flood_filler.html", [
      [ "BioCore.Graphics.QueueLinearFloodFiller", "class_bio_core_1_1_graphics_1_1_queue_linear_flood_filler.html", null ]
    ] ],
    [ "BioCore.Automation.Action", "class_bio_core_1_1_automation_1_1_action.html", null ],
    [ "BioCore.App", "class_bio_core_1_1_app.html", null ],
    [ "BioCore.Automation", "class_bio_core_1_1_automation.html", null ],
    [ "BioCore.Channel.ChannelInfo", "struct_bio_core_1_1_channel_1_1_channel_info.html", null ],
    [ "BioCore.ImageJ.Macro.Command", "class_bio_core_1_1_image_j_1_1_macro_1_1_command.html", null ],
    [ "BioCore.Graphics.Configuration", "class_bio_core_1_1_graphics_1_1_configuration.html", null ],
    [ "BioCore.Graphics.DBitmap", "class_bio_core_1_1_graphics_1_1_d_bitmap.html", null ],
    [ "BioCore.Filt", "class_bio_core_1_1_filt.html", null ],
    [ "BioCore.Graphics.FloodFillRange", "struct_bio_core_1_1_graphics_1_1_flood_fill_range.html", null ],
    [ "BioCore.Graphics.FloodFillRangeQueue", "class_bio_core_1_1_graphics_1_1_flood_fill_range_queue.html", null ],
    [ "BioCore.Focus", "class_bio_core_1_1_focus.html", null ],
    [ "Form", null, [
      [ "BioCore.About", "class_bio_core_1_1_about.html", null ],
      [ "BioCore.ApplyFilter", "class_bio_core_1_1_apply_filter.html", null ],
      [ "BioCore.BioConsole", "class_bio_core_1_1_bio_console.html", null ],
      [ "BioCore.ChannelsTool", "class_bio_core_1_1_channels_tool.html", null ],
      [ "BioCore.ColorTool", "class_bio_core_1_1_color_tool.html", null ],
      [ "BioCore.Filter", "class_bio_core_1_1_filter.html", null ],
      [ "BioCore.FunctionForm", "class_bio_core_1_1_function_form.html", null ],
      [ "BioCore.Graphics.FloodTool", "class_bio_core_1_1_graphics_1_1_flood_tool.html", null ],
      [ "BioCore.Graphics.PenTool", "class_bio_core_1_1_graphics_1_1_pen_tool.html", null ],
      [ "BioCore.ImageWindow", "class_bio_core_1_1_image_window.html", null ],
      [ "BioCore.ImagesToStack", "class_bio_core_1_1_images_to_stack.html", null ],
      [ "BioCore.Library", "class_bio_core_1_1_library.html", null ],
      [ "BioCore.MagicSelect", "class_bio_core_1_1_magic_select.html", null ],
      [ "BioCore.NodeView", "class_bio_core_1_1_node_view.html", null ],
      [ "BioCore.OpenInTab", "class_bio_core_1_1_open_in_tab.html", null ],
      [ "BioCore.PlaySpeed", "class_bio_core_1_1_play_speed.html", null ],
      [ "BioCore.Plot", "class_bio_core_1_1_plot.html", null ],
      [ "BioCore.Progress", "class_bio_core_1_1_progress.html", null ],
      [ "BioCore.ROIManager", "class_bio_core_1_1_r_o_i_manager.html", null ],
      [ "BioCore.RangeTool", "class_bio_core_1_1_range_tool.html", null ],
      [ "BioCore.Recorder", "class_bio_core_1_1_recorder.html", null ],
      [ "BioCore.Recordings", "class_bio_core_1_1_recordings.html", null ],
      [ "BioCore.Resolutions", "class_bio_core_1_1_resolutions.html", null ],
      [ "BioCore.Scripting", "class_bio_core_1_1_scripting.html", null ],
      [ "BioCore.SelectRecording", "class_bio_core_1_1_select_recording.html", null ],
      [ "BioCore.Series", "class_bio_core_1_1_series.html", null ],
      [ "BioCore.SetTool", "class_bio_core_1_1_set_tool.html", null ],
      [ "BioCore.Source.ImagesView", "class_bio_core_1_1_source_1_1_images_view.html", null ],
      [ "BioCore.StackTools", "class_bio_core_1_1_stack_tools.html", null ],
      [ "BioCore.TabsView", "class_bio_core_1_1_tabs_view.html", null ],
      [ "BioCore.TextInput", "class_bio_core_1_1_text_input.html", null ],
      [ "BioCore.Tools", "class_bio_core_1_1_tools.html", null ],
      [ "BioCore.View3D", "class_bio_core_1_1_view3_d.html", null ],
      [ "BioCore.XMLView", "class_bio_core_1_1_x_m_l_view.html", null ]
    ] ],
    [ "BioCore.Function", "class_bio_core_1_1_function.html", null ],
    [ "BioCore.ImageJ.Macro.Function", "class_bio_core_1_1_image_j_1_1_macro_1_1_function.html", null ],
    [ "IDisposable", null, [
      [ "BioCore.BioImage", "class_bio_core_1_1_bio_image.html", null ],
      [ "BioCore.BufferInfo", "class_bio_core_1_1_buffer_info.html", null ],
      [ "BioCore.Channel", "class_bio_core_1_1_channel.html", null ],
      [ "BioCore.ColorS", "struct_bio_core_1_1_color_s.html", null ],
      [ "BioCore.Graphics.Direct2D", "class_bio_core_1_1_graphics_1_1_direct2_d.html", null ],
      [ "BioCore.Graphics.Graphics", "class_bio_core_1_1_graphics_1_1_graphics.html", null ],
      [ "BioCore.Graphics.Pen", "struct_bio_core_1_1_graphics_1_1_pen.html", null ],
      [ "BioCore.ImageView", "class_bio_core_1_1_image_view.html", null ],
      [ "BioCore.ROI.Mask", "class_bio_core_1_1_r_o_i_1_1_mask.html", null ]
    ] ],
    [ "BioCore.ImageInfo", "class_bio_core_1_1_image_info.html", null ],
    [ "BioCore.ImageJ", "class_bio_core_1_1_image_j.html", null ],
    [ "BioCore.BioImage.ImageJDesc", "class_bio_core_1_1_bio_image_1_1_image_j_desc.html", null ],
    [ "BioCore.Plugin.IPlugin", "interface_bio_core_1_1_plugin_1_1_i_plugin.html", null ],
    [ "BioCore.Lib", "class_bio_core_1_1_lib.html", null ],
    [ "BioCore.MouseOperations", "class_bio_core_1_1_mouse_operations.html", null ],
    [ "BioCore.MouseOperations.MousePoint", "struct_bio_core_1_1_mouse_operations_1_1_mouse_point.html", null ],
    [ "BioCore.Filter.Node", "class_bio_core_1_1_filter_1_1_node.html", null ],
    [ "BioCore.NodeView.Node", "class_bio_core_1_1_node_view_1_1_node.html", null ],
    [ "BioCore.Recordings.Node", "class_bio_core_1_1_recordings_1_1_node.html", null ],
    [ "BioCore.Lib.ObjectInfo", "class_bio_core_1_1_lib_1_1_object_info.html", null ],
    [ "BioCore.Objectives.Objective", "class_bio_core_1_1_objectives_1_1_objective.html", null ],
    [ "BioCore.Objectives", "class_bio_core_1_1_objectives.html", null ],
    [ "BioCore.Plane", "class_bio_core_1_1_plane.html", null ],
    [ "BioCore.Plugin", "class_bio_core_1_1_plugin.html", null ],
    [ "BioCore.Point3D", "struct_bio_core_1_1_point3_d.html", null ],
    [ "BioCore.PointD", "struct_bio_core_1_1_point_d.html", null ],
    [ "BioCore.Automation.Recording", "class_bio_core_1_1_automation_1_1_recording.html", null ],
    [ "BioCore.Win32.Rect", "struct_bio_core_1_1_win32_1_1_rect.html", null ],
    [ "BioCore.RectangleD", "struct_bio_core_1_1_rectangle_d.html", null ],
    [ "BioCore.Resolution", "struct_bio_core_1_1_resolution.html", null ],
    [ "RichTextBox", null, [
      [ "BioCore.CodeView.ScrollTextBox", "class_bio_core_1_1_code_view_1_1_scroll_text_box.html", null ]
    ] ],
    [ "BioCore.RLShutter", "class_bio_core_1_1_r_l_shutter.html", null ],
    [ "BioCore.ROI", "class_bio_core_1_1_r_o_i.html", null ],
    [ "BioCore.ImageJ.RoiDecoder", "class_bio_core_1_1_image_j_1_1_roi_decoder.html", null ],
    [ "BioCore.ImageJ.RoiEncoder", "class_bio_core_1_1_image_j_1_1_roi_encoder.html", null ],
    [ "BioCore.BioImage.WellPlate.Well.Sample", "class_bio_core_1_1_bio_image_1_1_well_plate_1_1_well_1_1_sample.html", null ],
    [ "BioCore.Scripting.Script", "class_bio_core_1_1_scripting_1_1_script.html", null ],
    [ "BioCore.Stage", "class_bio_core_1_1_stage.html", null ],
    [ "BioCore.Scripting.State", "class_bio_core_1_1_scripting_1_1_state.html", null ],
    [ "BioCore.Statistics", "class_bio_core_1_1_statistics.html", null ],
    [ "BioCore.TLShutter", "class_bio_core_1_1_t_l_shutter.html", null ],
    [ "BioCore.Tools.Tool", "class_bio_core_1_1_tools_1_1_tool.html", null ],
    [ "BioCore.Lib.TypeInfo", "class_bio_core_1_1_lib_1_1_type_info.html", null ],
    [ "System.Windows.Forms.UserControl", null, [
      [ "BioCore.XmlTreeDisplay", "class_bio_core_1_1_xml_tree_display.html", null ]
    ] ],
    [ "UserControl", null, [
      [ "BioCore.CodeView", "class_bio_core_1_1_code_view.html", null ],
      [ "BioCore.HistogramControl", "class_bio_core_1_1_histogram_control.html", null ],
      [ "BioCore.ImageView", "class_bio_core_1_1_image_view.html", null ]
    ] ],
    [ "BioCore.VolumeD", "struct_bio_core_1_1_volume_d.html", null ],
    [ "BioCore.BioImage.WellPlate.Well", "class_bio_core_1_1_bio_image_1_1_well_plate_1_1_well.html", null ],
    [ "BioCore.BioImage.WellPlate", "class_bio_core_1_1_bio_image_1_1_well_plate.html", null ],
    [ "BioCore.Win32", "class_bio_core_1_1_win32.html", null ],
    [ "BioCore.ZCT", "struct_bio_core_1_1_z_c_t.html", null ],
    [ "BioCore.ZCTXY", "struct_bio_core_1_1_z_c_t_x_y.html", null ]
];