var dir_669348b718faff750adc1226db43aa73 =
[
    [ "ML", "dir_20726f830fd1141005a444f44fc1c8f2.html", "dir_20726f830fd1141005a444f44fc1c8f2" ],
    [ "About.cs", "_about_8cs_source.html", null ],
    [ "App.cs", "_app_8cs_source.html", null ],
    [ "ApplyFilter.cs", "_apply_filter_8cs_source.html", null ],
    [ "BioConsole.cs", "_bio_console_8cs_source.html", null ],
    [ "ChannelsTool.cs", "_channels_tool_8cs_source.html", null ],
    [ "ColorTool.cs", "_color_tool_8cs_source.html", null ],
    [ "ComboPicker.cs", "_combo_picker_8cs_source.html", null ],
    [ "Filters.cs", "_filters_8cs_source.html", null ],
    [ "Functions.cs", "_functions_8cs_source.html", null ],
    [ "HistogramControl.cs", "_histogram_control_8cs_source.html", null ],
    [ "ImageView.cs", "_image_view_8cs_source.html", null ],
    [ "MagicSelect.cs", "_magic_select_8cs_source.html", null ],
    [ "Microscope.cs", "_microscope_8cs_source.html", null ],
    [ "NodeView.cs", "_node_view_8cs_source.html", null ],
    [ "NumberPicker.cs", "_number_picker_8cs_source.html", null ],
    [ "Plate.cs", "_plate_8cs_source.html", null ],
    [ "Play.cs", "_play_8cs_source.html", null ],
    [ "Plot.cs", "_plot_8cs_source.html", null ],
    [ "Plugin.cs", "_plugin_8cs_source.html", null ],
    [ "Progress.cs", "_progress_8cs_source.html", null ],
    [ "Recorder.cs", "_recorder_8cs_source.html", null ],
    [ "Resolutions.cs", "_resolutions_8cs_source.html", null ],
    [ "ROIManager.cs", "_r_o_i_manager_8cs_source.html", null ],
    [ "Scripting.cs", "_scripting_8cs_source.html", null ],
    [ "Search.cs", "_search_8cs_source.html", null ],
    [ "SetTool.cs", "_set_tool_8cs_source.html", null ],
    [ "StackTools.cs", "_stack_tools_8cs_source.html", null ],
    [ "TabsView.cs", "_tabs_view_8cs_source.html", null ],
    [ "TextInput.cs", "_text_input_8cs_source.html", null ],
    [ "Tolerance.cs", "_tolerance_8cs_source.html", null ],
    [ "Tools.cs", "_tools_8cs_source.html", null ],
    [ "Updater.cs", "_updater_8cs_source.html", null ]
];